//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/logging/Formatter.java
//

#ifndef _JavaUtilLoggingFormatter_H_
#define _JavaUtilLoggingFormatter_H_

@class JavaUtilLoggingHandler;
@class JavaUtilLoggingLogRecord;

#import "JreEmulation.h"

@interface JavaUtilLoggingFormatter : NSObject {
}

- (instancetype)init;

- (NSString *)formatWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)r;

- (NSString *)formatMessageWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)r;

- (NSString *)getHeadWithJavaUtilLoggingHandler:(JavaUtilLoggingHandler *)h;

- (NSString *)getTailWithJavaUtilLoggingHandler:(JavaUtilLoggingHandler *)h;

@end

__attribute__((always_inline)) inline void JavaUtilLoggingFormatter_init() {}

#endif // _JavaUtilLoggingFormatter_H_
