//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/logging/StreamHandler.java
//

#ifndef _JavaUtilLoggingStreamHandler_H_
#define _JavaUtilLoggingStreamHandler_H_

@class JavaIoOutputStream;
@class JavaIoWriter;
@class JavaUtilLoggingFormatter;
@class JavaUtilLoggingLogRecord;

#import "JreEmulation.h"
#include "java/util/logging/Handler.h"

@interface JavaUtilLoggingStreamHandler : JavaUtilLoggingHandler {
}

- (instancetype)init;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os;

- (instancetype)initWithNSString:(NSString *)defaultLevel
                    withNSString:(NSString *)defaultFilter
                    withNSString:(NSString *)defaultFormatter
                    withNSString:(NSString *)defaultEncoding;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os
              withJavaUtilLoggingFormatter:(JavaUtilLoggingFormatter *)formatter;

- (void)internalSetOutputStreamWithJavaIoOutputStream:(JavaIoOutputStream *)newOs;

- (void)setOutputStreamWithJavaIoOutputStream:(JavaIoOutputStream *)os;

- (void)setEncodingWithNSString:(NSString *)charsetName;

- (void)closeWithBoolean:(jboolean)closeStream;

- (void)close;

- (void)flush;

- (void)publishWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;

- (jboolean)isLoggableWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;

@end

__attribute__((always_inline)) inline void JavaUtilLoggingStreamHandler_init() {}

#endif // _JavaUtilLoggingStreamHandler_H_
