//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/junit/framework/Protectable.java
//

#ifndef _JunitFrameworkProtectable_H_
#define _JunitFrameworkProtectable_H_

#import "JreEmulation.h"

@protocol JunitFrameworkProtectable < NSObject, JavaObject >

- (void)protect;

@end

__attribute__((always_inline)) inline void JunitFrameworkProtectable_init() {}

#endif // _JunitFrameworkProtectable_H_
