//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/ref/PhantomReference.java
//

#ifndef _JavaLangRefPhantomReference_H_
#define _JavaLangRefPhantomReference_H_

@class JavaLangRefReferenceQueue;

#import "JreEmulation.h"
#include "java/lang/ref/Reference.h"

@interface JavaLangRefPhantomReference : JavaLangRefReference {
}

- (instancetype)initWithId:(id)r
withJavaLangRefReferenceQueue:(JavaLangRefReferenceQueue *)q;

- (id)get;

@end

__attribute__((always_inline)) inline void JavaLangRefPhantomReference_init() {}

#endif // _JavaLangRefPhantomReference_H_
