//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/text/CollationKey.java
//

#ifndef _JavaTextCollationKey_H_
#define _JavaTextCollationKey_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/lang/Comparable.h"

@interface JavaTextCollationKey : NSObject < JavaLangComparable > {
}

- (instancetype)initWithNSString:(NSString *)source;

- (jint)compareToWithId:(JavaTextCollationKey *)value;

- (NSString *)getSourceString;

- (IOSByteArray *)toByteArray;

@end

__attribute__((always_inline)) inline void JavaTextCollationKey_init() {}

#endif // _JavaTextCollationKey_H_
