//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/text/FieldPosition.java
//

#ifndef _JavaTextFieldPosition_H_
#define _JavaTextFieldPosition_H_

@class JavaTextFormat_Field;

#import "JreEmulation.h"

@interface JavaTextFieldPosition : NSObject {
}

- (instancetype)initWithInt:(jint)field;

- (instancetype)initWithJavaTextFormat_Field:(JavaTextFormat_Field *)attribute;

- (instancetype)initWithJavaTextFormat_Field:(JavaTextFormat_Field *)attribute
                                     withInt:(jint)field;

- (jboolean)isEqual:(id)object;

- (jint)getBeginIndex;

- (jint)getEndIndex;

- (jint)getField;

- (JavaTextFormat_Field *)getFieldAttribute;

- (NSUInteger)hash;

- (void)setBeginIndexWithInt:(jint)index;

- (void)setEndIndexWithInt:(jint)index;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaTextFieldPosition_init() {}

#endif // _JavaTextFieldPosition_H_
