//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/text/ParsePosition.java
//

#ifndef _JavaTextParsePosition_H_
#define _JavaTextParsePosition_H_

#import "JreEmulation.h"

@interface JavaTextParsePosition : NSObject {
}

- (instancetype)initWithInt:(jint)index;

- (jboolean)isEqual:(id)object;

- (jint)getErrorIndex;

- (jint)getIndex;

- (NSUInteger)hash;

- (void)setErrorIndexWithInt:(jint)index;

- (void)setIndexWithInt:(jint)index;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaTextParsePosition_init() {}

#endif // _JavaTextParsePosition_H_
