//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/text/InputFilter.java
//

#ifndef _AndroidTextInputFilter_H_
#define _AndroidTextInputFilter_H_

@protocol AndroidTextSpanned;
@protocol JavaLangCharSequence;

#import "JreEmulation.h"

@protocol AndroidTextInputFilter < NSObject, JavaObject >

- (id<JavaLangCharSequence>)filterWithJavaLangCharSequence:(id<JavaLangCharSequence>)source
                                                   withInt:(jint)start
                                                   withInt:(jint)end
                                    withAndroidTextSpanned:(id<AndroidTextSpanned>)dest
                                                   withInt:(jint)dstart
                                                   withInt:(jint)dend;

@end

__attribute__((always_inline)) inline void AndroidTextInputFilter_init() {}

@interface AndroidTextInputFilter_AllCaps : NSObject < AndroidTextInputFilter > {
}

- (id<JavaLangCharSequence>)filterWithJavaLangCharSequence:(id<JavaLangCharSequence>)source
                                                   withInt:(jint)start
                                                   withInt:(jint)end
                                    withAndroidTextSpanned:(id<AndroidTextSpanned>)dest
                                                   withInt:(jint)dstart
                                                   withInt:(jint)dend;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void AndroidTextInputFilter_AllCaps_init() {}

@interface AndroidTextInputFilter_LengthFilter : NSObject < AndroidTextInputFilter > {
}

- (instancetype)initWithInt:(jint)max;

- (id<JavaLangCharSequence>)filterWithJavaLangCharSequence:(id<JavaLangCharSequence>)source
                                                   withInt:(jint)start
                                                   withInt:(jint)end
                                    withAndroidTextSpanned:(id<AndroidTextSpanned>)dest
                                                   withInt:(jint)dstart
                                                   withInt:(jint)dend;

@end

__attribute__((always_inline)) inline void AndroidTextInputFilter_LengthFilter_init() {}

#endif // _AndroidTextInputFilter_H_
