//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/reflect/AnnotatedElement.java
//

#ifndef _JavaLangReflectAnnotatedElement_H_
#define _JavaLangReflectAnnotatedElement_H_

@class IOSClass;
@class IOSObjectArray;
@protocol JavaLangAnnotationAnnotation;

#import "JreEmulation.h"

@protocol JavaLangReflectAnnotatedElement < NSObject, JavaObject >

- (id)getAnnotationWithIOSClass:(IOSClass *)annotationType;

- (IOSObjectArray *)getAnnotations;

- (IOSObjectArray *)getDeclaredAnnotations;

- (jboolean)isAnnotationPresentWithIOSClass:(IOSClass *)annotationType;

@end

__attribute__((always_inline)) inline void JavaLangReflectAnnotatedElement_init() {}

#endif // _JavaLangReflectAnnotatedElement_H_
