//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/reflect/MalformedParameterizedTypeException.java
//

#ifndef _JavaLangReflectMalformedParameterizedTypeException_H_
#define _JavaLangReflectMalformedParameterizedTypeException_H_

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define JavaLangReflectMalformedParameterizedTypeException_serialVersionUID -5696557788586220964LL

@interface JavaLangReflectMalformedParameterizedTypeException : JavaLangRuntimeException {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaLangReflectMalformedParameterizedTypeException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangReflectMalformedParameterizedTypeException, serialVersionUID, jlong)

#endif // _JavaLangReflectMalformedParameterizedTypeException_H_
