//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/InputSource.java
//

#ifndef _OrgXmlSaxInputSource_H_
#define _OrgXmlSaxInputSource_H_

@class JavaIoInputStream;
@class JavaIoReader;

#import "JreEmulation.h"

@interface OrgXmlSaxInputSource : NSObject {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)systemId;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)byteStream;

- (instancetype)initWithJavaIoReader:(JavaIoReader *)characterStream;

- (void)setPublicIdWithNSString:(NSString *)publicId;

- (NSString *)getPublicId;

- (void)setSystemIdWithNSString:(NSString *)systemId;

- (NSString *)getSystemId;

- (void)setByteStreamWithJavaIoInputStream:(JavaIoInputStream *)byteStream;

- (JavaIoInputStream *)getByteStream;

- (void)setEncodingWithNSString:(NSString *)encoding;

- (NSString *)getEncoding;

- (void)setCharacterStreamWithJavaIoReader:(JavaIoReader *)characterStream;

- (JavaIoReader *)getCharacterStream;

@end

__attribute__((always_inline)) inline void OrgXmlSaxInputSource_init() {}

#endif // _OrgXmlSaxInputSource_H_
