//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/eventbus/EventHandler.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonEventbusEventHandler_RESTRICT
#define ComGoogleCommonEventbusEventHandler_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonEventbusEventHandler_RESTRICT
#if !defined (_ComGoogleCommonEventbusEventHandler_) && (ComGoogleCommonEventbusEventHandler_INCLUDE_ALL || ComGoogleCommonEventbusEventHandler_INCLUDE)
#define _ComGoogleCommonEventbusEventHandler_

@class JavaLangReflectMethod;


@interface ComGoogleCommonEventbusEventHandler : NSObject {
}

- (instancetype)initWithId:(id)target
 withJavaLangReflectMethod:(JavaLangReflectMethod *)method;

- (void)handleEventWithId:(id)event;

- (NSString *)description;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

@end

__attribute__((always_inline)) inline void ComGoogleCommonEventbusEventHandler_init() {}
#endif
