//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/base/Charsets.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonBaseCharsets_RESTRICT
#define ComGoogleCommonBaseCharsets_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonBaseCharsets_RESTRICT
#if !defined (_ComGoogleCommonBaseCharsets_) && (ComGoogleCommonBaseCharsets_INCLUDE_ALL || ComGoogleCommonBaseCharsets_INCLUDE)
#define _ComGoogleCommonBaseCharsets_

@class JavaNioCharsetCharset;


@interface ComGoogleCommonBaseCharsets : NSObject {
}

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonBaseCharsets_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonBaseCharsets)

FOUNDATION_EXPORT JavaNioCharsetCharset *ComGoogleCommonBaseCharsets_US_ASCII_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseCharsets, US_ASCII_, JavaNioCharsetCharset *)

FOUNDATION_EXPORT JavaNioCharsetCharset *ComGoogleCommonBaseCharsets_ISO_8859_1_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseCharsets, ISO_8859_1_, JavaNioCharsetCharset *)

FOUNDATION_EXPORT JavaNioCharsetCharset *ComGoogleCommonBaseCharsets_UTF_8_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseCharsets, UTF_8_, JavaNioCharsetCharset *)

FOUNDATION_EXPORT JavaNioCharsetCharset *ComGoogleCommonBaseCharsets_UTF_16BE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseCharsets, UTF_16BE_, JavaNioCharsetCharset *)

FOUNDATION_EXPORT JavaNioCharsetCharset *ComGoogleCommonBaseCharsets_UTF_16LE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseCharsets, UTF_16LE_, JavaNioCharsetCharset *)

FOUNDATION_EXPORT JavaNioCharsetCharset *ComGoogleCommonBaseCharsets_UTF_16_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseCharsets, UTF_16_, JavaNioCharsetCharset *)
#endif
