//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/base/Defaults.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonBaseDefaults_RESTRICT
#define ComGoogleCommonBaseDefaults_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonBaseDefaults_RESTRICT
#if !defined (_ComGoogleCommonBaseDefaults_) && (ComGoogleCommonBaseDefaults_INCLUDE_ALL || ComGoogleCommonBaseDefaults_INCLUDE)
#define _ComGoogleCommonBaseDefaults_

@class IOSClass;
@protocol JavaUtilMap;


@interface ComGoogleCommonBaseDefaults : NSObject {
}

+ (id)defaultValueWithIOSClass:(IOSClass *)type;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonBaseDefaults_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonBaseDefaults)
FOUNDATION_EXPORT id ComGoogleCommonBaseDefaults_defaultValueWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonBaseDefaults_DEFAULTS_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonBaseDefaults, DEFAULTS_, id<JavaUtilMap>)
#endif
