//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/exceptions/base/MockitoException.java
//

#ifndef _OrgMockitoExceptionsBaseMockitoException_H_
#define _OrgMockitoExceptionsBaseMockitoException_H_

@class IOSObjectArray;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define OrgMockitoExceptionsBaseMockitoException_serialVersionUID 1LL

@interface OrgMockitoExceptionsBaseMockitoException : JavaLangRuntimeException {
 @public
  IOSObjectArray *unfilteredStackTrace_;
}

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)t;

- (instancetype)initWithNSString:(NSString *)message;

- (void)filterStackTrace;

- (IOSObjectArray *)getUnfilteredStackTrace;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoExceptionsBaseMockitoException *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsBaseMockitoException_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoExceptionsBaseMockitoException, unfilteredStackTrace_, IOSObjectArray *)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsBaseMockitoException, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsBaseMockitoException_H_
