//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/exceptions/verification/NeverWantedButInvoked.java
//

#ifndef _OrgMockitoExceptionsVerificationNeverWantedButInvoked_H_
#define _OrgMockitoExceptionsVerificationNeverWantedButInvoked_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoAssertionError.h"

#define OrgMockitoExceptionsVerificationNeverWantedButInvoked_serialVersionUID 1LL

@interface OrgMockitoExceptionsVerificationNeverWantedButInvoked : OrgMockitoExceptionsBaseMockitoAssertionError {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsVerificationNeverWantedButInvoked_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsVerificationNeverWantedButInvoked, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsVerificationNeverWantedButInvoked_H_
