//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/exceptions/verification/TooManyActualInvocations.java
//

#ifndef _OrgMockitoExceptionsVerificationTooManyActualInvocations_H_
#define _OrgMockitoExceptionsVerificationTooManyActualInvocations_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoAssertionError.h"

#define OrgMockitoExceptionsVerificationTooManyActualInvocations_serialVersionUID 1LL

@interface OrgMockitoExceptionsVerificationTooManyActualInvocations : OrgMockitoExceptionsBaseMockitoAssertionError {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsVerificationTooManyActualInvocations_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsVerificationTooManyActualInvocations, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsVerificationTooManyActualInvocations_H_
