//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/sql/SQLNonTransientException.java
//

#ifndef _JavaSqlSQLNonTransientException_H_
#define _JavaSqlSQLNonTransientException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/sql/SQLException.h"

#define JavaSqlSQLNonTransientException_serialVersionUID -9104382843534716547LL

@interface JavaSqlSQLNonTransientException : JavaSqlSQLException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)reason;

- (instancetype)initWithNSString:(NSString *)reason
                    withNSString:(NSString *)sqlState;

- (instancetype)initWithNSString:(NSString *)reason
                    withNSString:(NSString *)sqlState
                         withInt:(jint)vendorCode;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithNSString:(NSString *)reason
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithNSString:(NSString *)reason
                    withNSString:(NSString *)sqlState
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithNSString:(NSString *)reason
                    withNSString:(NSString *)sqlState
                         withInt:(jint)vendorCode
           withJavaLangThrowable:(JavaLangThrowable *)cause;


@end

__attribute__((always_inline)) inline void JavaSqlSQLNonTransientException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSqlSQLNonTransientException, serialVersionUID, jlong)

#endif // _JavaSqlSQLNonTransientException_H_
