//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/sql/Time.java
//

#ifndef _JavaSqlTime_H_
#define _JavaSqlTime_H_

@class JavaLangStringBuilder;

#import "JreEmulation.h"
#include "java/util/Date.h"

#define JavaSqlTime_serialVersionUID 8397324403548013681LL

@interface JavaSqlTime : JavaUtilDate {
}

- (instancetype)initWithInt:(jint)theHour
                    withInt:(jint)theMinute
                    withInt:(jint)theSecond;

- (instancetype)initWithLong:(jlong)theTime;

- (jint)getDate;

- (jint)getDay;

- (jint)getMonth;

- (jint)getYear;

- (void)setDateWithInt:(jint)i;

- (void)setMonthWithInt:(jint)i;

- (void)setYearWithInt:(jint)i;

- (void)setTimeWithLong:(jlong)time;

- (NSString *)description;

+ (JavaSqlTime *)valueOfWithNSString:(NSString *)timeString;

@end

__attribute__((always_inline)) inline void JavaSqlTime_init() {}
FOUNDATION_EXPORT JavaSqlTime *JavaSqlTime_valueOfWithNSString_(NSString *timeString);

J2OBJC_STATIC_FIELD_GETTER(JavaSqlTime, serialVersionUID, jlong)

FOUNDATION_EXPORT NSString *JavaSqlTime_PADDING_;
J2OBJC_STATIC_FIELD_GETTER(JavaSqlTime, PADDING_, NSString *)

#endif // _JavaSqlTime_H_
