//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/Guard.java
//

#ifndef _JavaSecurityGuard_H_
#define _JavaSecurityGuard_H_

#import "JreEmulation.h"

@protocol JavaSecurityGuard < NSObject, JavaObject >

- (void)checkGuardWithId:(id)object;

@end

__attribute__((always_inline)) inline void JavaSecurityGuard_init() {}

#endif // _JavaSecurityGuard_H_
