//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/GuardedObject.java
//

#ifndef _JavaSecurityGuardedObject_H_
#define _JavaSecurityGuardedObject_H_

@class JavaIoObjectOutputStream;
@protocol JavaSecurityGuard;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define JavaSecurityGuardedObject_serialVersionUID -5240450096227834308LL

@interface JavaSecurityGuardedObject : NSObject < JavaIoSerializable > {
}

- (instancetype)initWithId:(id)object
     withJavaSecurityGuard:(id<JavaSecurityGuard>)guard;

- (id)getObject;

@end

__attribute__((always_inline)) inline void JavaSecurityGuardedObject_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityGuardedObject, serialVersionUID, jlong)

#endif // _JavaSecurityGuardedObject_H_
