//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/Principal.java
//

#ifndef _JavaSecurityPrincipal_H_
#define _JavaSecurityPrincipal_H_

#import "JreEmulation.h"

@protocol JavaSecurityPrincipal < NSObject, JavaObject >

- (jboolean)isEqual:(id)obj;

- (NSString *)getName;

- (NSUInteger)hash;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaSecurityPrincipal_init() {}

#endif // _JavaSecurityPrincipal_H_
