//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/PrivilegedAction.java
//

#ifndef _JavaSecurityPrivilegedAction_H_
#define _JavaSecurityPrivilegedAction_H_

#import "JreEmulation.h"

@protocol JavaSecurityPrivilegedAction < NSObject, JavaObject >

- (id)run;

@end

__attribute__((always_inline)) inline void JavaSecurityPrivilegedAction_init() {}

#endif // _JavaSecurityPrivilegedAction_H_
