//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/ProtectionDomain.java
//

#ifndef _JavaSecurityProtectionDomain_H_
#define _JavaSecurityProtectionDomain_H_

@class IOSObjectArray;
@class JavaLangClassLoader;
@class JavaSecurityCodeSource;
@class JavaSecurityPermission;
@class JavaSecurityPermissionCollection;

#import "JreEmulation.h"

@interface JavaSecurityProtectionDomain : NSObject {
}

- (instancetype)initWithJavaSecurityCodeSource:(JavaSecurityCodeSource *)cs
          withJavaSecurityPermissionCollection:(JavaSecurityPermissionCollection *)permissions;

- (instancetype)initWithJavaSecurityCodeSource:(JavaSecurityCodeSource *)cs
          withJavaSecurityPermissionCollection:(JavaSecurityPermissionCollection *)permissions
                       withJavaLangClassLoader:(JavaLangClassLoader *)cl
                withJavaSecurityPrincipalArray:(IOSObjectArray *)principals;

- (JavaLangClassLoader *)getClassLoader;

- (JavaSecurityCodeSource *)getCodeSource;

- (JavaSecurityPermissionCollection *)getPermissions;

- (IOSObjectArray *)getPrincipals;

- (jboolean)impliesWithJavaSecurityPermission:(JavaSecurityPermission *)permission;

@end

__attribute__((always_inline)) inline void JavaSecurityProtectionDomain_init() {}

#endif // _JavaSecurityProtectionDomain_H_
