//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/hamcrest/core/Is.java
//

#ifndef _OrgHamcrestCoreIs_H_
#define _OrgHamcrestCoreIs_H_

@class IOSClass;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"
#include "org/hamcrest/BaseMatcher.h"

@interface OrgHamcrestCoreIs : OrgHamcrestBaseMatcher {
 @public
  id<OrgHamcrestMatcher> matcher_;
}

- (instancetype)initWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;

- (jboolean)matchesWithId:(id)arg;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

+ (id<OrgHamcrestMatcher>)isWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;

+ (id<OrgHamcrestMatcher>)isWithId:(id)value;

+ (id<OrgHamcrestMatcher>)isWithIOSClass:(IOSClass *)type;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgHamcrestCoreIs *)other;

@end

__attribute__((always_inline)) inline void OrgHamcrestCoreIs_init() {}

J2OBJC_FIELD_SETTER(OrgHamcrestCoreIs, matcher_, id<OrgHamcrestMatcher>)
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreIs_isWithOrgHamcrestMatcher_(id<OrgHamcrestMatcher> matcher);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreIs_isWithId_(id value);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreIs_isWithIOSClass_(IOSClass *type);

#endif // _OrgHamcrestCoreIs_H_
