//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/util/MutableLong.java
//

#ifndef _LibcoreUtilMutableLong_H_
#define _LibcoreUtilMutableLong_H_

#import "JreEmulation.h"

@interface LibcoreUtilMutableLong : NSObject {
 @public
  jlong value_;
}

- (instancetype)initWithLong:(jlong)value;

@end

__attribute__((always_inline)) inline void LibcoreUtilMutableLong_init() {}

#endif // _LibcoreUtilMutableLong_H_
