//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/util/Objects.java
//

#ifndef _LibcoreUtilObjects_H_
#define _LibcoreUtilObjects_H_

#import "JreEmulation.h"

@interface LibcoreUtilObjects : NSObject {
}

+ (jboolean)equalWithId:(id)a
                 withId:(id)b;

+ (jint)hashCodeWithId:(id)o;

+ (NSString *)toStringWithId:(id)o;

@end

__attribute__((always_inline)) inline void LibcoreUtilObjects_init() {}
FOUNDATION_EXPORT jboolean LibcoreUtilObjects_equalWithId_withId_(id a, id b);
FOUNDATION_EXPORT jint LibcoreUtilObjects_hashCodeWithId_(id o);
FOUNDATION_EXPORT NSString *LibcoreUtilObjects_toStringWithId_(id o);

#endif // _LibcoreUtilObjects_H_
