//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/ArgumentMatcher.java
//

#ifndef _OrgMockitoArgumentMatcher_H_
#define _OrgMockitoArgumentMatcher_H_

@protocol OrgHamcrestDescription;

#import "JreEmulation.h"
#include "org/hamcrest/BaseMatcher.h"

#define OrgMockitoArgumentMatcher_serialVersionUID -2145234737829370369LL

@interface OrgMockitoArgumentMatcher : OrgHamcrestBaseMatcher {
}

- (jboolean)matchesWithId:(id)argument;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoArgumentMatcher_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoArgumentMatcher, serialVersionUID, jlong)

#endif // _OrgMockitoArgumentMatcher_H_
