//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/jsr305/build_result/java/javax/annotation/CheckForNull.java
//

#ifndef _JavaxAnnotationCheckForNull_H_
#define _JavaxAnnotationCheckForNull_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationCheckForNull < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationCheckForNull : NSObject < JavaxAnnotationCheckForNull >

@end

__attribute__((always_inline)) inline void JavaxAnnotationCheckForNull_init() {}

#endif // _JavaxAnnotationCheckForNull_H_
