//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/jsr305/build_result/java/javax/annotation/WillNotClose.java
//

#ifndef _JavaxAnnotationWillNotClose_H_
#define _JavaxAnnotationWillNotClose_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationWillNotClose < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationWillNotClose : NSObject < JavaxAnnotationWillNotClose >

@end

__attribute__((always_inline)) inline void JavaxAnnotationWillNotClose_init() {}

#endif // _JavaxAnnotationWillNotClose_H_
