//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/Checks.java
//

#ifndef _OrgMockitoInternalUtilChecks_H_
#define _OrgMockitoInternalUtilChecks_H_

@protocol JavaLangIterable;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilChecks : NSObject {
}

+ (id)checkNotNullWithId:(id)value
            withNSString:(NSString *)checkedValue;

+ (id)checkItemsNotNullWithJavaLangIterable:(id<JavaLangIterable>)iterable
                               withNSString:(NSString *)checkedIterable;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilChecks_init() {}
FOUNDATION_EXPORT id OrgMockitoInternalUtilChecks_checkNotNullWithId_withNSString_(id value, NSString *checkedValue);
FOUNDATION_EXPORT id OrgMockitoInternalUtilChecks_checkItemsNotNullWithJavaLangIterable_withNSString_(id<JavaLangIterable> iterable, NSString *checkedIterable);

#endif // _OrgMockitoInternalUtilChecks_H_
