//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/BrokenBarrierException.java
//

#ifndef _JavaUtilConcurrentBrokenBarrierException_H_
#define _JavaUtilConcurrentBrokenBarrierException_H_

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaUtilConcurrentBrokenBarrierException_serialVersionUID 7117394618823254244LL

@interface JavaUtilConcurrentBrokenBarrierException : JavaLangException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentBrokenBarrierException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentBrokenBarrierException, serialVersionUID, jlong)

#endif // _JavaUtilConcurrentBrokenBarrierException_H_
