//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/Delayed.java
//

#ifndef _JavaUtilConcurrentDelayed_H_
#define _JavaUtilConcurrentDelayed_H_

@class JavaUtilConcurrentTimeUnitEnum;

#import "JreEmulation.h"
#include "java/lang/Comparable.h"

@protocol JavaUtilConcurrentDelayed < JavaLangComparable, NSObject, JavaObject >
- (jlong)getDelayWithJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentDelayed_init() {}

#endif // _JavaUtilConcurrentDelayed_H_
