//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/ExecutionException.java
//

#ifndef _JavaUtilConcurrentExecutionException_H_
#define _JavaUtilConcurrentExecutionException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaUtilConcurrentExecutionException_serialVersionUID 7830266012832686185LL

@interface JavaUtilConcurrentExecutionException : JavaLangException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentExecutionException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentExecutionException, serialVersionUID, jlong)

#endif // _JavaUtilConcurrentExecutionException_H_
