//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/ExecutorCompletionService.java
//

#ifndef _JavaUtilConcurrentExecutorCompletionService_H_
#define _JavaUtilConcurrentExecutorCompletionService_H_

@class JavaUtilConcurrentAbstractExecutorService;
@class JavaUtilConcurrentTimeUnitEnum;
@protocol JavaLangRunnable;
@protocol JavaUtilConcurrentBlockingQueue;
@protocol JavaUtilConcurrentCallable;
@protocol JavaUtilConcurrentExecutor;
@protocol JavaUtilConcurrentFuture;
@protocol JavaUtilConcurrentRunnableFuture;

#import "JreEmulation.h"
#include "java/util/concurrent/CompletionService.h"
#include "java/util/concurrent/FutureTask.h"

@interface JavaUtilConcurrentExecutorCompletionService : NSObject < JavaUtilConcurrentCompletionService > {
}

- (instancetype)initWithJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor;

- (instancetype)initWithJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor
               withJavaUtilConcurrentBlockingQueue:(id<JavaUtilConcurrentBlockingQueue>)completionQueue;

- (id<JavaUtilConcurrentFuture>)submitWithJavaUtilConcurrentCallable:(id<JavaUtilConcurrentCallable>)task;

- (id<JavaUtilConcurrentFuture>)submitWithJavaLangRunnable:(id<JavaLangRunnable>)task
                                                    withId:(id)result;

- (id<JavaUtilConcurrentFuture>)take;

- (id<JavaUtilConcurrentFuture>)poll;

- (id<JavaUtilConcurrentFuture>)pollWithLong:(jlong)timeout
          withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentExecutorCompletionService_init() {}

@interface JavaUtilConcurrentExecutorCompletionService_QueueingFuture : JavaUtilConcurrentFutureTask {
}

- (instancetype)initWithJavaUtilConcurrentExecutorCompletionService:(JavaUtilConcurrentExecutorCompletionService *)outer$
                               withJavaUtilConcurrentRunnableFuture:(id<JavaUtilConcurrentRunnableFuture>)task;

- (void)done;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentExecutorCompletionService_QueueingFuture_init() {}

#endif // _JavaUtilConcurrentExecutorCompletionService_H_
