//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/RecursiveTask.java
//

#ifndef _JavaUtilConcurrentRecursiveTask_H_
#define _JavaUtilConcurrentRecursiveTask_H_

#import "JreEmulation.h"
#include "java/util/concurrent/ForkJoinTask.h"

#define JavaUtilConcurrentRecursiveTask_serialVersionUID 5232453952276485270LL

@interface JavaUtilConcurrentRecursiveTask : JavaUtilConcurrentForkJoinTask {
 @public
  id result_;
}

- (id)compute;

- (id)getRawResult;

- (void)setRawResultWithId:(id)value;

- (jboolean)exec;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentRecursiveTask_init() {}

J2OBJC_FIELD_SETTER(JavaUtilConcurrentRecursiveTask, result_, id)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentRecursiveTask, serialVersionUID, jlong)

#endif // _JavaUtilConcurrentRecursiveTask_H_
