//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/RunnableFuture.java
//

#ifndef _JavaUtilConcurrentRunnableFuture_H_
#define _JavaUtilConcurrentRunnableFuture_H_

#import "JreEmulation.h"
#include "java/lang/Runnable.h"
#include "java/util/concurrent/Future.h"

@protocol JavaUtilConcurrentRunnableFuture < JavaLangRunnable, JavaUtilConcurrentFuture, NSObject, JavaObject >
- (void)run;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentRunnableFuture_init() {}

#endif // _JavaUtilConcurrentRunnableFuture_H_
