//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/ThreadLocalRandom.java
//

#ifndef _JavaUtilConcurrentThreadLocalRandom_H_
#define _JavaUtilConcurrentThreadLocalRandom_H_

#import "JreEmulation.h"
#include "java/lang/ThreadLocal.h"
#include "java/util/Random.h"

#define JavaUtilConcurrentThreadLocalRandom_addend 11LL
#define JavaUtilConcurrentThreadLocalRandom_mask 281474976710655LL
#define JavaUtilConcurrentThreadLocalRandom_multiplier 25214903917LL
#define JavaUtilConcurrentThreadLocalRandom_serialVersionUID -5851777807851030925LL

@interface JavaUtilConcurrentThreadLocalRandom : JavaUtilRandom {
 @public
  jboolean initialized_;
}

- (instancetype)init;

+ (JavaUtilConcurrentThreadLocalRandom *)current;

- (void)setSeedWithLong:(jlong)seed;

- (jint)nextWithInt:(jint)bits;

- (jint)nextIntWithInt:(jint)least
               withInt:(jint)bound;

- (jlong)nextLongWithLong:(jlong)n;

- (jlong)nextLongWithLong:(jlong)least
                 withLong:(jlong)bound;

- (jdouble)nextDoubleWithDouble:(jdouble)n;

- (jdouble)nextDoubleWithDouble:(jdouble)least
                     withDouble:(jdouble)bound;

@end

FOUNDATION_EXPORT BOOL JavaUtilConcurrentThreadLocalRandom_initialized;
J2OBJC_STATIC_INIT(JavaUtilConcurrentThreadLocalRandom)
FOUNDATION_EXPORT JavaUtilConcurrentThreadLocalRandom *JavaUtilConcurrentThreadLocalRandom_current();

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentThreadLocalRandom, multiplier, jlong)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentThreadLocalRandom, addend, jlong)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentThreadLocalRandom, mask, jlong)

FOUNDATION_EXPORT JavaLangThreadLocal *JavaUtilConcurrentThreadLocalRandom_localRandom_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentThreadLocalRandom, localRandom_, JavaLangThreadLocal *)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentThreadLocalRandom, serialVersionUID, jlong)

@interface JavaUtilConcurrentThreadLocalRandom_$1 : JavaLangThreadLocal {
}

- (JavaUtilConcurrentThreadLocalRandom *)initialValue OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaUtilConcurrentThreadLocalRandom_$1_init() {}

#endif // _JavaUtilConcurrentThreadLocalRandom_H_
