//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/verification/MockAwareVerificationMode.java
//

#ifndef _OrgMockitoInternalVerificationMockAwareVerificationMode_H_
#define _OrgMockitoInternalVerificationMockAwareVerificationMode_H_

@protocol OrgMockitoInternalVerificationApiVerificationData;

#import "JreEmulation.h"
#include "org/mockito/verification/VerificationMode.h"

@interface OrgMockitoInternalVerificationMockAwareVerificationMode : NSObject < OrgMockitoVerificationVerificationMode > {
 @public
  id mock_;
  id<OrgMockitoVerificationVerificationMode> mode_;
}

- (instancetype)initWithId:(id)mock
withOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)mode;

- (void)verifyWithOrgMockitoInternalVerificationApiVerificationData:(id<OrgMockitoInternalVerificationApiVerificationData>)data;

- (id)getMock;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalVerificationMockAwareVerificationMode *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalVerificationMockAwareVerificationMode_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalVerificationMockAwareVerificationMode, mock_, id)
J2OBJC_FIELD_SETTER(OrgMockitoInternalVerificationMockAwareVerificationMode, mode_, id<OrgMockitoVerificationVerificationMode>)

#endif // _OrgMockitoInternalVerificationMockAwareVerificationMode_H_
