//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/net/http/HttpDate.java
//

#ifndef _LibcoreNetHttpHttpDate_H_
#define _LibcoreNetHttpHttpDate_H_

@class IOSObjectArray;
@class JavaTextDateFormat;
@class JavaUtilDate;

#import "JreEmulation.h"
#include "java/lang/ThreadLocal.h"

@interface LibcoreNetHttpHttpDate : NSObject {
}

+ (JavaUtilDate *)parseWithNSString:(NSString *)value;

+ (NSString *)formatWithJavaUtilDate:(JavaUtilDate *)value;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL LibcoreNetHttpHttpDate_initialized;
J2OBJC_STATIC_INIT(LibcoreNetHttpHttpDate)
FOUNDATION_EXPORT JavaUtilDate *LibcoreNetHttpHttpDate_parseWithNSString_(NSString *value);
FOUNDATION_EXPORT NSString *LibcoreNetHttpHttpDate_formatWithJavaUtilDate_(JavaUtilDate *value);

FOUNDATION_EXPORT JavaLangThreadLocal *LibcoreNetHttpHttpDate_STANDARD_DATE_FORMAT_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreNetHttpHttpDate, STANDARD_DATE_FORMAT_, JavaLangThreadLocal *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreNetHttpHttpDate_BROWSER_COMPATIBLE_DATE_FORMATS_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreNetHttpHttpDate, BROWSER_COMPATIBLE_DATE_FORMATS_, IOSObjectArray *)

@interface LibcoreNetHttpHttpDate_$1 : JavaLangThreadLocal {
}

- (JavaTextDateFormat *)initialValue OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void LibcoreNetHttpHttpDate_$1_init() {}

#endif // _LibcoreNetHttpHttpDate_H_
