//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/CharConversionException.java
//

#ifndef _JavaIoCharConversionException_H_
#define _JavaIoCharConversionException_H_

#import "JreEmulation.h"
#include "java/io/IOException.h"

#define JavaIoCharConversionException_serialVersionUID -8680016352018427031LL

@interface JavaIoCharConversionException : JavaIoIOException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

__attribute__((always_inline)) inline void JavaIoCharConversionException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaIoCharConversionException, serialVersionUID, jlong)

#endif // _JavaIoCharConversionException_H_
