//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/DataOutputStream.java
//

#ifndef _JavaIoDataOutputStream_H_
#define _JavaIoDataOutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;

#import "JreEmulation.h"
#include "java/io/DataOutput.h"
#include "java/io/FilterOutputStream.h"

@interface JavaIoDataOutputStream : JavaIoFilterOutputStream < JavaIoDataOutput > {
 @public
  jint written_;
}

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;

- (void)flush;

- (jint)size;

- (void)writeWithByteArray:(IOSByteArray *)buffer
                   withInt:(jint)offset
                   withInt:(jint)count;

- (void)writeWithInt:(jint)oneByte;

- (void)writeBooleanWithBoolean:(jboolean)val;

- (void)writeByteWithInt:(jint)val;

- (void)writeBytesWithNSString:(NSString *)str;

- (void)writeCharWithInt:(jint)val;

- (void)writeCharsWithNSString:(NSString *)str;

- (void)writeDoubleWithDouble:(jdouble)val;

- (void)writeFloatWithFloat:(jfloat)val;

- (void)writeIntWithInt:(jint)val;

- (void)writeLongWithLong:(jlong)val;

- (void)writeShortWithInt:(jint)val;

- (void)writeUTFWithNSString:(NSString *)str;

@end

__attribute__((always_inline)) inline void JavaIoDataOutputStream_init() {}

#endif // _JavaIoDataOutputStream_H_
