//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/FileInputStream.java
//

#ifndef _JavaIoFileInputStream_H_
#define _JavaIoFileInputStream_H_

@class DalvikSystemCloseGuard;
@class IOSByteArray;
@class JavaIoFile;
@class JavaIoFileDescriptor;
@class JavaNioChannelsFileChannel;

#import "JreEmulation.h"
#include "java/io/InputStream.h"

@interface JavaIoFileInputStream : JavaIoInputStream {
}

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file;

- (instancetype)initWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;

- (instancetype)initWithNSString:(NSString *)path;

- (jint)available;

- (void)close;

- (void)dealloc;

- (JavaNioChannelsFileChannel *)getChannel;

- (JavaIoFileDescriptor *)getFD;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)byteOffset
                  withInt:(jint)byteCount;

- (jlong)skipWithLong:(jlong)byteCount;

@end

__attribute__((always_inline)) inline void JavaIoFileInputStream_init() {}

#endif // _JavaIoFileInputStream_H_
