//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/FileWriter.java
//

#ifndef _JavaIoFileWriter_H_
#define _JavaIoFileWriter_H_

@class JavaIoFile;
@class JavaIoFileDescriptor;

#import "JreEmulation.h"
#include "java/io/OutputStreamWriter.h"

@interface JavaIoFileWriter : JavaIoOutputStreamWriter {
}

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file
                       withBoolean:(jboolean)append;

- (instancetype)initWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;

- (instancetype)initWithNSString:(NSString *)filename;

- (instancetype)initWithNSString:(NSString *)filename
                     withBoolean:(jboolean)append;

@end

__attribute__((always_inline)) inline void JavaIoFileWriter_init() {}

#endif // _JavaIoFileWriter_H_
