//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/OutputStreamWriter.java
//

#ifndef _JavaIoOutputStreamWriter_H_
#define _JavaIoOutputStreamWriter_H_

@class IOSCharArray;
@class JavaIoOutputStream;
@class JavaNioByteBuffer;
@class JavaNioCharBuffer;
@class JavaNioCharsetCharset;
@class JavaNioCharsetCharsetEncoder;

#import "JreEmulation.h"
#include "java/io/Writer.h"

@interface JavaIoOutputStreamWriter : JavaIoWriter {
}

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                              withNSString:(NSString *)charsetName;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                 withJavaNioCharsetCharset:(JavaNioCharsetCharset *)cs;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
          withJavaNioCharsetCharsetEncoder:(JavaNioCharsetCharsetEncoder *)charsetEncoder;

- (void)close;

- (void)flush;

- (NSString *)getEncoding;

- (void)writeWithCharArray:(IOSCharArray *)buffer
                   withInt:(jint)offset
                   withInt:(jint)count;

- (void)writeWithInt:(jint)oneChar;

- (void)writeWithNSString:(NSString *)str
                  withInt:(jint)offset
                  withInt:(jint)count;

- (jboolean)checkError;

@end

__attribute__((always_inline)) inline void JavaIoOutputStreamWriter_init() {}

#endif // _JavaIoOutputStreamWriter_H_
