//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/PipedWriter.java
//

#ifndef _JavaIoPipedWriter_H_
#define _JavaIoPipedWriter_H_

@class IOSCharArray;
@class JavaIoPipedReader;

#import "JreEmulation.h"
#include "java/io/Writer.h"

@interface JavaIoPipedWriter : JavaIoWriter {
}

- (instancetype)init;

- (instancetype)initWithJavaIoPipedReader:(JavaIoPipedReader *)destination;

- (void)close;

- (void)connectWithJavaIoPipedReader:(JavaIoPipedReader *)reader;

- (void)flush;

- (void)writeWithCharArray:(IOSCharArray *)buffer
                   withInt:(jint)offset
                   withInt:(jint)count;

- (void)writeWithInt:(jint)c;

@end

__attribute__((always_inline)) inline void JavaIoPipedWriter_init() {}

#endif // _JavaIoPipedWriter_H_
