//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/WriteAbortedException.java
//

#ifndef _JavaIoWriteAbortedException_H_
#define _JavaIoWriteAbortedException_H_

@class JavaLangException;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/io/ObjectStreamException.h"

#define JavaIoWriteAbortedException_serialVersionUID -3326426625597282442LL

@interface JavaIoWriteAbortedException : JavaIoObjectStreamException {
 @public
  JavaLangException *detail_;
}

- (instancetype)initWithNSString:(NSString *)detailMessage
           withJavaLangException:(JavaLangException *)rootCause;

- (NSString *)getMessage;

- (JavaLangThrowable *)getCause;

@end

__attribute__((always_inline)) inline void JavaIoWriteAbortedException_init() {}

J2OBJC_FIELD_SETTER(JavaIoWriteAbortedException, detail_, JavaLangException *)

J2OBJC_STATIC_FIELD_GETTER(JavaIoWriteAbortedException, serialVersionUID, jlong)

#endif // _JavaIoWriteAbortedException_H_
