//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/reflection/FieldReader.java
//

#ifndef _OrgMockitoInternalUtilReflectionFieldReader_H_
#define _OrgMockitoInternalUtilReflectionFieldReader_H_

@class JavaLangReflectField;
@class OrgMockitoInternalUtilReflectionAccessibilityChanger;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilReflectionFieldReader : NSObject {
 @public
  id target_;
  JavaLangReflectField *field_;
  OrgMockitoInternalUtilReflectionAccessibilityChanger *changer_;
}

- (instancetype)initWithId:(id)target
  withJavaLangReflectField:(JavaLangReflectField *)field;

- (jboolean)isNull;

- (id)read;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalUtilReflectionFieldReader *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilReflectionFieldReader_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalUtilReflectionFieldReader, target_, id)
J2OBJC_FIELD_SETTER(OrgMockitoInternalUtilReflectionFieldReader, field_, JavaLangReflectField *)
J2OBJC_FIELD_SETTER(OrgMockitoInternalUtilReflectionFieldReader, changer_, OrgMockitoInternalUtilReflectionAccessibilityChanger *)

#endif // _OrgMockitoInternalUtilReflectionFieldReader_H_
