//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/hamcrest/BaseDescription.java
//

#ifndef _OrgHamcrestBaseDescription_H_
#define _OrgHamcrestBaseDescription_H_

@class IOSObjectArray;
@protocol JavaLangIterable;
@protocol JavaUtilIterator;
@protocol OrgHamcrestSelfDescribing;

#import "JreEmulation.h"
#include "org/hamcrest/Description.h"

@interface OrgHamcrestBaseDescription : NSObject < OrgHamcrestDescription > {
}

- (id<OrgHamcrestDescription>)appendTextWithNSString:(NSString *)text;

- (id<OrgHamcrestDescription>)appendDescriptionOfWithOrgHamcrestSelfDescribing:(id<OrgHamcrestSelfDescribing>)value;

- (id<OrgHamcrestDescription>)appendValueWithId:(id)value;

- (id<OrgHamcrestDescription>)appendValueListWithNSString:(NSString *)start
                                             withNSString:(NSString *)separator
                                             withNSString:(NSString *)end
                                        withNSObjectArray:(IOSObjectArray *)values;

- (id<OrgHamcrestDescription>)appendValueListWithNSString:(NSString *)start
                                             withNSString:(NSString *)separator
                                             withNSString:(NSString *)end
                                     withJavaLangIterable:(id<JavaLangIterable>)values;

- (id<OrgHamcrestDescription>)appendValueListWithNSString:(NSString *)start
                                             withNSString:(NSString *)separator
                                             withNSString:(NSString *)end
                                     withJavaUtilIterator:(id<JavaUtilIterator>)values;

- (id<OrgHamcrestDescription>)appendListWithNSString:(NSString *)start
                                        withNSString:(NSString *)separator
                                        withNSString:(NSString *)end
                                withJavaLangIterable:(id<JavaLangIterable>)values;

- (id<OrgHamcrestDescription>)appendListWithNSString:(NSString *)start
                                        withNSString:(NSString *)separator
                                        withNSString:(NSString *)end
                                withJavaUtilIterator:(id<JavaUtilIterator>)i;

- (void)appendWithNSString:(NSString *)str;

- (void)appendWithChar:(jchar)c;

- (void)toJavaSyntaxWithNSString:(NSString *)unformatted;

- (void)toJavaSyntaxWithChar:(jchar)ch;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgHamcrestBaseDescription_init() {}

#endif // _OrgHamcrestBaseDescription_H_
