//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/hamcrest/CoreMatchers.java
//

#ifndef _OrgHamcrestCoreMatchers_H_
#define _OrgHamcrestCoreMatchers_H_

@class IOSClass;
@class IOSObjectArray;
@protocol JavaLangIterable;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"

@interface OrgHamcrestCoreMatchers : NSObject {
}

+ (id<OrgHamcrestMatcher>)isWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;

+ (id<OrgHamcrestMatcher>)isWithId:(id)value;

+ (id<OrgHamcrestMatcher>)isWithIOSClass:(IOSClass *)type;

+ (id<OrgHamcrestMatcher>)not__WithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;

+ (id<OrgHamcrestMatcher>)not__WithId:(id)value;

+ (id<OrgHamcrestMatcher>)equalToWithId:(id)operand;

+ (id<OrgHamcrestMatcher>)instanceOfWithIOSClass:(IOSClass *)type;

+ (id<OrgHamcrestMatcher>)allOfWithOrgHamcrestMatcherArray:(IOSObjectArray *)matchers;

+ (id<OrgHamcrestMatcher>)allOfWithJavaLangIterable:(id<JavaLangIterable>)matchers;

+ (id<OrgHamcrestMatcher>)anyOfWithOrgHamcrestMatcherArray:(IOSObjectArray *)matchers;

+ (id<OrgHamcrestMatcher>)anyOfWithJavaLangIterable:(id<JavaLangIterable>)matchers;

+ (id<OrgHamcrestMatcher>)sameInstanceWithId:(id)object;

+ (id<OrgHamcrestMatcher>)anything;

+ (id<OrgHamcrestMatcher>)anythingWithNSString:(NSString *)description_;

+ (id<OrgHamcrestMatcher>)anyWithIOSClass:(IOSClass *)type;

+ (id<OrgHamcrestMatcher>)nullValue;

+ (id<OrgHamcrestMatcher>)nullValueWithIOSClass:(IOSClass *)type;

+ (id<OrgHamcrestMatcher>)notNullValue;

+ (id<OrgHamcrestMatcher>)notNullValueWithIOSClass:(IOSClass *)type;

+ (id<OrgHamcrestMatcher>)describedAsWithNSString:(NSString *)description_
                           withOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher
                                withNSObjectArray:(IOSObjectArray *)values;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgHamcrestCoreMatchers_init() {}
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_isWithOrgHamcrestMatcher_(id<OrgHamcrestMatcher> matcher);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_isWithId_(id value);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_isWithIOSClass_(IOSClass *type);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_not__WithOrgHamcrestMatcher_(id<OrgHamcrestMatcher> matcher);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_not__WithId_(id value);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_equalToWithId_(id operand);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_instanceOfWithIOSClass_(IOSClass *type);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_allOfWithOrgHamcrestMatcherArray_(IOSObjectArray *matchers);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_allOfWithJavaLangIterable_(id<JavaLangIterable> matchers);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_anyOfWithOrgHamcrestMatcherArray_(IOSObjectArray *matchers);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_anyOfWithJavaLangIterable_(id<JavaLangIterable> matchers);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_sameInstanceWithId_(id object);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_anything();
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_anythingWithNSString_(NSString *description_);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_anyWithIOSClass_(IOSClass *type);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_nullValue();
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_nullValueWithIOSClass_(IOSClass *type);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_notNullValue();
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_notNullValueWithIOSClass_(IOSClass *type);
FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreMatchers_describedAsWithNSString_withOrgHamcrestMatcher_withNSObjectArray_(NSString *description_, id<OrgHamcrestMatcher> matcher, IOSObjectArray *values);

#endif // _OrgHamcrestCoreMatchers_H_
