//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/hamcrest/Matcher.java
//

#ifndef _OrgHamcrestMatcher_H_
#define _OrgHamcrestMatcher_H_

#import "JreEmulation.h"
#include "org/hamcrest/SelfDescribing.h"

@protocol OrgHamcrestMatcher < OrgHamcrestSelfDescribing, NSObject, JavaObject >
- (jboolean)matchesWithId:(id)item;

- (void)_dont_implement_Matcher___instead_extend_BaseMatcher_;

@end

__attribute__((always_inline)) inline void OrgHamcrestMatcher_init() {}

#endif // _OrgHamcrestMatcher_H_
