//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/verification/api/InOrderContext.java
//

#ifndef _OrgMockitoInternalVerificationApiInOrderContext_H_
#define _OrgMockitoInternalVerificationApiInOrderContext_H_

@protocol OrgMockitoInvocationInvocation;

#import "JreEmulation.h"

@protocol OrgMockitoInternalVerificationApiInOrderContext < NSObject, JavaObject >

- (jboolean)isVerifiedWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)invocation;

- (void)markVerifiedWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)i;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalVerificationApiInOrderContext_init() {}

#endif // _OrgMockitoInternalVerificationApiInOrderContext_H_
