//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/verification/api/VerificationData.java
//

#ifndef _OrgMockitoInternalVerificationApiVerificationData_H_
#define _OrgMockitoInternalVerificationApiVerificationData_H_

@class OrgMockitoInternalInvocationInvocationMatcher;
@protocol JavaUtilList;

#import "JreEmulation.h"

@protocol OrgMockitoInternalVerificationApiVerificationData < NSObject, JavaObject >

- (id<JavaUtilList>)getAllInvocations;

- (OrgMockitoInternalInvocationInvocationMatcher *)getWanted;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalVerificationApiVerificationData_init() {}

#endif // _OrgMockitoInternalVerificationApiVerificationData_H_
