//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/ArithmeticException.java
//

#ifndef _JavaLangArithmeticException_H_
#define _JavaLangArithmeticException_H_

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define JavaLangArithmeticException_serialVersionUID 2256477558314496007LL

@interface JavaLangArithmeticException : JavaLangRuntimeException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

__attribute__((always_inline)) inline void JavaLangArithmeticException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangArithmeticException, serialVersionUID, jlong)

#endif // _JavaLangArithmeticException_H_
