//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/ClassCastException.java
//

#ifndef _JavaLangClassCastException_H_
#define _JavaLangClassCastException_H_

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define JavaLangClassCastException_serialVersionUID -9223365651070458532LL

@interface JavaLangClassCastException : JavaLangRuntimeException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

__attribute__((always_inline)) inline void JavaLangClassCastException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangClassCastException, serialVersionUID, jlong)

#endif // _JavaLangClassCastException_H_
