//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/ExceptionInInitializerError.java
//

#ifndef _JavaLangExceptionInInitializerError_H_
#define _JavaLangExceptionInInitializerError_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/LinkageError.h"

#define JavaLangExceptionInInitializerError_serialVersionUID 1521711792217232256LL

@interface JavaLangExceptionInInitializerError : JavaLangLinkageError {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)exception;

- (JavaLangThrowable *)getException;

- (JavaLangThrowable *)getCause;

@end

__attribute__((always_inline)) inline void JavaLangExceptionInInitializerError_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangExceptionInInitializerError, serialVersionUID, jlong)

#endif // _JavaLangExceptionInInitializerError_H_
