//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/NoSuchFieldError.java
//

#ifndef _JavaLangNoSuchFieldError_H_
#define _JavaLangNoSuchFieldError_H_

#import "JreEmulation.h"
#include "java/lang/IncompatibleClassChangeError.h"

#define JavaLangNoSuchFieldError_serialVersionUID -3456430195886129035LL

@interface JavaLangNoSuchFieldError : JavaLangIncompatibleClassChangeError {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

__attribute__((always_inline)) inline void JavaLangNoSuchFieldError_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangNoSuchFieldError, serialVersionUID, jlong)

#endif // _JavaLangNoSuchFieldError_H_
