//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/NumberFormatException.java
//

#ifndef _JavaLangNumberFormatException_H_
#define _JavaLangNumberFormatException_H_

#import "JreEmulation.h"
#include "java/lang/IllegalArgumentException.h"

#define JavaLangNumberFormatException_serialVersionUID -2848938806368998894LL

@interface JavaLangNumberFormatException : JavaLangIllegalArgumentException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

__attribute__((always_inline)) inline void JavaLangNumberFormatException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangNumberFormatException, serialVersionUID, jlong)

#endif // _JavaLangNumberFormatException_H_
