//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/Override.java
//

#ifndef _JavaLangOverride_H_
#define _JavaLangOverride_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaLangOverride < JavaLangAnnotationAnnotation >

@end

#endif // _JavaLangOverride_H_
