//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/java/lang/StackTraceElement.java
//

#ifndef _JavaLangStackTraceElement_H_
#define _JavaLangStackTraceElement_H_

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define JavaLangStackTraceElement_serialVersionUID 6992337162326171013LL

@interface JavaLangStackTraceElement : NSObject < JavaIoSerializable > {
}

- (NSString *)getClassName;

- (NSString *)getMethodName;

- (NSString *)getFileName;

- (jint)getLineNumber;

- (instancetype)initWithNSString:(NSString *)className_
                    withNSString:(NSString *)methodName
                    withNSString:(NSString *)fileName
                         withInt:(jint)lineNumber;

- (instancetype)initWithLong:(jlong)address;

- (NSString *)description;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

__attribute__((always_inline)) inline void JavaLangStackTraceElement_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangStackTraceElement, serialVersionUID, jlong)

#endif // _JavaLangStackTraceElement_H_
