//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni-kernel/src/main/java/java/lang/ThreadGroup.java
//

#ifndef _JavaLangThreadGroup_H_
#define _JavaLangThreadGroup_H_

@class IOSObjectArray;
@class JavaLangThread;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/Thread.h"

@interface JavaLangThreadGroup : NSObject < JavaLangThread_UncaughtExceptionHandler > {
 @public
  JavaLangThreadGroup *parent_;
  jint numThreads_;
  jint numGroups_;
}

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)parent
                               withNSString:(NSString *)name;

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)parent;

- (jint)activeCount;

- (jint)activeGroupCount;

- (void)addWithJavaLangThread:(JavaLangThread *)thread;

- (void)checkAccess;

- (void)destroy;

- (jint)enumerateWithJavaLangThreadArray:(IOSObjectArray *)threads;

- (jint)enumerateWithJavaLangThreadArray:(IOSObjectArray *)threads
                             withBoolean:(jboolean)recurse;

- (jint)enumerateWithJavaLangThreadGroupArray:(IOSObjectArray *)groups;

- (jint)enumerateWithJavaLangThreadGroupArray:(IOSObjectArray *)groups
                                  withBoolean:(jboolean)recurse;

- (jint)getMaxPriority;

- (NSString *)getName;

- (JavaLangThreadGroup *)getParent;

- (jboolean)isDestroyed;

- (void)list;

- (jboolean)parentOfWithJavaLangThreadGroup:(JavaLangThreadGroup *)g;

- (void)removeWithJavaLangThread:(JavaLangThread *)thread;

- (void)setMaxPriorityWithInt:(jint)newMax;

- (NSString *)description;

- (void)uncaughtExceptionWithJavaLangThread:(JavaLangThread *)t
                      withJavaLangThrowable:(JavaLangThrowable *)e;

@end

__attribute__((always_inline)) inline void JavaLangThreadGroup_init() {}

J2OBJC_FIELD_SETTER(JavaLangThreadGroup, parent_, JavaLangThreadGroup *)

@interface JavaLangThreadGroup_ChildrenGroupsLock : NSObject {
}

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)outer$;

@end

__attribute__((always_inline)) inline void JavaLangThreadGroup_ChildrenGroupsLock_init() {}

@interface JavaLangThreadGroup_ChildrenThreadsLock : NSObject {
}

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)outer$;

@end

__attribute__((always_inline)) inline void JavaLangThreadGroup_ChildrenThreadsLock_init() {}

#endif // _JavaLangThreadGroup_H_
