//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/TypeNotPresentException.java
//

#ifndef _JavaLangTypeNotPresentException_H_
#define _JavaLangTypeNotPresentException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define JavaLangTypeNotPresentException_serialVersionUID -5101214195716534496LL

@interface JavaLangTypeNotPresentException : JavaLangRuntimeException {
}

- (instancetype)initWithNSString:(NSString *)typeName
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (NSString *)typeName;

@end

__attribute__((always_inline)) inline void JavaLangTypeNotPresentException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaLangTypeNotPresentException, serialVersionUID, jlong)

#endif // _JavaLangTypeNotPresentException_H_
