//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/util/concurrent/CheckedFuture.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonUtilConcurrentCheckedFuture_RESTRICT
#define ComGoogleCommonUtilConcurrentCheckedFuture_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentCheckedFuture_RESTRICT
#if !defined (_ComGoogleCommonUtilConcurrentCheckedFuture_) && (ComGoogleCommonUtilConcurrentCheckedFuture_INCLUDE_ALL || ComGoogleCommonUtilConcurrentCheckedFuture_INCLUDE)
#define _ComGoogleCommonUtilConcurrentCheckedFuture_

@class JavaUtilConcurrentTimeUnitEnum;

#define ComGoogleCommonUtilConcurrentListenableFuture_RESTRICT 1
#define ComGoogleCommonUtilConcurrentListenableFuture_INCLUDE 1
#include "com/google/common/util/concurrent/ListenableFuture.h"


@protocol ComGoogleCommonUtilConcurrentCheckedFuture < ComGoogleCommonUtilConcurrentListenableFuture, NSObject, JavaObject >
- (id)checkedGet;

- (id)checkedGetWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

@end

__attribute__((always_inline)) inline void ComGoogleCommonUtilConcurrentCheckedFuture_init() {}
#endif
