//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/util/concurrent/ForwardingBlockingQueue.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonUtilConcurrentForwardingBlockingQueue_RESTRICT
#define ComGoogleCommonUtilConcurrentForwardingBlockingQueue_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentForwardingBlockingQueue_RESTRICT
#if !defined (_ComGoogleCommonUtilConcurrentForwardingBlockingQueue_) && (ComGoogleCommonUtilConcurrentForwardingBlockingQueue_INCLUDE_ALL || ComGoogleCommonUtilConcurrentForwardingBlockingQueue_INCLUDE)
#define _ComGoogleCommonUtilConcurrentForwardingBlockingQueue_

@class JavaUtilConcurrentTimeUnitEnum;
@protocol JavaUtilCollection;

#define ComGoogleCommonCollectForwardingQueue_RESTRICT 1
#define ComGoogleCommonCollectForwardingQueue_INCLUDE 1
#include "com/google/common/collect/ForwardingQueue.h"

#define JavaUtilConcurrentBlockingQueue_RESTRICT 1
#define JavaUtilConcurrentBlockingQueue_INCLUDE 1
#include "java/util/concurrent/BlockingQueue.h"


@interface ComGoogleCommonUtilConcurrentForwardingBlockingQueue : ComGoogleCommonCollectForwardingQueue < JavaUtilConcurrentBlockingQueue > {
}

- (instancetype)init;

- (id<JavaUtilConcurrentBlockingQueue>)delegate;

- (jint)drainToWithJavaUtilCollection:(id<JavaUtilCollection>)c
                              withInt:(jint)maxElements;

- (jint)drainToWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jboolean)offerWithId:(id)e
               withLong:(jlong)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

- (id)pollWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

- (void)putWithId:(id)e;

- (jint)remainingCapacity;

- (id)take;


@end

__attribute__((always_inline)) inline void ComGoogleCommonUtilConcurrentForwardingBlockingQueue_init() {}
#endif
