//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/util/concurrent/ForwardingService.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonUtilConcurrentForwardingService_RESTRICT
#define ComGoogleCommonUtilConcurrentForwardingService_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentForwardingService_RESTRICT
#if !defined (_ComGoogleCommonUtilConcurrentForwardingService_) && (ComGoogleCommonUtilConcurrentForwardingService_INCLUDE_ALL || ComGoogleCommonUtilConcurrentForwardingService_INCLUDE)
#define _ComGoogleCommonUtilConcurrentForwardingService_

@class ComGoogleCommonUtilConcurrentService_StateEnum;
@class JavaLangThrowable;
@protocol ComGoogleCommonUtilConcurrentListenableFuture;
@protocol ComGoogleCommonUtilConcurrentService_Listener;
@protocol JavaUtilConcurrentExecutor;

#define ComGoogleCommonCollectForwardingObject_RESTRICT 1
#define ComGoogleCommonCollectForwardingObject_INCLUDE 1
#include "com/google/common/collect/ForwardingObject.h"

#define ComGoogleCommonUtilConcurrentService_RESTRICT 1
#define ComGoogleCommonUtilConcurrentService_INCLUDE 1
#include "com/google/common/util/concurrent/Service.h"


@interface ComGoogleCommonUtilConcurrentForwardingService : ComGoogleCommonCollectForwardingObject < ComGoogleCommonUtilConcurrentService > {
}

- (instancetype)init;

- (id<ComGoogleCommonUtilConcurrentService>)delegate;

- (id<ComGoogleCommonUtilConcurrentListenableFuture>)start;

- (ComGoogleCommonUtilConcurrentService_StateEnum *)state;

- (id<ComGoogleCommonUtilConcurrentListenableFuture>)stop;

- (ComGoogleCommonUtilConcurrentService_StateEnum *)startAndWait;

- (ComGoogleCommonUtilConcurrentService_StateEnum *)stopAndWait;

- (jboolean)isRunning;

- (void)addListenerWithComGoogleCommonUtilConcurrentService_Listener:(id<ComGoogleCommonUtilConcurrentService_Listener>)listener
                                      withJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor;

- (JavaLangThrowable *)failureCause;

- (ComGoogleCommonUtilConcurrentService_StateEnum *)standardStartAndWait;

- (ComGoogleCommonUtilConcurrentService_StateEnum *)standardStopAndWait;

@end

__attribute__((always_inline)) inline void ComGoogleCommonUtilConcurrentForwardingService_init() {}
#endif
