//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/util/concurrent/Runnables.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonUtilConcurrentRunnables_RESTRICT
#define ComGoogleCommonUtilConcurrentRunnables_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentRunnables_RESTRICT
#if !defined (_ComGoogleCommonUtilConcurrentRunnables_) && (ComGoogleCommonUtilConcurrentRunnables_INCLUDE_ALL || ComGoogleCommonUtilConcurrentRunnables_INCLUDE)
#define _ComGoogleCommonUtilConcurrentRunnables_

@protocol JavaLangRunnable;


@interface ComGoogleCommonUtilConcurrentRunnables : NSObject {
}

+ (id<JavaLangRunnable>)doNothing;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonUtilConcurrentRunnables_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonUtilConcurrentRunnables)
FOUNDATION_EXPORT id<JavaLangRunnable> ComGoogleCommonUtilConcurrentRunnables_doNothing();

FOUNDATION_EXPORT id<JavaLangRunnable> ComGoogleCommonUtilConcurrentRunnables_EMPTY_RUNNABLE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonUtilConcurrentRunnables, EMPTY_RUNNABLE_, id<JavaLangRunnable>)
#endif
#if !defined (_ComGoogleCommonUtilConcurrentRunnables_$1_) && (ComGoogleCommonUtilConcurrentRunnables_INCLUDE_ALL || ComGoogleCommonUtilConcurrentRunnables_$1_INCLUDE)
#define _ComGoogleCommonUtilConcurrentRunnables_$1_

#define JavaLangRunnable_RESTRICT 1
#define JavaLangRunnable_INCLUDE 1
#include "java/lang/Runnable.h"


@interface ComGoogleCommonUtilConcurrentRunnables_$1 : NSObject < JavaLangRunnable > {
}

- (void)run;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComGoogleCommonUtilConcurrentRunnables_$1_init() {}
#endif
