//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/util/concurrent/TimeLimiter.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonUtilConcurrentTimeLimiter_RESTRICT
#define ComGoogleCommonUtilConcurrentTimeLimiter_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentTimeLimiter_RESTRICT
#if !defined (_ComGoogleCommonUtilConcurrentTimeLimiter_) && (ComGoogleCommonUtilConcurrentTimeLimiter_INCLUDE_ALL || ComGoogleCommonUtilConcurrentTimeLimiter_INCLUDE)
#define _ComGoogleCommonUtilConcurrentTimeLimiter_

@class IOSClass;
@class JavaUtilConcurrentTimeUnitEnum;
@protocol JavaUtilConcurrentCallable;


@protocol ComGoogleCommonUtilConcurrentTimeLimiter < NSObject, JavaObject >

- (id)newProxyWithId:(id)target
        withIOSClass:(IOSClass *)interfaceType
            withLong:(jlong)timeoutDuration
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)timeoutUnit OBJC_METHOD_FAMILY_NONE;

- (id)callWithTimeoutWithJavaUtilConcurrentCallable:(id<JavaUtilConcurrentCallable>)callable
                                           withLong:(jlong)timeoutDuration
                 withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)timeoutUnit
                                        withBoolean:(jboolean)interruptible;

@end

__attribute__((always_inline)) inline void ComGoogleCommonUtilConcurrentTimeLimiter_init() {}
#endif
