//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/junit/Before.java
//

#ifndef _OrgJunitBefore_H_
#define _OrgJunitBefore_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitBefore < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitBefore : NSObject < OrgJunitBefore >

@end

__attribute__((always_inline)) inline void OrgJunitBefore_init() {}

#endif // _OrgJunitBefore_H_
