//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/DefaultFileNameMap.java
//

#ifndef _JavaNetDefaultFileNameMap_H_
#define _JavaNetDefaultFileNameMap_H_

#import "JreEmulation.h"
#include "java/net/FileNameMap.h"

@interface JavaNetDefaultFileNameMap : NSObject < JavaNetFileNameMap > {
}

- (NSString *)getContentTypeForWithNSString:(NSString *)filename;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaNetDefaultFileNameMap_init() {}

#endif // _JavaNetDefaultFileNameMap_H_
