//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/HttpCookie.java
//

#ifndef _JavaNetHttpCookie_H_
#define _JavaNetHttpCookie_H_

@class JavaLangStringBuilder;
@class JavaNetURI;
@class JavaUtilDate;
@protocol JavaUtilList;
@protocol JavaUtilSet;

#import "JreEmulation.h"

@interface JavaNetHttpCookie : NSObject < NSCopying > {
}

+ (jboolean)domainMatchesWithNSString:(NSString *)domainPattern
                         withNSString:(NSString *)host;

+ (jboolean)pathMatchesWithJavaNetHttpCookie:(JavaNetHttpCookie *)cookie
                              withJavaNetURI:(JavaNetURI *)uri;

+ (jboolean)secureMatchesWithJavaNetHttpCookie:(JavaNetHttpCookie *)cookie
                                withJavaNetURI:(JavaNetURI *)uri;

+ (jboolean)portMatchesWithJavaNetHttpCookie:(JavaNetHttpCookie *)cookie
                              withJavaNetURI:(JavaNetURI *)uri;

+ (id<JavaUtilList>)parseWithNSString:(NSString *)header;

- (instancetype)initWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (NSString *)getComment;

- (NSString *)getCommentURL;

- (jboolean)getDiscard;

- (NSString *)getDomain;

- (jlong)getMaxAge;

- (NSString *)getName;

- (NSString *)getPath;

- (NSString *)getPortlist;

- (jboolean)getSecure;

- (NSString *)getValue;

- (jint)getVersion;

- (jboolean)hasExpired;

- (void)setCommentWithNSString:(NSString *)comment;

- (void)setCommentURLWithNSString:(NSString *)commentURL;

- (void)setDiscardWithBoolean:(jboolean)discard;

- (void)setDomainWithNSString:(NSString *)pattern;

- (void)setMaxAgeWithLong:(jlong)deltaSeconds;

- (void)setPathWithNSString:(NSString *)path;

- (void)setPortlistWithNSString:(NSString *)portList;

- (void)setSecureWithBoolean:(jboolean)secure;

- (void)setValueWithNSString:(NSString *)value;

- (void)setVersionWithInt:(jint)newVersion;

- (id)clone;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL JavaNetHttpCookie_initialized;
J2OBJC_STATIC_INIT(JavaNetHttpCookie)
FOUNDATION_EXPORT jboolean JavaNetHttpCookie_domainMatchesWithNSString_withNSString_(NSString *domainPattern, NSString *host);
FOUNDATION_EXPORT jboolean JavaNetHttpCookie_pathMatchesWithJavaNetHttpCookie_withJavaNetURI_(JavaNetHttpCookie *cookie, JavaNetURI *uri);
FOUNDATION_EXPORT jboolean JavaNetHttpCookie_secureMatchesWithJavaNetHttpCookie_withJavaNetURI_(JavaNetHttpCookie *cookie, JavaNetURI *uri);
FOUNDATION_EXPORT jboolean JavaNetHttpCookie_portMatchesWithJavaNetHttpCookie_withJavaNetURI_(JavaNetHttpCookie *cookie, JavaNetURI *uri);
FOUNDATION_EXPORT id<JavaUtilList> JavaNetHttpCookie_parseWithNSString_(NSString *header);

FOUNDATION_EXPORT id<JavaUtilSet> JavaNetHttpCookie_RESERVED_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(JavaNetHttpCookie, RESERVED_NAMES_, id<JavaUtilSet>)

@interface JavaNetHttpCookie_CookieParser : NSObject {
 @public
  jboolean hasExpires_;
  jboolean hasMaxAge_;
  jboolean hasVersion_;
}

- (instancetype)initWithNSString:(NSString *)input;

- (id<JavaUtilList>)parse;

@end

__attribute__((always_inline)) inline void JavaNetHttpCookie_CookieParser_init() {}

FOUNDATION_EXPORT NSString *JavaNetHttpCookie_CookieParser_ATTRIBUTE_NAME_TERMINATORS_;
J2OBJC_STATIC_FIELD_GETTER(JavaNetHttpCookie_CookieParser, ATTRIBUTE_NAME_TERMINATORS_, NSString *)

FOUNDATION_EXPORT NSString *JavaNetHttpCookie_CookieParser_WHITESPACE_;
J2OBJC_STATIC_FIELD_GETTER(JavaNetHttpCookie_CookieParser, WHITESPACE_, NSString *)

#endif // _JavaNetHttpCookie_H_
