//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/InetUnixAddress.java
//

#ifndef _JavaNetInetUnixAddress_H_
#define _JavaNetInetUnixAddress_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/net/InetAddress.h"

@interface JavaNetInetUnixAddress : JavaNetInetAddress {
}

- (instancetype)initWithNSString:(NSString *)path;

- (instancetype)initWithByteArray:(IOSByteArray *)path;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaNetInetUnixAddress_init() {}

#endif // _JavaNetInetUnixAddress_H_
