//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/PlainServerSocketImpl.java
//

#ifndef _JavaNetPlainServerSocketImpl_H_
#define _JavaNetPlainServerSocketImpl_H_

@class JavaIoFileDescriptor;

#import "JreEmulation.h"
#include "java/net/PlainSocketImpl.h"

@interface JavaNetPlainServerSocketImpl : JavaNetPlainSocketImpl {
}

- (instancetype)init;

- (instancetype)initWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;

- (void)createWithBoolean:(jboolean)isStreaming;

@end

__attribute__((always_inline)) inline void JavaNetPlainServerSocketImpl_init() {}

#endif // _JavaNetPlainServerSocketImpl_H_
