//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/SocketOption.java
//

#ifndef _JavaNetSocketOption_H_
#define _JavaNetSocketOption_H_

@class IOSClass;

#import "JreEmulation.h"

@protocol JavaNetSocketOption < NSObject, JavaObject >

- (NSString *)name;

- (IOSClass *)type;

@end

__attribute__((always_inline)) inline void JavaNetSocketOption_init() {}

#endif // _JavaNetSocketOption_H_
