//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/SocketTimeoutException.java
//

#ifndef _JavaNetSocketTimeoutException_H_
#define _JavaNetSocketTimeoutException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/io/InterruptedIOException.h"

#define JavaNetSocketTimeoutException_serialVersionUID -8846654841826352300LL

@interface JavaNetSocketTimeoutException : JavaIoInterruptedIOException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithNSString:(NSString *)detailMessage
           withJavaLangThrowable:(JavaLangThrowable *)cause;

@end

__attribute__((always_inline)) inline void JavaNetSocketTimeoutException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaNetSocketTimeoutException, serialVersionUID, jlong)

#endif // _JavaNetSocketTimeoutException_H_
