//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/SocketImplFactory.java
//

#ifndef _JavaNetSocketImplFactory_H_
#define _JavaNetSocketImplFactory_H_

@class JavaNetSocketImpl;

#import "JreEmulation.h"

@protocol JavaNetSocketImplFactory < NSObject, JavaObject >

- (JavaNetSocketImpl *)createSocketImpl;

@end

__attribute__((always_inline)) inline void JavaNetSocketImplFactory_init() {}

#endif // _JavaNetSocketImplFactory_H_
