//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/URLStreamHandler.java
//

#ifndef _JavaNetURLStreamHandler_H_
#define _JavaNetURLStreamHandler_H_

@class JavaNetInetAddress;
@class JavaNetProxy;
@class JavaNetURL;
@class JavaNetURLConnection;

#import "JreEmulation.h"

@interface JavaNetURLStreamHandler : NSObject {
}

- (JavaNetURLConnection *)openConnectionWithJavaNetURL:(JavaNetURL *)u;

- (JavaNetURLConnection *)openConnectionWithJavaNetURL:(JavaNetURL *)u
                                      withJavaNetProxy:(JavaNetProxy *)proxy;

- (void)parseURLWithJavaNetURL:(JavaNetURL *)url
                  withNSString:(NSString *)spec
                       withInt:(jint)start
                       withInt:(jint)end;

- (void)setURLWithJavaNetURL:(JavaNetURL *)u
                withNSString:(NSString *)protocol
                withNSString:(NSString *)host
                     withInt:(jint)port
                withNSString:(NSString *)file
                withNSString:(NSString *)ref;

- (void)setURLWithJavaNetURL:(JavaNetURL *)u
                withNSString:(NSString *)protocol
                withNSString:(NSString *)host
                     withInt:(jint)port
                withNSString:(NSString *)authority
                withNSString:(NSString *)userInfo
                withNSString:(NSString *)path
                withNSString:(NSString *)query
                withNSString:(NSString *)ref;

- (NSString *)toExternalFormWithJavaNetURL:(JavaNetURL *)url;

- (NSString *)toExternalFormWithJavaNetURL:(JavaNetURL *)url
                               withBoolean:(jboolean)escapeIllegalCharacters;

- (jboolean)equalsWithJavaNetURL:(JavaNetURL *)a
                  withJavaNetURL:(JavaNetURL *)b;

- (jint)getDefaultPort;

- (JavaNetInetAddress *)getHostAddressWithJavaNetURL:(JavaNetURL *)url;

- (jint)hashCodeWithJavaNetURL:(JavaNetURL *)url;

- (jboolean)hostsEqualWithJavaNetURL:(JavaNetURL *)a
                      withJavaNetURL:(JavaNetURL *)b;

- (jboolean)sameFileWithJavaNetURL:(JavaNetURL *)a
                    withJavaNetURL:(JavaNetURL *)b;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaNetURLStreamHandler_init() {}

#endif // _JavaNetURLStreamHandler_H_
