//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/asn1/ASN1Sequence.java
//

#ifndef _OrgApacheHarmonySecurityAsn1ASN1Sequence_H_
#define _OrgApacheHarmonySecurityAsn1ASN1Sequence_H_

@class IOSObjectArray;
@class OrgApacheHarmonySecurityAsn1BerInputStream;
@class OrgApacheHarmonySecurityAsn1BerOutputStream;

#import "JreEmulation.h"
#include "org/apache/harmony/security/asn1/ASN1TypeCollection.h"

@interface OrgApacheHarmonySecurityAsn1ASN1Sequence : OrgApacheHarmonySecurityAsn1ASN1TypeCollection {
}

- (instancetype)initWithOrgApacheHarmonySecurityAsn1ASN1TypeArray:(IOSObjectArray *)type;

- (id)decodeWithOrgApacheHarmonySecurityAsn1BerInputStream:(OrgApacheHarmonySecurityAsn1BerInputStream *)inArg;

- (void)encodeContentWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

- (void)setEncodingContentWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonySecurityAsn1ASN1Sequence_init() {}

#endif // _OrgApacheHarmonySecurityAsn1ASN1Sequence_H_
