//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/FileLock.java
//

#ifndef _JavaNioChannelsFileLock_H_
#define _JavaNioChannelsFileLock_H_

@class JavaNioChannelsFileChannel;

#import "JreEmulation.h"
#include "java/lang/AutoCloseable.h"

@interface JavaNioChannelsFileLock : NSObject < JavaLangAutoCloseable > {
}

- (instancetype)initWithJavaNioChannelsFileChannel:(JavaNioChannelsFileChannel *)channel
                                          withLong:(jlong)position
                                          withLong:(jlong)size
                                       withBoolean:(jboolean)shared;

- (JavaNioChannelsFileChannel *)channel;

- (jlong)position;

- (jlong)size;

- (jboolean)isShared;

- (jboolean)overlapsWithLong:(jlong)start
                    withLong:(jlong)length;

- (jboolean)isValid;

- (void)release__;

- (void)close;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaNioChannelsFileLock_init() {}

#endif // _JavaNioChannelsFileLock_H_
