//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/IllegalBlockingModeException.java
//

#ifndef _JavaNioChannelsIllegalBlockingModeException_H_
#define _JavaNioChannelsIllegalBlockingModeException_H_

#import "JreEmulation.h"
#include "java/lang/IllegalStateException.h"

#define JavaNioChannelsIllegalBlockingModeException_serialVersionUID -3335774961855590474LL

@interface JavaNioChannelsIllegalBlockingModeException : JavaLangIllegalStateException {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaNioChannelsIllegalBlockingModeException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaNioChannelsIllegalBlockingModeException, serialVersionUID, jlong)

#endif // _JavaNioChannelsIllegalBlockingModeException_H_
