//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/InterruptibleChannel.java
//

#ifndef _JavaNioChannelsInterruptibleChannel_H_
#define _JavaNioChannelsInterruptibleChannel_H_

#import "JreEmulation.h"
#include "java/nio/channels/Channel.h"

@protocol JavaNioChannelsInterruptibleChannel < JavaNioChannelsChannel, NSObject, JavaObject >
- (void)close;

@end

__attribute__((always_inline)) inline void JavaNioChannelsInterruptibleChannel_init() {}

#endif // _JavaNioChannelsInterruptibleChannel_H_
