//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/OverlappingFileLockException.java
//

#ifndef _JavaNioChannelsOverlappingFileLockException_H_
#define _JavaNioChannelsOverlappingFileLockException_H_

#import "JreEmulation.h"
#include "java/lang/IllegalStateException.h"

#define JavaNioChannelsOverlappingFileLockException_serialVersionUID 2047812138163068433LL

@interface JavaNioChannelsOverlappingFileLockException : JavaLangIllegalStateException {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaNioChannelsOverlappingFileLockException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaNioChannelsOverlappingFileLockException, serialVersionUID, jlong)

#endif // _JavaNioChannelsOverlappingFileLockException_H_
