//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/Pipe.java
//

#ifndef _JavaNioChannelsPipe_H_
#define _JavaNioChannelsPipe_H_

@class JavaNioChannelsPipe_SinkChannel;
@class JavaNioChannelsPipe_SourceChannel;
@class JavaNioChannelsSpiSelectorProvider;

#import "JreEmulation.h"
#include "java/nio/channels/GatheringByteChannel.h"
#include "java/nio/channels/ReadableByteChannel.h"
#include "java/nio/channels/ScatteringByteChannel.h"
#include "java/nio/channels/WritableByteChannel.h"
#include "java/nio/channels/spi/AbstractSelectableChannel.h"

@interface JavaNioChannelsPipe : NSObject {
}

+ (JavaNioChannelsPipe *)open;

- (instancetype)init;

- (JavaNioChannelsPipe_SinkChannel *)sink;

- (JavaNioChannelsPipe_SourceChannel *)source;

@end

__attribute__((always_inline)) inline void JavaNioChannelsPipe_init() {}
FOUNDATION_EXPORT JavaNioChannelsPipe *JavaNioChannelsPipe_open();

@interface JavaNioChannelsPipe_SinkChannel : JavaNioChannelsSpiAbstractSelectableChannel < JavaNioChannelsWritableByteChannel, JavaNioChannelsGatheringByteChannel > {
}

- (instancetype)initWithJavaNioChannelsSpiSelectorProvider:(JavaNioChannelsSpiSelectorProvider *)provider;

- (jint)validOps;

@end

__attribute__((always_inline)) inline void JavaNioChannelsPipe_SinkChannel_init() {}

@interface JavaNioChannelsPipe_SourceChannel : JavaNioChannelsSpiAbstractSelectableChannel < JavaNioChannelsReadableByteChannel, JavaNioChannelsScatteringByteChannel > {
}

- (instancetype)initWithJavaNioChannelsSpiSelectorProvider:(JavaNioChannelsSpiSelectorProvider *)provider;

- (jint)validOps;

@end

__attribute__((always_inline)) inline void JavaNioChannelsPipe_SourceChannel_init() {}

#endif // _JavaNioChannelsPipe_H_
