//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/ReadableByteChannel.java
//

#ifndef _JavaNioChannelsReadableByteChannel_H_
#define _JavaNioChannelsReadableByteChannel_H_

@class JavaNioByteBuffer;

#import "JreEmulation.h"
#include "java/nio/channels/Channel.h"

@protocol JavaNioChannelsReadableByteChannel < JavaNioChannelsChannel, NSObject, JavaObject >
- (jint)readWithJavaNioByteBuffer:(JavaNioByteBuffer *)buffer;

@end

__attribute__((always_inline)) inline void JavaNioChannelsReadableByteChannel_init() {}

#endif // _JavaNioChannelsReadableByteChannel_H_
