//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/UnsupportedAddressTypeException.java
//

#ifndef _JavaNioChannelsUnsupportedAddressTypeException_H_
#define _JavaNioChannelsUnsupportedAddressTypeException_H_

#import "JreEmulation.h"
#include "java/lang/IllegalArgumentException.h"

#define JavaNioChannelsUnsupportedAddressTypeException_serialVersionUID -2964323842829700493LL

@interface JavaNioChannelsUnsupportedAddressTypeException : JavaLangIllegalArgumentException {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaNioChannelsUnsupportedAddressTypeException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaNioChannelsUnsupportedAddressTypeException, serialVersionUID, jlong)

#endif // _JavaNioChannelsUnsupportedAddressTypeException_H_
