//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/stubbing/defaultanswers/ForwardsInvocations.java
//

#ifndef _OrgMockitoInternalStubbingDefaultanswersForwardsInvocations_H_
#define _OrgMockitoInternalStubbingDefaultanswersForwardsInvocations_H_

@protocol OrgMockitoInvocationInvocationOnMock;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "org/mockito/stubbing/Answer.h"

#define OrgMockitoInternalStubbingDefaultanswersForwardsInvocations_serialVersionUID -8343690268123254910LL

@interface OrgMockitoInternalStubbingDefaultanswersForwardsInvocations : NSObject < OrgMockitoStubbingAnswer, JavaIoSerializable > {
 @public
  id delegatedObject_;
}

- (instancetype)initWithId:(id)delegatedObject;

- (id)answerWithOrgMockitoInvocationInvocationOnMock:(id<OrgMockitoInvocationInvocationOnMock>)invocation;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalStubbingDefaultanswersForwardsInvocations *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalStubbingDefaultanswersForwardsInvocations_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalStubbingDefaultanswersForwardsInvocations, delegatedObject_, id)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalStubbingDefaultanswersForwardsInvocations, serialVersionUID, jlong)

#endif // _OrgMockitoInternalStubbingDefaultanswersForwardsInvocations_H_
