//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/collections/ArrayUtils.java
//

#ifndef _OrgMockitoInternalUtilCollectionsArrayUtils_H_
#define _OrgMockitoInternalUtilCollectionsArrayUtils_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilCollectionsArrayUtils : NSObject {
}

- (jboolean)isEmptyWithNSObjectArray:(IOSObjectArray *)array;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilCollectionsArrayUtils_init() {}

#endif // _OrgMockitoInternalUtilCollectionsArrayUtils_H_
