//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/collections/Sets.java
//

#ifndef _OrgMockitoInternalUtilCollectionsSets_H_
#define _OrgMockitoInternalUtilCollectionsSets_H_

@class IOSObjectArray;
@class OrgMockitoInternalUtilCollectionsIdentitySet;
@protocol JavaLangIterable;
@protocol JavaUtilSet;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilCollectionsSets : NSObject {
}

+ (id<JavaUtilSet>)newMockSafeHashSetWithJavaLangIterable:(id<JavaLangIterable>)mocks OBJC_METHOD_FAMILY_NONE;

+ (id<JavaUtilSet>)newMockSafeHashSetWithNSObjectArray:(IOSObjectArray *)mocks OBJC_METHOD_FAMILY_NONE;

+ (OrgMockitoInternalUtilCollectionsIdentitySet *)newIdentitySet OBJC_METHOD_FAMILY_NONE;

+ (id<JavaUtilSet>)newSetWithNSObjectArray:(IOSObjectArray *)elements OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilCollectionsSets_init() {}
FOUNDATION_EXPORT id<JavaUtilSet> OrgMockitoInternalUtilCollectionsSets_newMockSafeHashSetWithJavaLangIterable_(id<JavaLangIterable> mocks);
FOUNDATION_EXPORT id<JavaUtilSet> OrgMockitoInternalUtilCollectionsSets_newMockSafeHashSetWithNSObjectArray_(IOSObjectArray *mocks);
FOUNDATION_EXPORT OrgMockitoInternalUtilCollectionsIdentitySet *OrgMockitoInternalUtilCollectionsSets_newIdentitySet();
FOUNDATION_EXPORT id<JavaUtilSet> OrgMockitoInternalUtilCollectionsSets_newSetWithNSObjectArray_(IOSObjectArray *elements);

#endif // _OrgMockitoInternalUtilCollectionsSets_H_
