//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/CRC32.java
//

#ifndef _JavaUtilZipCRC32_H_
#define _JavaUtilZipCRC32_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/util/zip/Checksum.h"

@interface JavaUtilZipCRC32 : NSObject < JavaUtilZipChecksum > {
 @public
  jlong tbytes_;
}

- (jlong)getValue;

- (void)reset;

- (void)updateWithInt:(jint)val;

- (void)updateWithByteArray:(IOSByteArray *)buf;

- (void)updateWithByteArray:(IOSByteArray *)buf
                    withInt:(jint)offset
                    withInt:(jint)byteCount;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaUtilZipCRC32_init() {}

#endif // _JavaUtilZipCRC32_H_
