//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/GZIPOutputStream.java
//

#ifndef _JavaUtilZipGZIPOutputStream_H_
#define _JavaUtilZipGZIPOutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;
@class JavaUtilZipCRC32;

#import "JreEmulation.h"
#include "java/util/zip/DeflaterOutputStream.h"

@interface JavaUtilZipGZIPOutputStream : JavaUtilZipDeflaterOutputStream {
 @public
  JavaUtilZipCRC32 *crc_;
}

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os
                               withBoolean:(jboolean)syncFlush;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os
                                   withInt:(jint)bufferSize;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os
                                   withInt:(jint)bufferSize
                               withBoolean:(jboolean)syncFlush;

- (void)finish;

- (void)writeWithByteArray:(IOSByteArray *)buffer
                   withInt:(jint)off
                   withInt:(jint)nbytes;

@end

__attribute__((always_inline)) inline void JavaUtilZipGZIPOutputStream_init() {}

J2OBJC_FIELD_SETTER(JavaUtilZipGZIPOutputStream, crc_, JavaUtilZipCRC32 *)

#endif // _JavaUtilZipGZIPOutputStream_H_
