//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/InflaterOutputStream.java
//

#ifndef _JavaUtilZipInflaterOutputStream_H_
#define _JavaUtilZipInflaterOutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;
@class JavaUtilZipInflater;

#import "JreEmulation.h"
#include "java/io/FilterOutputStream.h"

#define JavaUtilZipInflaterOutputStream_DEFAULT_BUFFER_SIZE 1024

@interface JavaUtilZipInflaterOutputStream : JavaIoFilterOutputStream {
 @public
  JavaUtilZipInflater *inf_;
  IOSByteArray *buf_;
}

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                   withJavaUtilZipInflater:(JavaUtilZipInflater *)inf;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                   withJavaUtilZipInflater:(JavaUtilZipInflater *)inf
                                   withInt:(jint)bufferSize;

- (void)close;

- (void)flush;

- (void)finish;

- (void)writeWithInt:(jint)b;

- (void)writeWithByteArray:(IOSByteArray *)bytes
                   withInt:(jint)offset
                   withInt:(jint)byteCount;

@end

__attribute__((always_inline)) inline void JavaUtilZipInflaterOutputStream_init() {}

J2OBJC_FIELD_SETTER(JavaUtilZipInflaterOutputStream, inf_, JavaUtilZipInflater *)
J2OBJC_FIELD_SETTER(JavaUtilZipInflaterOutputStream, buf_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipInflaterOutputStream, DEFAULT_BUFFER_SIZE, jint)

#endif // _JavaUtilZipInflaterOutputStream_H_
