//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/ZipError.java
//

#ifndef _JavaUtilZipZipError_H_
#define _JavaUtilZipZipError_H_

#import "JreEmulation.h"
#include "java/lang/InternalError.h"

#define JavaUtilZipZipError_serialVersionUID 853973422266861979LL

@interface JavaUtilZipZipError : JavaLangInternalError {
}

- (instancetype)initWithNSString:(NSString *)s;

@end

__attribute__((always_inline)) inline void JavaUtilZipZipError_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipError, serialVersionUID, jlong)

#endif // _JavaUtilZipZipError_H_
