//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/regex/PatternSyntaxException.java
//

#ifndef _JavaUtilRegexPatternSyntaxException_H_
#define _JavaUtilRegexPatternSyntaxException_H_

#import "JreEmulation.h"
#include "java/lang/IllegalArgumentException.h"

#define JavaUtilRegexPatternSyntaxException_serialVersionUID -3864639126226059218LL

@interface JavaUtilRegexPatternSyntaxException : JavaLangIllegalArgumentException {
}

- (instancetype)initWithNSString:(NSString *)description_
                    withNSString:(NSString *)pattern
                         withInt:(jint)index;

- (NSString *)getPattern;

- (NSString *)getMessage;

- (NSString *)getDescription;

- (jint)getIndex;

@end

__attribute__((always_inline)) inline void JavaUtilRegexPatternSyntaxException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaUtilRegexPatternSyntaxException, serialVersionUID, jlong)

#endif // _JavaUtilRegexPatternSyntaxException_H_
