//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/regex/Splitter.java
//

#ifndef _JavaUtilRegexSplitter_H_
#define _JavaUtilRegexSplitter_H_

@class IOSObjectArray;
@class JavaUtilRegexPattern;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface JavaUtilRegexSplitter : NSObject {
}

+ (IOSObjectArray *)fastSplitWithNSString:(NSString *)re
                             withNSString:(NSString *)input
                                  withInt:(jint)limit;

+ (IOSObjectArray *)splitWithJavaUtilRegexPattern:(JavaUtilRegexPattern *)pattern
                                     withNSString:(NSString *)re
                                     withNSString:(NSString *)input
                                          withInt:(jint)limit;

@end

__attribute__((always_inline)) inline void JavaUtilRegexSplitter_init() {}
FOUNDATION_EXPORT IOSObjectArray *JavaUtilRegexSplitter_fastSplitWithNSString_withNSString_withInt_(NSString *re, NSString *input, jint limit);
FOUNDATION_EXPORT IOSObjectArray *JavaUtilRegexSplitter_splitWithJavaUtilRegexPattern_withNSString_withNSString_withInt_(JavaUtilRegexPattern *pattern, NSString *re, NSString *input, jint limit);

FOUNDATION_EXPORT NSString *JavaUtilRegexSplitter_METACHARACTERS_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilRegexSplitter, METACHARACTERS_, NSString *)

#endif // _JavaUtilRegexSplitter_H_
