//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/exceptions/stacktrace/ConditionalStackTraceFilter.java
//

#ifndef _OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter_H_
#define _OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter_H_

@class JavaLangThrowable;
@class OrgMockitoInternalExceptionsStacktraceStackTraceFilter;
@protocol OrgMockitoConfigurationIMockitoConfiguration;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter_serialVersionUID -8085849703510292641LL

@interface OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter : NSObject < JavaIoSerializable > {
 @public
  id<OrgMockitoConfigurationIMockitoConfiguration> config_;
  OrgMockitoInternalExceptionsStacktraceStackTraceFilter *filter__;
}

- (void)filterWithJavaLangThrowable:(JavaLangThrowable *)throwable;

- (instancetype)init;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter, config_, id<OrgMockitoConfigurationIMockitoConfiguration>)
J2OBJC_FIELD_SETTER(OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter, filter__, OrgMockitoInternalExceptionsStacktraceStackTraceFilter *)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter, serialVersionUID, jlong)

#endif // _OrgMockitoInternalExceptionsStacktraceConditionalStackTraceFilter_H_
