//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/matchers/And.java
//

#ifndef _OrgMockitoInternalMatchersAnd_H_
#define _OrgMockitoInternalMatchersAnd_H_

@protocol JavaUtilList;
@protocol OrgHamcrestDescription;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "org/mockito/ArgumentMatcher.h"

#define OrgMockitoInternalMatchersAnd_serialVersionUID -4624719625691177501LL

@interface OrgMockitoInternalMatchersAnd : OrgMockitoArgumentMatcher < JavaIoSerializable > {
 @public
  id<JavaUtilList> matchers_;
}

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)matchers;

- (jboolean)matchesWithId:(id)actual;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalMatchersAnd *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalMatchersAnd_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalMatchersAnd, matchers_, id<JavaUtilList>)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalMatchersAnd, serialVersionUID, jlong)

#endif // _OrgMockitoInternalMatchersAnd_H_
