//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/matchers/EqualsWithDelta.java
//

#ifndef _OrgMockitoInternalMatchersEqualsWithDelta_H_
#define _OrgMockitoInternalMatchersEqualsWithDelta_H_

@protocol OrgHamcrestDescription;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "org/mockito/ArgumentMatcher.h"

#define OrgMockitoInternalMatchersEqualsWithDelta_serialVersionUID 5066980489920383664LL

@interface OrgMockitoInternalMatchersEqualsWithDelta : OrgMockitoArgumentMatcher < JavaIoSerializable > {
 @public
  NSNumber *wanted_;
  NSNumber *delta_;
}

- (instancetype)initWithNSNumber:(NSNumber *)value
                    withNSNumber:(NSNumber *)delta;

- (jboolean)matchesWithId:(id)actual;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalMatchersEqualsWithDelta *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalMatchersEqualsWithDelta_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalMatchersEqualsWithDelta, wanted_, NSNumber *)
J2OBJC_FIELD_SETTER(OrgMockitoInternalMatchersEqualsWithDelta, delta_, NSNumber *)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalMatchersEqualsWithDelta, serialVersionUID, jlong)

#endif // _OrgMockitoInternalMatchersEqualsWithDelta_H_
