//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/jsr305/build_result/java/javax/annotation/meta/TypeQualifierValidator.java
//

#ifndef _JavaxAnnotationMetaTypeQualifierValidator_H_
#define _JavaxAnnotationMetaTypeQualifierValidator_H_

@class JavaxAnnotationMetaWhenEnum;
@protocol JavaLangAnnotationAnnotation;

#import "JreEmulation.h"

@protocol JavaxAnnotationMetaTypeQualifierValidator < NSObject, JavaObject >

- (JavaxAnnotationMetaWhenEnum *)forConstantValueWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                                                                           withId:(id)value;

@end

__attribute__((always_inline)) inline void JavaxAnnotationMetaTypeQualifierValidator_init() {}

#endif // _JavaxAnnotationMetaTypeQualifierValidator_H_
