//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/jsr305/build_result/java/javax/annotation/meta/When.java
//

#ifndef _JavaxAnnotationMetaWhen_H_
#define _JavaxAnnotationMetaWhen_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

typedef NS_ENUM(NSUInteger, JavaxAnnotationMetaWhen) {
  JavaxAnnotationMetaWhen_ALWAYS = 0,
  JavaxAnnotationMetaWhen_UNKNOWN = 1,
  JavaxAnnotationMetaWhen_MAYBE = 2,
  JavaxAnnotationMetaWhen_NEVER = 3,
};

@interface JavaxAnnotationMetaWhenEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *JavaxAnnotationMetaWhenEnum_values();

+ (JavaxAnnotationMetaWhenEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT JavaxAnnotationMetaWhenEnum *JavaxAnnotationMetaWhenEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL JavaxAnnotationMetaWhenEnum_initialized;
J2OBJC_STATIC_INIT(JavaxAnnotationMetaWhenEnum)

FOUNDATION_EXPORT JavaxAnnotationMetaWhenEnum *JavaxAnnotationMetaWhenEnum_values_[];

#define JavaxAnnotationMetaWhenEnum_ALWAYS JavaxAnnotationMetaWhenEnum_values_[JavaxAnnotationMetaWhen_ALWAYS]
J2OBJC_STATIC_FIELD_GETTER(JavaxAnnotationMetaWhenEnum, ALWAYS, JavaxAnnotationMetaWhenEnum *)

#define JavaxAnnotationMetaWhenEnum_UNKNOWN JavaxAnnotationMetaWhenEnum_values_[JavaxAnnotationMetaWhen_UNKNOWN]
J2OBJC_STATIC_FIELD_GETTER(JavaxAnnotationMetaWhenEnum, UNKNOWN, JavaxAnnotationMetaWhenEnum *)

#define JavaxAnnotationMetaWhenEnum_MAYBE JavaxAnnotationMetaWhenEnum_values_[JavaxAnnotationMetaWhen_MAYBE]
J2OBJC_STATIC_FIELD_GETTER(JavaxAnnotationMetaWhenEnum, MAYBE, JavaxAnnotationMetaWhenEnum *)

#define JavaxAnnotationMetaWhenEnum_NEVER JavaxAnnotationMetaWhenEnum_values_[JavaxAnnotationMetaWhen_NEVER]
J2OBJC_STATIC_FIELD_GETTER(JavaxAnnotationMetaWhenEnum, NEVER, JavaxAnnotationMetaWhenEnum *)

#endif // _JavaxAnnotationMetaWhen_H_
