//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/invocation/UnusedStubsFinder.java
//

#ifndef _OrgMockitoInternalInvocationUnusedStubsFinder_H_
#define _OrgMockitoInternalInvocationUnusedStubsFinder_H_

@protocol JavaUtilList;

#import "JreEmulation.h"

@interface OrgMockitoInternalInvocationUnusedStubsFinder : NSObject {
}

- (id<JavaUtilList>)findWithJavaUtilList:(id<JavaUtilList>)mocks;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalInvocationUnusedStubsFinder_init() {}

#endif // _OrgMockitoInternalInvocationUnusedStubsFinder_H_
