//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/com/google/j2objc/security/IosMD5MessageDigest.java
//

#ifndef _ComGoogleJ2objcSecurityIosMD5MessageDigest_H_
#define _ComGoogleJ2objcSecurityIosMD5MessageDigest_H_

@class IOSByteArray;
@class JavaIoByteArrayOutputStream;

#import "JreEmulation.h"
#include "java/security/MessageDigest.h"

@interface ComGoogleJ2objcSecurityIosMD5MessageDigest : JavaSecurityMessageDigest {
}

- (instancetype)init;

- (void)engineUpdateWithByte:(jbyte)input;

- (void)engineUpdateWithByteArray:(IOSByteArray *)input
                          withInt:(jint)offset
                          withInt:(jint)len;

- (IOSByteArray *)engineDigest;

- (void)engineReset;

- (jint)engineGetDigestLength;

@end

__attribute__((always_inline)) inline void ComGoogleJ2objcSecurityIosMD5MessageDigest_init() {}

#endif // _ComGoogleJ2objcSecurityIosMD5MessageDigest_H_
