//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/configuration/DefaultAnnotationEngine.java
//

#ifndef _OrgMockitoInternalConfigurationDefaultAnnotationEngine_H_
#define _OrgMockitoInternalConfigurationDefaultAnnotationEngine_H_

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "org/mockito/configuration/AnnotationEngine.h"
#include "org/mockito/internal/configuration/FieldAnnotationProcessor.h"

@interface OrgMockitoInternalConfigurationDefaultAnnotationEngine : NSObject < OrgMockitoConfigurationAnnotationEngine > {
 @public
  id<JavaUtilMap> annotationProcessorMap_;
}

- (instancetype)init;

- (id)createMockForWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                           withJavaLangReflectField:(JavaLangReflectField *)field;

- (id<OrgMockitoInternalConfigurationFieldAnnotationProcessor>)forAnnotationWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation;

- (void)registerAnnotationProcessorWithIOSClass:(IOSClass *)annotationClass
withOrgMockitoInternalConfigurationFieldAnnotationProcessor:(id<OrgMockitoInternalConfigurationFieldAnnotationProcessor>)fieldAnnotationProcessor;

- (void)processWithIOSClass:(IOSClass *)clazz
                     withId:(id)testInstance;

- (void)throwIfAlreadyAssignedWithJavaLangReflectField:(JavaLangReflectField *)field
                                           withBoolean:(jboolean)alreadyAssigned;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalConfigurationDefaultAnnotationEngine *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationDefaultAnnotationEngine_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalConfigurationDefaultAnnotationEngine, annotationProcessorMap_, id<JavaUtilMap>)

@interface OrgMockitoInternalConfigurationDefaultAnnotationEngine_$1 : NSObject < OrgMockitoInternalConfigurationFieldAnnotationProcessor > {
}

- (id)processWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                     withJavaLangReflectField:(JavaLangReflectField *)field;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationDefaultAnnotationEngine_$1_init() {}

#endif // _OrgMockitoInternalConfigurationDefaultAnnotationEngine_H_
