//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/configuration/MockAnnotationProcessor.java
//

#ifndef _OrgMockitoInternalConfigurationMockAnnotationProcessor_H_
#define _OrgMockitoInternalConfigurationMockAnnotationProcessor_H_

@class JavaLangReflectField;
@protocol OrgMockitoMock;

#import "JreEmulation.h"
#include "org/mockito/internal/configuration/FieldAnnotationProcessor.h"

@interface OrgMockitoInternalConfigurationMockAnnotationProcessor : NSObject < OrgMockitoInternalConfigurationFieldAnnotationProcessor > {
}

- (id)processWithJavaLangAnnotationAnnotation:(id<OrgMockitoMock>)annotation
                     withJavaLangReflectField:(JavaLangReflectField *)field;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationMockAnnotationProcessor_init() {}

#endif // _OrgMockitoInternalConfigurationMockAnnotationProcessor_H_
