//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/configuration/SpyAnnotationEngine.java
//

#ifndef _OrgMockitoInternalConfigurationSpyAnnotationEngine_H_
#define _OrgMockitoInternalConfigurationSpyAnnotationEngine_H_

@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;

#import "JreEmulation.h"
#include "org/mockito/configuration/AnnotationEngine.h"

@interface OrgMockitoInternalConfigurationSpyAnnotationEngine : NSObject < OrgMockitoConfigurationAnnotationEngine > {
}

- (id)createMockForWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                           withJavaLangReflectField:(JavaLangReflectField *)field;

- (void)processWithIOSClass:(IOSClass *)context
                     withId:(id)testInstance;

- (void)assertNoIncompatibleAnnotationsWithIOSClass:(IOSClass *)annotation
                           withJavaLangReflectField:(JavaLangReflectField *)field
                                  withIOSClassArray:(IOSObjectArray *)undesiredAnnotations;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationSpyAnnotationEngine_init() {}

#endif // _OrgMockitoInternalConfigurationSpyAnnotationEngine_H_
