//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/internal/progress/MockingProgress.java
//

#ifndef _OrgMockitoInternalProgressMockingProgress_H_
#define _OrgMockitoInternalProgressMockingProgress_H_

@class IOSClass;
@protocol OrgMockitoInternalListenersMockingProgressListener;
@protocol OrgMockitoInternalProgressArgumentMatcherStorage;
@protocol OrgMockitoInternalProgressIOngoingStubbing;
@protocol OrgMockitoInvocationInvocation;
@protocol OrgMockitoVerificationVerificationMode;

#import "JreEmulation.h"

@protocol OrgMockitoInternalProgressMockingProgress < NSObject, JavaObject >

- (void)reportOngoingStubbingWithOrgMockitoInternalProgressIOngoingStubbing:(id<OrgMockitoInternalProgressIOngoingStubbing>)iOngoingStubbing;

- (id<OrgMockitoInternalProgressIOngoingStubbing>)pullOngoingStubbing;

- (void)verificationStartedWithOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)verificationMode;

- (id<OrgMockitoVerificationVerificationMode>)pullVerificationMode;

- (void)stubbingStarted;

- (void)stubbingCompletedWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)invocation;

- (void)validateState;

- (void)reset;

- (void)resetOngoingStubbing;

- (id<OrgMockitoInternalProgressArgumentMatcherStorage>)getArgumentMatcherStorage;

- (void)mockingStartedWithId:(id)mock
                withIOSClass:(IOSClass *)classToMock;

- (void)setListenerWithOrgMockitoInternalListenersMockingProgressListener:(id<OrgMockitoInternalListenersMockingProgressListener>)listener;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalProgressMockingProgress_init() {}

#endif // _OrgMockitoInternalProgressMockingProgress_H_
