//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/testing/mockito/build_result/java/org/mockito/verification/VerificationWithTimeout.java
//

#ifndef _OrgMockitoVerificationVerificationWithTimeout_H_
#define _OrgMockitoVerificationVerificationWithTimeout_H_

#import "JreEmulation.h"
#include "org/mockito/verification/VerificationMode.h"

@protocol OrgMockitoVerificationVerificationWithTimeout < OrgMockitoVerificationVerificationMode, NSObject, JavaObject >
- (id<OrgMockitoVerificationVerificationMode>)timesWithInt:(jint)wantedNumberOfInvocations;

- (id<OrgMockitoVerificationVerificationMode>)never;

- (id<OrgMockitoVerificationVerificationMode>)atLeastOnce;

- (id<OrgMockitoVerificationVerificationMode>)atLeastWithInt:(jint)minNumberOfInvocations;

- (id<OrgMockitoVerificationVerificationMode>)atMostWithInt:(jint)maxNumberOfInvocations;

- (id<OrgMockitoVerificationVerificationMode>)only;

@end

__attribute__((always_inline)) inline void OrgMockitoVerificationVerificationWithTimeout_init() {}

#endif // _OrgMockitoVerificationVerificationWithTimeout_H_
