//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/hash/Murmur3_32HashFunction.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonHashMurmur3_32HashFunction_RESTRICT
#define ComGoogleCommonHashMurmur3_32HashFunction_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonHashMurmur3_32HashFunction_RESTRICT
#if !defined (_ComGoogleCommonHashMurmur3_32HashFunction_) && (ComGoogleCommonHashMurmur3_32HashFunction_INCLUDE_ALL || ComGoogleCommonHashMurmur3_32HashFunction_INCLUDE)
#define _ComGoogleCommonHashMurmur3_32HashFunction_

@class ComGoogleCommonHashHashCode;
@protocol ComGoogleCommonHashHasher;
@protocol JavaLangCharSequence;

#define ComGoogleCommonHashAbstractStreamingHashFunction_RESTRICT 1
#define ComGoogleCommonHashAbstractStreamingHashFunction_INCLUDE 1
#include "com/google/common/hash/AbstractStreamingHashFunction.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonHashMurmur3_32HashFunction_C1 -862048943
#define ComGoogleCommonHashMurmur3_32HashFunction_C2 461845907
#define ComGoogleCommonHashMurmur3_32HashFunction_serialVersionUID 0LL

@interface ComGoogleCommonHashMurmur3_32HashFunction : ComGoogleCommonHashAbstractStreamingHashFunction < JavaIoSerializable > {
}

- (instancetype)initWithInt:(jint)seed;

- (jint)bits;

- (id<ComGoogleCommonHashHasher>)newHasher OBJC_METHOD_FAMILY_NONE;

- (NSString *)description;

- (ComGoogleCommonHashHashCode *)hashIntWithInt:(jint)input;

- (ComGoogleCommonHashHashCode *)hashLongWithLong:(jlong)input;

- (ComGoogleCommonHashHashCode *)hashStringWithJavaLangCharSequence:(id<JavaLangCharSequence>)input;

@end

__attribute__((always_inline)) inline void ComGoogleCommonHashMurmur3_32HashFunction_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonHashMurmur3_32HashFunction, C1, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonHashMurmur3_32HashFunction, C2, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonHashMurmur3_32HashFunction, serialVersionUID, jlong)
#endif
#if !defined (_ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher_) && (ComGoogleCommonHashMurmur3_32HashFunction_INCLUDE_ALL || ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher_INCLUDE)
#define _ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher_

@class ComGoogleCommonHashHashCode;
@class JavaNioByteBuffer;

#define ComGoogleCommonHashAbstractStreamingHashFunction_RESTRICT 1
#define ComGoogleCommonHashAbstractStreamingHashFunction_AbstractStreamingHasher_INCLUDE 1
#include "com/google/common/hash/AbstractStreamingHashFunction.h"


#define ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher_CHUNK_SIZE 4

@interface ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher : ComGoogleCommonHashAbstractStreamingHashFunction_AbstractStreamingHasher {
}

- (instancetype)initWithInt:(jint)seed;

- (void)processWithJavaNioByteBuffer:(JavaNioByteBuffer *)bb;

- (void)processRemainingWithJavaNioByteBuffer:(JavaNioByteBuffer *)bb;

- (ComGoogleCommonHashHashCode *)makeHash;

@end

__attribute__((always_inline)) inline void ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonHashMurmur3_32HashFunction_Murmur3_32Hasher, CHUNK_SIZE, jint)
#endif
