//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/math/src/main/java/java/math/RoundingMode.java
//

#ifndef _JavaMathRoundingMode_H_
#define _JavaMathRoundingMode_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

typedef NS_ENUM(NSUInteger, JavaMathRoundingMode) {
  JavaMathRoundingMode_UP = 0,
  JavaMathRoundingMode_DOWN = 1,
  JavaMathRoundingMode_CEILING = 2,
  JavaMathRoundingMode_FLOOR = 3,
  JavaMathRoundingMode_HALF_UP = 4,
  JavaMathRoundingMode_HALF_DOWN = 5,
  JavaMathRoundingMode_HALF_EVEN = 6,
  JavaMathRoundingMode_UNNECESSARY = 7,
};

@interface JavaMathRoundingModeEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithInt:(jint)rm
               withNSString:(NSString *)__name
                    withInt:(jint)__ordinal;

+ (JavaMathRoundingModeEnum *)valueOfWithInt:(jint)mode;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *JavaMathRoundingModeEnum_values();

+ (JavaMathRoundingModeEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT JavaMathRoundingModeEnum *JavaMathRoundingModeEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL JavaMathRoundingModeEnum_initialized;
J2OBJC_STATIC_INIT(JavaMathRoundingModeEnum)
FOUNDATION_EXPORT JavaMathRoundingModeEnum *JavaMathRoundingModeEnum_valueOfWithInt_(jint mode);

FOUNDATION_EXPORT JavaMathRoundingModeEnum *JavaMathRoundingModeEnum_values_[];

#define JavaMathRoundingModeEnum_UP JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_UP]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, UP, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_DOWN JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_DOWN]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, DOWN, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_CEILING JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_CEILING]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, CEILING, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_FLOOR JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_FLOOR]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, FLOOR, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_HALF_UP JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_HALF_UP]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, HALF_UP, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_HALF_DOWN JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_HALF_DOWN]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, HALF_DOWN, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_HALF_EVEN JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_HALF_EVEN]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, HALF_EVEN, JavaMathRoundingModeEnum *)

#define JavaMathRoundingModeEnum_UNNECESSARY JavaMathRoundingModeEnum_values_[JavaMathRoundingMode_UNNECESSARY]
J2OBJC_STATIC_FIELD_GETTER(JavaMathRoundingModeEnum, UNNECESSARY, JavaMathRoundingModeEnum *)

#endif // _JavaMathRoundingMode_H_
