//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/AbstractRangeSet.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectAbstractRangeSet_RESTRICT
#define ComGoogleCommonCollectAbstractRangeSet_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectAbstractRangeSet_RESTRICT
#if !defined (_ComGoogleCommonCollectAbstractRangeSet_) && (ComGoogleCommonCollectAbstractRangeSet_INCLUDE_ALL || ComGoogleCommonCollectAbstractRangeSet_INCLUDE)
#define _ComGoogleCommonCollectAbstractRangeSet_

@class ComGoogleCommonCollectRange;
@protocol JavaLangComparable;

#define ComGoogleCommonCollectRangeSet_RESTRICT 1
#define ComGoogleCommonCollectRangeSet_INCLUDE 1
#include "com/google/common/collect/RangeSet.h"


@interface ComGoogleCommonCollectAbstractRangeSet : NSObject < ComGoogleCommonCollectRangeSet > {
}

- (instancetype)init;

- (jboolean)containsWithJavaLangComparable:(id<JavaLangComparable>)value;

- (ComGoogleCommonCollectRange *)rangeContainingWithJavaLangComparable:(id<JavaLangComparable>)value;

- (jboolean)isEmpty;

- (void)addWithComGoogleCommonCollectRange:(ComGoogleCommonCollectRange *)range;

- (void)removeWithComGoogleCommonCollectRange:(ComGoogleCommonCollectRange *)range;

- (void)clear;

- (jboolean)enclosesAllWithComGoogleCommonCollectRangeSet:(id<ComGoogleCommonCollectRangeSet>)other;

- (void)addAllWithComGoogleCommonCollectRangeSet:(id<ComGoogleCommonCollectRangeSet>)other;

- (void)removeAllWithComGoogleCommonCollectRangeSet:(id<ComGoogleCommonCollectRangeSet>)other;

- (jboolean)enclosesWithComGoogleCommonCollectRange:(ComGoogleCommonCollectRange *)otherRange;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectAbstractRangeSet_init() {}
#endif
