//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/BiMap.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectBiMap_RESTRICT
#define ComGoogleCommonCollectBiMap_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectBiMap_RESTRICT
#if !defined (_ComGoogleCommonCollectBiMap_) && (ComGoogleCommonCollectBiMap_INCLUDE_ALL || ComGoogleCommonCollectBiMap_INCLUDE)
#define _ComGoogleCommonCollectBiMap_

@protocol JavaUtilSet;

#define JavaUtilMap_RESTRICT 1
#define JavaUtilMap_INCLUDE 1
#include "java/util/Map.h"


@protocol ComGoogleCommonCollectBiMap < JavaUtilMap, NSObject, JavaObject >
- (id)putWithId:(id)key
         withId:(id)value;

- (id)forcePutWithId:(id)key
              withId:(id)value;

- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)map;

- (id<JavaUtilSet>)values;

- (id<ComGoogleCommonCollectBiMap>)inverse;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectBiMap_init() {}
#endif
