//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/CartesianList.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectCartesianList_RESTRICT
#define ComGoogleCommonCollectCartesianList_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectCartesianList_RESTRICT
#if !defined (_ComGoogleCommonCollectCartesianList_) && (ComGoogleCommonCollectCartesianList_INCLUDE_ALL || ComGoogleCommonCollectCartesianList_INCLUDE)
#define _ComGoogleCommonCollectCartesianList_

@class ComGoogleCommonCollectImmutableList;
@class IOSIntArray;
@protocol JavaUtilList;

#define JavaUtilAbstractList_RESTRICT 1
#define JavaUtilAbstractList_INCLUDE 1
#include "java/util/AbstractList.h"


@interface ComGoogleCommonCollectCartesianList : JavaUtilAbstractList {
}

+ (id<JavaUtilList>)createWithJavaUtilList:(id<JavaUtilList>)lists;

- (instancetype)initWithComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)axes;

- (ComGoogleCommonCollectImmutableList *)getWithInt:(jint)index;

- (jint)size;

- (jboolean)containsWithId:(id)o;

- (jint)indexOfWithId:(id)o;

- (jint)lastIndexOfWithId:(id)o;


@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectCartesianList_init() {}
FOUNDATION_EXPORT id<JavaUtilList> ComGoogleCommonCollectCartesianList_createWithJavaUtilList_(id<JavaUtilList> lists);
#endif
#if !defined (_ComGoogleCommonCollectCartesianList_$1_) && (ComGoogleCommonCollectCartesianList_INCLUDE_ALL || ComGoogleCommonCollectCartesianList_$1_INCLUDE)
#define _ComGoogleCommonCollectCartesianList_$1_

@class ComGoogleCommonCollectCartesianList;

#define ComGoogleCommonCollectImmutableList_RESTRICT 1
#define ComGoogleCommonCollectImmutableList_INCLUDE 1
#include "com/google/common/collect/ImmutableList.h"


@interface ComGoogleCommonCollectCartesianList_$1 : ComGoogleCommonCollectImmutableList {
}

- (jint)size;

- (id)getWithInt:(jint)axis;

- (jboolean)isPartialView;

- (instancetype)initWithComGoogleCommonCollectCartesianList:(ComGoogleCommonCollectCartesianList *)outer$
                                                    withInt:(jint)capture$0;


@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectCartesianList_$1_init() {}
#endif
