//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/ClassToInstanceMap.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectClassToInstanceMap_RESTRICT
#define ComGoogleCommonCollectClassToInstanceMap_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectClassToInstanceMap_RESTRICT
#if !defined (_ComGoogleCommonCollectClassToInstanceMap_) && (ComGoogleCommonCollectClassToInstanceMap_INCLUDE_ALL || ComGoogleCommonCollectClassToInstanceMap_INCLUDE)
#define _ComGoogleCommonCollectClassToInstanceMap_

@class IOSClass;

#define JavaUtilMap_RESTRICT 1
#define JavaUtilMap_INCLUDE 1
#include "java/util/Map.h"


@protocol ComGoogleCommonCollectClassToInstanceMap < JavaUtilMap, NSObject, JavaObject >
- (id)getInstanceWithIOSClass:(IOSClass *)type;

- (id)putInstanceWithIOSClass:(IOSClass *)type
                       withId:(id)value;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectClassToInstanceMap_init() {}
#endif
