//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/ComputingConcurrentHashMap.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectComputingConcurrentHashMap_RESTRICT
#define ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectComputingConcurrentHashMap_RESTRICT
#if !defined (_ComGoogleCommonCollectComputingConcurrentHashMap_) && (ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE_ALL || ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE)
#define _ComGoogleCommonCollectComputingConcurrentHashMap_

@class ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment;
@class ComGoogleCommonCollectMapMaker;
@class ComGoogleCommonCollectMapMakerInternalMap_Segment;
@protocol ComGoogleCommonBaseFunction;

#define ComGoogleCommonCollectMapMakerInternalMap_RESTRICT 1
#define ComGoogleCommonCollectMapMakerInternalMap_INCLUDE 1
#include "com/google/common/collect/MapMakerInternalMap.h"


#define ComGoogleCommonCollectComputingConcurrentHashMap_serialVersionUID 4LL

@interface ComGoogleCommonCollectComputingConcurrentHashMap : ComGoogleCommonCollectMapMakerInternalMap {
 @public
  id<ComGoogleCommonBaseFunction> computingFunction_;
}

- (instancetype)initWithComGoogleCommonCollectMapMaker:(ComGoogleCommonCollectMapMaker *)builder
                       withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)computingFunction;

- (ComGoogleCommonCollectMapMakerInternalMap_Segment *)createSegmentWithInt:(jint)initialCapacity
                                                                    withInt:(jint)maxSegmentSize;

- (ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment *)segmentForWithInt:(jint)hash_;

- (id)getOrComputeWithId:(id)key;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectComputingConcurrentHashMap_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectComputingConcurrentHashMap, computingFunction_, id<ComGoogleCommonBaseFunction>)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectComputingConcurrentHashMap, serialVersionUID, jlong)
#endif
#if !defined (_ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment_) && (ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE_ALL || ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment_INCLUDE)
#define _ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment_

@class ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference;
@class ComGoogleCommonCollectMapMakerInternalMap;
@protocol ComGoogleCommonBaseFunction;
@protocol ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry;

#define ComGoogleCommonCollectMapMakerInternalMap_RESTRICT 1
#define ComGoogleCommonCollectMapMakerInternalMap_Segment_INCLUDE 1
#include "com/google/common/collect/MapMakerInternalMap.h"


@interface ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment : ComGoogleCommonCollectMapMakerInternalMap_Segment {
}

- (instancetype)initWithComGoogleCommonCollectMapMakerInternalMap:(ComGoogleCommonCollectMapMakerInternalMap *)map
                                                          withInt:(jint)initialCapacity
                                                          withInt:(jint)maxSegmentSize;

- (id)getOrComputeWithId:(id)key
                 withInt:(jint)hash_
withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)computingFunction;

- (id)computeWithId:(id)key
            withInt:(jint)hash_
withComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry:(id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)e
withComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference:(ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference *)computingValueReference;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectComputingConcurrentHashMap_ComputingSegment_init() {}
#endif
#if !defined (_ComGoogleCommonCollectComputingConcurrentHashMap_ComputationExceptionReference_) && (ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE_ALL || ComGoogleCommonCollectComputingConcurrentHashMap_ComputationExceptionReference_INCLUDE)
#define _ComGoogleCommonCollectComputingConcurrentHashMap_ComputationExceptionReference_

@class JavaLangRefReferenceQueue;
@class JavaLangThrowable;
@protocol ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry;

#define ComGoogleCommonCollectMapMakerInternalMap_RESTRICT 1
#define ComGoogleCommonCollectMapMakerInternalMap_ValueReference_INCLUDE 1
#include "com/google/common/collect/MapMakerInternalMap.h"


@interface ComGoogleCommonCollectComputingConcurrentHashMap_ComputationExceptionReference : NSObject < ComGoogleCommonCollectMapMakerInternalMap_ValueReference > {
 @public
  JavaLangThrowable *t_;
}

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)t;

- (id)get;

- (id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)getEntry;

- (id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)copyForWithJavaLangRefReferenceQueue:(JavaLangRefReferenceQueue *)queue
                                                                                              withId:(id)value
                                        withComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry:(id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)entry_ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isComputingReference;

- (id)waitForValue;

- (void)clearWithComGoogleCommonCollectMapMakerInternalMap_ValueReference:(id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)newValue;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectComputingConcurrentHashMap_ComputationExceptionReference_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectComputingConcurrentHashMap_ComputationExceptionReference, t_, JavaLangThrowable *)
#endif
#if !defined (_ComGoogleCommonCollectComputingConcurrentHashMap_ComputedReference_) && (ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE_ALL || ComGoogleCommonCollectComputingConcurrentHashMap_ComputedReference_INCLUDE)
#define _ComGoogleCommonCollectComputingConcurrentHashMap_ComputedReference_

@class JavaLangRefReferenceQueue;
@protocol ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry;

#define ComGoogleCommonCollectMapMakerInternalMap_RESTRICT 1
#define ComGoogleCommonCollectMapMakerInternalMap_ValueReference_INCLUDE 1
#include "com/google/common/collect/MapMakerInternalMap.h"


@interface ComGoogleCommonCollectComputingConcurrentHashMap_ComputedReference : NSObject < ComGoogleCommonCollectMapMakerInternalMap_ValueReference > {
 @public
  id value_;
}

- (instancetype)initWithId:(id)value;

- (id)get;

- (id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)getEntry;

- (id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)copyForWithJavaLangRefReferenceQueue:(JavaLangRefReferenceQueue *)queue
                                                                                              withId:(id)value
                                        withComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry:(id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)entry_ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isComputingReference;

- (id)waitForValue;

- (void)clearWithComGoogleCommonCollectMapMakerInternalMap_ValueReference:(id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)newValue;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectComputingConcurrentHashMap_ComputedReference_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectComputingConcurrentHashMap_ComputedReference, value_, id)
#endif
#if !defined (_ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference_) && (ComGoogleCommonCollectComputingConcurrentHashMap_INCLUDE_ALL || ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference_INCLUDE)
#define _ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference_

@class JavaLangRefReferenceQueue;
@protocol ComGoogleCommonBaseFunction;
@protocol ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry;

#define ComGoogleCommonCollectMapMakerInternalMap_RESTRICT 1
#define ComGoogleCommonCollectMapMakerInternalMap_ValueReference_INCLUDE 1
#include "com/google/common/collect/MapMakerInternalMap.h"


@interface ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference : NSObject < ComGoogleCommonCollectMapMakerInternalMap_ValueReference > {
 @public
  id<ComGoogleCommonBaseFunction> computingFunction_;
  id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference> computedReference_;
}

- (instancetype)initWithComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)computingFunction;

- (id)get;

- (id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)getEntry;

- (id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)copyForWithJavaLangRefReferenceQueue:(JavaLangRefReferenceQueue *)queue
                                                                                              withId:(id)value
                                        withComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry:(id<ComGoogleCommonCollectMapMakerInternalMap_ReferenceEntry>)entry_ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isComputingReference;

- (id)waitForValue;

- (void)clearWithComGoogleCommonCollectMapMakerInternalMap_ValueReference:(id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)newValue;

- (id)computeWithId:(id)key
            withInt:(jint)hash_;

- (void)setValueReferenceWithComGoogleCommonCollectMapMakerInternalMap_ValueReference:(id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)valueReference;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference, computingFunction_, id<ComGoogleCommonBaseFunction>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectComputingConcurrentHashMap_ComputingValueReference, computedReference_, id<ComGoogleCommonCollectMapMakerInternalMap_ValueReference>)
#endif
