//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/EnumMultiset.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectEnumMultiset_RESTRICT
#define ComGoogleCommonCollectEnumMultiset_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectEnumMultiset_RESTRICT
#if !defined (_ComGoogleCommonCollectEnumMultiset_) && (ComGoogleCommonCollectEnumMultiset_INCLUDE_ALL || ComGoogleCommonCollectEnumMultiset_INCLUDE)
#define _ComGoogleCommonCollectEnumMultiset_

@class IOSClass;
@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol JavaLangIterable;

#define ComGoogleCommonCollectAbstractMapBasedMultiset_RESTRICT 1
#define ComGoogleCommonCollectAbstractMapBasedMultiset_INCLUDE 1
#include "com/google/common/collect/AbstractMapBasedMultiset.h"


#define ComGoogleCommonCollectEnumMultiset_serialVersionUID 0LL

@interface ComGoogleCommonCollectEnumMultiset : ComGoogleCommonCollectAbstractMapBasedMultiset {
}

+ (ComGoogleCommonCollectEnumMultiset *)createWithIOSClass:(IOSClass *)type;

+ (ComGoogleCommonCollectEnumMultiset *)createWithJavaLangIterable:(id<JavaLangIterable>)elements;

+ (ComGoogleCommonCollectEnumMultiset *)createWithJavaLangIterable:(id<JavaLangIterable>)elements
                                                      withIOSClass:(IOSClass *)type;


@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectEnumMultiset_init() {}
FOUNDATION_EXPORT ComGoogleCommonCollectEnumMultiset *ComGoogleCommonCollectEnumMultiset_createWithIOSClass_(IOSClass *type);
FOUNDATION_EXPORT ComGoogleCommonCollectEnumMultiset *ComGoogleCommonCollectEnumMultiset_createWithJavaLangIterable_(id<JavaLangIterable> elements);
FOUNDATION_EXPORT ComGoogleCommonCollectEnumMultiset *ComGoogleCommonCollectEnumMultiset_createWithJavaLangIterable_withIOSClass_(id<JavaLangIterable> elements, IOSClass *type);

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectEnumMultiset, serialVersionUID, jlong)
#endif
