//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/ForwardingImmutableList.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectForwardingImmutableList_RESTRICT
#define ComGoogleCommonCollectForwardingImmutableList_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectForwardingImmutableList_RESTRICT
#if !defined (_ComGoogleCommonCollectForwardingImmutableList_) && (ComGoogleCommonCollectForwardingImmutableList_INCLUDE_ALL || ComGoogleCommonCollectForwardingImmutableList_INCLUDE)
#define _ComGoogleCommonCollectForwardingImmutableList_


@interface ComGoogleCommonCollectForwardingImmutableList : NSObject {
}

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectForwardingImmutableList_init() {}
#endif
