//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/ForwardingObject.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectForwardingObject_RESTRICT
#define ComGoogleCommonCollectForwardingObject_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectForwardingObject_RESTRICT
#if !defined (_ComGoogleCommonCollectForwardingObject_) && (ComGoogleCommonCollectForwardingObject_INCLUDE_ALL || ComGoogleCommonCollectForwardingObject_INCLUDE)
#define _ComGoogleCommonCollectForwardingObject_


@interface ComGoogleCommonCollectForwardingObject : NSObject {
}

- (instancetype)init;

- (id)delegate;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectForwardingObject_init() {}
#endif
