//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/ForwardingList.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectForwardingList_RESTRICT
#define ComGoogleCommonCollectForwardingList_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectForwardingList_RESTRICT
#if !defined (_ComGoogleCommonCollectForwardingList_) && (ComGoogleCommonCollectForwardingList_INCLUDE_ALL || ComGoogleCommonCollectForwardingList_INCLUDE)
#define _ComGoogleCommonCollectForwardingList_

@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilListIterator;

#define ComGoogleCommonCollectForwardingCollection_RESTRICT 1
#define ComGoogleCommonCollectForwardingCollection_INCLUDE 1
#include "com/google/common/collect/ForwardingCollection.h"

#define JavaUtilList_RESTRICT 1
#define JavaUtilList_INCLUDE 1
#include "java/util/List.h"


@interface ComGoogleCommonCollectForwardingList : ComGoogleCommonCollectForwardingCollection < JavaUtilList > {
}

- (instancetype)init;

- (id<JavaUtilList>)delegate;

- (void)addWithInt:(jint)index
            withId:(id)element;

- (jboolean)addAllWithInt:(jint)index
   withJavaUtilCollection:(id<JavaUtilCollection>)elements;

- (id)getWithInt:(jint)index;

- (jint)indexOfWithId:(id)element;

- (jint)lastIndexOfWithId:(id)element;

- (id<JavaUtilListIterator>)listIterator;

- (id<JavaUtilListIterator>)listIteratorWithInt:(jint)index;

- (id)removeWithInt:(jint)index;

- (id)setWithInt:(jint)index
          withId:(id)element;

- (id<JavaUtilList>)subListWithInt:(jint)fromIndex
                           withInt:(jint)toIndex;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (jboolean)standardAddWithId:(id)element;

- (jboolean)standardAddAllWithInt:(jint)index
             withJavaLangIterable:(id<JavaLangIterable>)elements;

- (jint)standardIndexOfWithId:(id)element;

- (jint)standardLastIndexOfWithId:(id)element;

- (id<JavaUtilIterator>)standardIterator;

- (id<JavaUtilListIterator>)standardListIterator;

- (id<JavaUtilListIterator>)standardListIteratorWithInt:(jint)start;

- (id<JavaUtilList>)standardSubListWithInt:(jint)fromIndex
                                   withInt:(jint)toIndex;

- (jboolean)standardEqualsWithId:(id)object;

- (jint)standardHashCode;


@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectForwardingList_init() {}
#endif
