//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/MapDifference.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectMapDifference_RESTRICT
#define ComGoogleCommonCollectMapDifference_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectMapDifference_RESTRICT
#if !defined (_ComGoogleCommonCollectMapDifference_) && (ComGoogleCommonCollectMapDifference_INCLUDE_ALL || ComGoogleCommonCollectMapDifference_INCLUDE)
#define _ComGoogleCommonCollectMapDifference_

@protocol JavaUtilMap;


@protocol ComGoogleCommonCollectMapDifference < NSObject, JavaObject >

- (jboolean)areEqual;

- (id<JavaUtilMap>)entriesOnlyOnLeft;

- (id<JavaUtilMap>)entriesOnlyOnRight;

- (id<JavaUtilMap>)entriesInCommon;

- (id<JavaUtilMap>)entriesDiffering;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectMapDifference_init() {}
#endif
#if !defined (_ComGoogleCommonCollectMapDifference_ValueDifference_) && (ComGoogleCommonCollectMapDifference_INCLUDE_ALL || ComGoogleCommonCollectMapDifference_ValueDifference_INCLUDE)
#define _ComGoogleCommonCollectMapDifference_ValueDifference_


@protocol ComGoogleCommonCollectMapDifference_ValueDifference < NSObject, JavaObject >

- (id)leftValue;

- (id)rightValue;

- (jboolean)isEqual:(id)other;

- (NSUInteger)hash;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectMapDifference_ValueDifference_init() {}
#endif
