//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/RegularContiguousSet.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectRegularContiguousSet_RESTRICT
#define ComGoogleCommonCollectRegularContiguousSet_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectRegularContiguousSet_RESTRICT
#if !defined (_ComGoogleCommonCollectRegularContiguousSet_) && (ComGoogleCommonCollectRegularContiguousSet_INCLUDE_ALL || ComGoogleCommonCollectRegularContiguousSet_INCLUDE)
#define _ComGoogleCommonCollectRegularContiguousSet_

@class ComGoogleCommonCollectBoundTypeEnum;
@class ComGoogleCommonCollectDiscreteDomain;
@class ComGoogleCommonCollectRange;
@class ComGoogleCommonCollectUnmodifiableIterator;
@class IOSObjectArray;
@protocol JavaLangComparable;
@protocol JavaUtilCollection;

#define ComGoogleCommonCollectContiguousSet_RESTRICT 1
#define ComGoogleCommonCollectContiguousSet_INCLUDE 1
#include "com/google/common/collect/ContiguousSet.h"


#define ComGoogleCommonCollectRegularContiguousSet_serialVersionUID 0LL

@interface ComGoogleCommonCollectRegularContiguousSet : ComGoogleCommonCollectContiguousSet {
}

- (instancetype)initWithComGoogleCommonCollectRange:(ComGoogleCommonCollectRange *)range
           withComGoogleCommonCollectDiscreteDomain:(ComGoogleCommonCollectDiscreteDomain *)domain;

- (ComGoogleCommonCollectContiguousSet *)headSetImplWithId:(id<JavaLangComparable>)toElement
                                               withBoolean:(jboolean)inclusive;

- (ComGoogleCommonCollectContiguousSet *)subSetImplWithId:(id<JavaLangComparable>)fromElement
                                              withBoolean:(jboolean)fromInclusive
                                                   withId:(id<JavaLangComparable>)toElement
                                              withBoolean:(jboolean)toInclusive;

- (ComGoogleCommonCollectContiguousSet *)tailSetImplWithId:(id<JavaLangComparable>)fromElement
                                               withBoolean:(jboolean)inclusive;

- (jint)indexOfWithId:(id)target;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (ComGoogleCommonCollectUnmodifiableIterator *)descendingIterator;

- (jboolean)isPartialView;

- (id)first;

- (id)last;

- (jint)size;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)targets;

- (jboolean)isEmpty;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)other;

- (ComGoogleCommonCollectContiguousSet *)intersectionWithComGoogleCommonCollectContiguousSet:(ComGoogleCommonCollectContiguousSet *)other;

- (ComGoogleCommonCollectRange *)range;

- (ComGoogleCommonCollectRange *)rangeWithComGoogleCommonCollectBoundTypeEnum:(ComGoogleCommonCollectBoundTypeEnum *)lowerBoundType
                                      withComGoogleCommonCollectBoundTypeEnum:(ComGoogleCommonCollectBoundTypeEnum *)upperBoundType;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (id)writeReplace;


@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectRegularContiguousSet_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectRegularContiguousSet, serialVersionUID, jlong)
#endif
#if !defined (_ComGoogleCommonCollectRegularContiguousSet_SerializedForm_) && (ComGoogleCommonCollectRegularContiguousSet_INCLUDE_ALL || ComGoogleCommonCollectRegularContiguousSet_SerializedForm_INCLUDE)
#define _ComGoogleCommonCollectRegularContiguousSet_SerializedForm_

@class ComGoogleCommonCollectDiscreteDomain;
@class ComGoogleCommonCollectRange;

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


@interface ComGoogleCommonCollectRegularContiguousSet_SerializedForm : NSObject < JavaIoSerializable > {
 @public
  ComGoogleCommonCollectRange *range_;
  ComGoogleCommonCollectDiscreteDomain *domain_;
}

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectRegularContiguousSet_SerializedForm_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularContiguousSet_SerializedForm, range_, ComGoogleCommonCollectRange *)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularContiguousSet_SerializedForm, domain_, ComGoogleCommonCollectDiscreteDomain *)
#endif
#if !defined (_ComGoogleCommonCollectRegularContiguousSet_$1_) && (ComGoogleCommonCollectRegularContiguousSet_INCLUDE_ALL || ComGoogleCommonCollectRegularContiguousSet_$1_INCLUDE)
#define _ComGoogleCommonCollectRegularContiguousSet_$1_

@class ComGoogleCommonCollectRegularContiguousSet;
@protocol JavaLangComparable;

#define ComGoogleCommonCollectAbstractSequentialIterator_RESTRICT 1
#define ComGoogleCommonCollectAbstractSequentialIterator_INCLUDE 1
#include "com/google/common/collect/AbstractSequentialIterator.h"


@interface ComGoogleCommonCollectRegularContiguousSet_$1 : ComGoogleCommonCollectAbstractSequentialIterator {
 @public
  id<JavaLangComparable> last_;
}

- (id)computeNextWithId:(id<JavaLangComparable>)previous;

- (instancetype)initWithComGoogleCommonCollectRegularContiguousSet:(ComGoogleCommonCollectRegularContiguousSet *)outer$
                                            withJavaLangComparable:(id<JavaLangComparable>)arg$0;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectRegularContiguousSet_$1_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularContiguousSet_$1, last_, id)
#endif
#if !defined (_ComGoogleCommonCollectRegularContiguousSet_$2_) && (ComGoogleCommonCollectRegularContiguousSet_INCLUDE_ALL || ComGoogleCommonCollectRegularContiguousSet_$2_INCLUDE)
#define _ComGoogleCommonCollectRegularContiguousSet_$2_

@class ComGoogleCommonCollectRegularContiguousSet;
@protocol JavaLangComparable;

#define ComGoogleCommonCollectAbstractSequentialIterator_RESTRICT 1
#define ComGoogleCommonCollectAbstractSequentialIterator_INCLUDE 1
#include "com/google/common/collect/AbstractSequentialIterator.h"


@interface ComGoogleCommonCollectRegularContiguousSet_$2 : ComGoogleCommonCollectAbstractSequentialIterator {
 @public
  id<JavaLangComparable> first_;
}

- (id)computeNextWithId:(id<JavaLangComparable>)previous;

- (instancetype)initWithComGoogleCommonCollectRegularContiguousSet:(ComGoogleCommonCollectRegularContiguousSet *)outer$
                                            withJavaLangComparable:(id<JavaLangComparable>)arg$0;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectRegularContiguousSet_$2_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularContiguousSet_$2, first_, id)
#endif
