//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/SortedIterables.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectSortedIterables_RESTRICT
#define ComGoogleCommonCollectSortedIterables_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectSortedIterables_RESTRICT
#if !defined (_ComGoogleCommonCollectSortedIterables_) && (ComGoogleCommonCollectSortedIterables_INCLUDE_ALL || ComGoogleCommonCollectSortedIterables_INCLUDE)
#define _ComGoogleCommonCollectSortedIterables_

@protocol JavaLangIterable;
@protocol JavaUtilComparator;
@protocol JavaUtilSortedSet;


@interface ComGoogleCommonCollectSortedIterables : NSObject {
}

+ (jboolean)hasSameComparatorWithJavaUtilComparator:(id<JavaUtilComparator>)comparator
                               withJavaLangIterable:(id<JavaLangIterable>)elements;

+ (id<JavaUtilComparator>)comparatorWithJavaUtilSortedSet:(id<JavaUtilSortedSet>)sortedSet;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectSortedIterables_init() {}
FOUNDATION_EXPORT jboolean ComGoogleCommonCollectSortedIterables_hasSameComparatorWithJavaUtilComparator_withJavaLangIterable_(id<JavaUtilComparator> comparator, id<JavaLangIterable> elements);
FOUNDATION_EXPORT id<JavaUtilComparator> ComGoogleCommonCollectSortedIterables_comparatorWithJavaUtilSortedSet_(id<JavaUtilSortedSet> sortedSet);
#endif
