//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/Table.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectTable_RESTRICT
#define ComGoogleCommonCollectTable_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectTable_RESTRICT
#if !defined (_ComGoogleCommonCollectTable_) && (ComGoogleCommonCollectTable_INCLUDE_ALL || ComGoogleCommonCollectTable_INCLUDE)
#define _ComGoogleCommonCollectTable_

@protocol JavaUtilCollection;
@protocol JavaUtilMap;
@protocol JavaUtilSet;


@protocol ComGoogleCommonCollectTable < NSObject, JavaObject >

- (jboolean)containsWithId:(id)rowKey
                    withId:(id)columnKey;

- (jboolean)containsRowWithId:(id)rowKey;

- (jboolean)containsColumnWithId:(id)columnKey;

- (jboolean)containsValueWithId:(id)value;

- (id)getWithId:(id)rowKey
         withId:(id)columnKey;

- (jboolean)isEmpty;

- (jint)size;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (void)clear;

- (id)putWithId:(id)rowKey
         withId:(id)columnKey
         withId:(id)value;

- (void)putAllWithComGoogleCommonCollectTable:(id<ComGoogleCommonCollectTable>)table;

- (id)removeWithId:(id)rowKey
            withId:(id)columnKey;

- (id<JavaUtilMap>)rowWithId:(id)rowKey;

- (id<JavaUtilMap>)columnWithId:(id)columnKey;

- (id<JavaUtilSet>)cellSet;

- (id<JavaUtilSet>)rowKeySet;

- (id<JavaUtilSet>)columnKeySet;

- (id<JavaUtilCollection>)values;

- (id<JavaUtilMap>)rowMap;

- (id<JavaUtilMap>)columnMap;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectTable_init() {}
#endif
#if !defined (_ComGoogleCommonCollectTable_Cell_) && (ComGoogleCommonCollectTable_INCLUDE_ALL || ComGoogleCommonCollectTable_Cell_INCLUDE)
#define _ComGoogleCommonCollectTable_Cell_


@protocol ComGoogleCommonCollectTable_Cell < NSObject, JavaObject >

- (id)getRowKey;

- (id)getColumnKey;

- (id)getValue;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectTable_Cell_init() {}
#endif
