//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/collect/TransformedIterator.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectTransformedIterator_RESTRICT
#define ComGoogleCommonCollectTransformedIterator_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectTransformedIterator_RESTRICT
#if !defined (_ComGoogleCommonCollectTransformedIterator_) && (ComGoogleCommonCollectTransformedIterator_INCLUDE_ALL || ComGoogleCommonCollectTransformedIterator_INCLUDE)
#define _ComGoogleCommonCollectTransformedIterator_

#define JavaUtilIterator_RESTRICT 1
#define JavaUtilIterator_INCLUDE 1
#include "java/util/Iterator.h"


@interface ComGoogleCommonCollectTransformedIterator : NSObject < JavaUtilIterator > {
 @public
  id<JavaUtilIterator> backingIterator_;
}

- (instancetype)initWithJavaUtilIterator:(id<JavaUtilIterator>)backingIterator;

- (id)transformWithId:(id)from;

- (jboolean)hasNext;

- (id)next;

- (void)remove;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectTransformedIterator_init() {}

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectTransformedIterator, backingIterator_, id<JavaUtilIterator>)
#endif
