//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/junit/runners/model/FrameworkMember.java
//

#ifndef _OrgJunitRunnersModelFrameworkMember_H_
#define _OrgJunitRunnersModelFrameworkMember_H_

@class IOSObjectArray;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface OrgJunitRunnersModelFrameworkMember : NSObject {
}

- (IOSObjectArray *)getAnnotations;

- (jboolean)isShadowedByWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)otherMember;

- (jboolean)isShadowedByWithJavaUtilList:(id<JavaUtilList>)members;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJunitRunnersModelFrameworkMember_init() {}

#endif // _OrgJunitRunnersModelFrameworkMember_H_
