//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/org/junit/runners/model/InitializationError.java
//

#ifndef _OrgJunitRunnersModelInitializationError_H_
#define _OrgJunitRunnersModelInitializationError_H_

@class JavaLangThrowable;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define OrgJunitRunnersModelInitializationError_serialVersionUID 1LL

@interface OrgJunitRunnersModelInitializationError : JavaLangException {
 @public
  id<JavaUtilList> fErrors_;
}

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)errors;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)error;

- (instancetype)initWithNSString:(NSString *)string;

- (id<JavaUtilList>)getCauses;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgJunitRunnersModelInitializationError *)other;

@end

__attribute__((always_inline)) inline void OrgJunitRunnersModelInitializationError_init() {}

J2OBJC_FIELD_SETTER(OrgJunitRunnersModelInitializationError, fErrors_, id<JavaUtilList>)

J2OBJC_STATIC_FIELD_GETTER(OrgJunitRunnersModelInitializationError, serialVersionUID, jlong)

#endif // _OrgJunitRunnersModelInitializationError_H_
