//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/event/ActionCompleteEvent.java
//

#include "ActionCompleteEvent.h"
#include "Event.h"
#include "EventType.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JSONObject.h"
#include "ObjectProperty.h"
#include "com/google/common/collect/ImmutableSet.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"

@interface RtdcCoreEventActionCompleteEvent () {
 @public
  NSString *objectType_;
  jint objectId_;
  NSString *action_;
}

@end

J2OBJC_FIELD_SETTER(RtdcCoreEventActionCompleteEvent, objectType_, NSString *)
J2OBJC_FIELD_SETTER(RtdcCoreEventActionCompleteEvent, action_, NSString *)

@interface RtdcCoreEventActionCompleteEvent_Handler : NSObject

@end

__attribute__((unused)) static void RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(RtdcCoreEventActionCompleteEvent_PropertiesEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static RtdcCoreEventActionCompleteEvent_PropertiesEnum *new_RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_INITIALIZED_DEFN(RtdcCoreEventActionCompleteEvent)

RtdcCoreEventEventType *RtdcCoreEventActionCompleteEvent_TYPE_;

@implementation RtdcCoreEventActionCompleteEvent

- (instancetype)initWithInt:(jint)objectId
               withNSString:(NSString *)objectType
               withNSString:(NSString *)action {
  RtdcCoreEventActionCompleteEvent_initWithInt_withNSString_withNSString_(self, objectId, objectType, action);
  return self;
}

- (instancetype)initWithJSONJSONObject:(JSONJSONObject *)object {
  RtdcCoreEventActionCompleteEvent_initWithJSONJSONObject_(self, object);
  return self;
}

- (jint)getObjectId {
  return objectId_;
}

- (NSString *)getObjectType {
  return objectType_;
}

- (NSString *)getAction {
  return action_;
}

- (void)fire {
  for (id<RtdcCoreEventActionCompleteEvent_Handler> __strong handler in nil_chk([self getHandlersWithRtdcCoreEventEventType:RtdcCoreEventActionCompleteEvent_TYPE_])) [((id<RtdcCoreEventActionCompleteEvent_Handler>) nil_chk(handler)) onActionCompleteWithRtdcCoreEventActionCompleteEvent:self];
}

- (IOSObjectArray *)getProperties {
  return RtdcCoreEventActionCompleteEvent_PropertiesEnum_values();
}

- (NSString *)getType {
  return [((RtdcCoreEventEventType *) nil_chk(RtdcCoreEventActionCompleteEvent_TYPE_)) getName];
}

- (id)getValueWithModelObjectProperty:(id<ModelObjectProperty>)property {
  switch ([(RtdcCoreEventActionCompleteEvent_PropertiesEnum *) check_class_cast(property, [RtdcCoreEventActionCompleteEvent_PropertiesEnum class]) ordinal]) {
    case RtdcCoreEventActionCompleteEvent_Properties_objectId:
    return JavaLangInteger_valueOfWithInt_(objectId_);
    case RtdcCoreEventActionCompleteEvent_Properties_objectType:
    return objectType_;
    case RtdcCoreEventActionCompleteEvent_Properties_action:
    return action_;
  }
  return nil;
}

- (void)dealloc {
  RELEASE_(objectType_);
  RELEASE_(action_);
  [super dealloc];
}

+ (void)initialize {
  if (self == [RtdcCoreEventActionCompleteEvent class]) {
    JreStrongAssignAndConsume(&RtdcCoreEventActionCompleteEvent_TYPE_, new_RtdcCoreEventEventType_initWithNSString_(@"actionCompleteEvent"));
    J2OBJC_SET_INITIALIZED(RtdcCoreEventActionCompleteEvent)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:withNSString:withNSString:", "ActionCompleteEvent", NULL, 0x1, NULL, NULL },
    { "initWithJSONJSONObject:", "ActionCompleteEvent", NULL, 0x1, NULL, NULL },
    { "getObjectId", NULL, "I", 0x1, NULL, NULL },
    { "getObjectType", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getAction", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "fire", NULL, "V", 0x1, NULL, NULL },
    { "getProperties", NULL, "[Lrtdc.core.model.ObjectProperty;", 0x1, NULL, NULL },
    { "getType", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getValueWithModelObjectProperty:", "getValue", "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TYPE_", NULL, 0x19, "Lrtdc.core.event.EventType;", &RtdcCoreEventActionCompleteEvent_TYPE_, "Lrtdc/core/event/EventType<Lrtdc/core/event/ActionCompleteEvent$Handler;>;", .constantValue.asLong = 0 },
    { "objectType_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "objectId_", NULL, 0x12, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "action_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lrtdc.core.event.ActionCompleteEvent$Handler;"};
  static const char *inner_classes[] = {"Lrtdc.core.event.ActionCompleteEvent$Handler;", "Lrtdc.core.event.ActionCompleteEvent$Properties;"};
  static const J2ObjcClassInfo _RtdcCoreEventActionCompleteEvent = { 2, "ActionCompleteEvent", "rtdc.core.event", NULL, 0x1, 9, methods, 4, fields, 1, superclass_type_args, 2, inner_classes, NULL, "Lrtdc/core/event/Event<Lrtdc/core/event/ActionCompleteEvent$Handler;>;" };
  return &_RtdcCoreEventActionCompleteEvent;
}

@end

void RtdcCoreEventActionCompleteEvent_initWithInt_withNSString_withNSString_(RtdcCoreEventActionCompleteEvent *self, jint objectId, NSString *objectType, NSString *action) {
  RtdcCoreEventEvent_init(self);
  self->objectId_ = objectId;
  JreStrongAssign(&self->objectType_, objectType);
  JreStrongAssign(&self->action_, action);
}

RtdcCoreEventActionCompleteEvent *new_RtdcCoreEventActionCompleteEvent_initWithInt_withNSString_withNSString_(jint objectId, NSString *objectType, NSString *action) {
  RtdcCoreEventActionCompleteEvent *self = [RtdcCoreEventActionCompleteEvent alloc];
  RtdcCoreEventActionCompleteEvent_initWithInt_withNSString_withNSString_(self, objectId, objectType, action);
  return self;
}

void RtdcCoreEventActionCompleteEvent_initWithJSONJSONObject_(RtdcCoreEventActionCompleteEvent *self, JSONJSONObject *object) {
  RtdcCoreEventEvent_init(self);
  self->objectId_ = [((JSONJSONObject *) nil_chk(object)) getIntWithNSString:[((RtdcCoreEventActionCompleteEvent_PropertiesEnum *) nil_chk(JreLoadStatic(RtdcCoreEventActionCompleteEvent_PropertiesEnum, objectId))) name]];
  JreStrongAssign(&self->objectType_, [object getStringWithNSString:[((RtdcCoreEventActionCompleteEvent_PropertiesEnum *) nil_chk(JreLoadStatic(RtdcCoreEventActionCompleteEvent_PropertiesEnum, objectType))) name]]);
  JreStrongAssign(&self->action_, [object getStringWithNSString:[((RtdcCoreEventActionCompleteEvent_PropertiesEnum *) nil_chk(JreLoadStatic(RtdcCoreEventActionCompleteEvent_PropertiesEnum, action))) name]]);
}

RtdcCoreEventActionCompleteEvent *new_RtdcCoreEventActionCompleteEvent_initWithJSONJSONObject_(JSONJSONObject *object) {
  RtdcCoreEventActionCompleteEvent *self = [RtdcCoreEventActionCompleteEvent alloc];
  RtdcCoreEventActionCompleteEvent_initWithJSONJSONObject_(self, object);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RtdcCoreEventActionCompleteEvent)

@implementation RtdcCoreEventActionCompleteEvent_Handler

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onActionCompleteWithRtdcCoreEventActionCompleteEvent:", "onActionComplete", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreEventActionCompleteEvent_Handler = { 2, "Handler", "rtdc.core.event", "ActionCompleteEvent", 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RtdcCoreEventActionCompleteEvent_Handler;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RtdcCoreEventActionCompleteEvent_Handler)

J2OBJC_INITIALIZED_DEFN(RtdcCoreEventActionCompleteEvent_PropertiesEnum)

RtdcCoreEventActionCompleteEvent_PropertiesEnum *RtdcCoreEventActionCompleteEvent_PropertiesEnum_values_[3];

@implementation RtdcCoreEventActionCompleteEvent_PropertiesEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *RtdcCoreEventActionCompleteEvent_PropertiesEnum_values() {
  RtdcCoreEventActionCompleteEvent_PropertiesEnum_initialize();
  return [IOSObjectArray arrayWithObjects:RtdcCoreEventActionCompleteEvent_PropertiesEnum_values_ count:3 type:RtdcCoreEventActionCompleteEvent_PropertiesEnum_class_()];
}

+ (IOSObjectArray *)values {
  return RtdcCoreEventActionCompleteEvent_PropertiesEnum_values();
}

+ (RtdcCoreEventActionCompleteEvent_PropertiesEnum *)valueOfWithNSString:(NSString *)name {
  return RtdcCoreEventActionCompleteEvent_PropertiesEnum_valueOfWithNSString_(name);
}

RtdcCoreEventActionCompleteEvent_PropertiesEnum *RtdcCoreEventActionCompleteEvent_PropertiesEnum_valueOfWithNSString_(NSString *name) {
  RtdcCoreEventActionCompleteEvent_PropertiesEnum_initialize();
  for (int i = 0; i < 3; i++) {
    RtdcCoreEventActionCompleteEvent_PropertiesEnum *e = RtdcCoreEventActionCompleteEvent_PropertiesEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [RtdcCoreEventActionCompleteEvent_PropertiesEnum class]) {
    RtdcCoreEventActionCompleteEvent_PropertiesEnum_objectId = new_RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(@"objectId", 0);
    RtdcCoreEventActionCompleteEvent_PropertiesEnum_objectType = new_RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(@"objectType", 1);
    RtdcCoreEventActionCompleteEvent_PropertiesEnum_action = new_RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(@"action", 2);
    J2OBJC_SET_INITIALIZED(RtdcCoreEventActionCompleteEvent_PropertiesEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "objectId", "objectId", 0x4019, "Lrtdc.core.event.ActionCompleteEvent$Properties;", &RtdcCoreEventActionCompleteEvent_PropertiesEnum_objectId, NULL, .constantValue.asLong = 0 },
    { "objectType", "objectType", 0x4019, "Lrtdc.core.event.ActionCompleteEvent$Properties;", &RtdcCoreEventActionCompleteEvent_PropertiesEnum_objectType, NULL, .constantValue.asLong = 0 },
    { "action", "action", 0x4019, "Lrtdc.core.event.ActionCompleteEvent$Properties;", &RtdcCoreEventActionCompleteEvent_PropertiesEnum_action, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lrtdc.core.event.ActionCompleteEvent$Properties;"};
  static const J2ObjcClassInfo _RtdcCoreEventActionCompleteEvent_PropertiesEnum = { 2, "Properties", "rtdc.core.event", "ActionCompleteEvent", 0x4019, 0, NULL, 3, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lrtdc/core/event/ActionCompleteEvent$Properties;>;Lrtdc/core/model/ObjectProperty<Lrtdc/core/event/ActionCompleteEvent;>;" };
  return &_RtdcCoreEventActionCompleteEvent_PropertiesEnum;
}

@end

void RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(RtdcCoreEventActionCompleteEvent_PropertiesEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

RtdcCoreEventActionCompleteEvent_PropertiesEnum *new_RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  RtdcCoreEventActionCompleteEvent_PropertiesEnum *self = [RtdcCoreEventActionCompleteEvent_PropertiesEnum alloc];
  RtdcCoreEventActionCompleteEvent_PropertiesEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RtdcCoreEventActionCompleteEvent_PropertiesEnum)
