//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/view/ActionListView.java
//

#ifndef _ActionListView_H_
#define _ActionListView_H_

#include "J2ObjC_header.h"
#include "View.h"

@protocol JavaUtilList;

@protocol RtdcCoreViewActionListView < RtdcCoreViewView, NSObject, JavaObject >

- (void)setActionsWithJavaUtilList:(id<JavaUtilList>)actions;

@end

J2OBJC_EMPTY_STATIC_INIT(RtdcCoreViewActionListView)

J2OBJC_TYPE_LITERAL_HEADER(RtdcCoreViewActionListView)

#endif // _ActionListView_H_
