//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/controller/AddUserController.java
//

#ifndef _AddUserController_H_
#define _AddUserController_H_

#include "ActionCompleteEvent.h"
#include "Controller.h"
#include "J2ObjC_header.h"

@protocol RtdcCoreViewAddUserView;

@interface ControllerAddUserController : ControllerController < RtdcCoreEventActionCompleteEvent_Handler >

#pragma mark Public

- (instancetype)initWithRtdcCoreViewAddUserView:(id<RtdcCoreViewAddUserView>)view;

- (void)addUser;

- (void)deleteUser;

- (void)onActionCompleteWithRtdcCoreEventActionCompleteEvent:(RtdcCoreEventActionCompleteEvent *)event;

- (void)onStop;

#pragma mark Package-Private

- (NSString *)getTitle;

@end

J2OBJC_EMPTY_STATIC_INIT(ControllerAddUserController)

FOUNDATION_EXPORT void ControllerAddUserController_initWithRtdcCoreViewAddUserView_(ControllerAddUserController *self, id<RtdcCoreViewAddUserView> view);

FOUNDATION_EXPORT ControllerAddUserController *new_ControllerAddUserController_initWithRtdcCoreViewAddUserView_(id<RtdcCoreViewAddUserView> view) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ControllerAddUserController)

@compatibility_alias RtdcCoreControllerAddUserController ControllerAddUserController;

#endif // _AddUserController_H_
