//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/controller/AddUserController.java
//

#ifndef _AddUserController_H_
#define _AddUserController_H_

#include "ActionCompleteEvent.h"
#include "Controller.h"
#include "J2ObjC_header.h"

@protocol ViewAddUserView;

@interface ControllerAddUserController : ControllerController < EventActionCompleteEvent_Handler >

#pragma mark Public

- (instancetype)initWithViewAddUserView:(id<ViewAddUserView>)view;

- (void)addUser;

- (void)deleteUser;

- (void)onActionCompleteWithEventActionCompleteEvent:(EventActionCompleteEvent *)event;

- (void)onStop;

#pragma mark Package-Private

- (NSString *)getTitle;

@end

J2OBJC_EMPTY_STATIC_INIT(ControllerAddUserController)

FOUNDATION_EXPORT void ControllerAddUserController_initWithViewAddUserView_(ControllerAddUserController *self, id<ViewAddUserView> view);

FOUNDATION_EXPORT ControllerAddUserController *new_ControllerAddUserController_initWithViewAddUserView_(id<ViewAddUserView> view) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ControllerAddUserController)

@compatibility_alias RtdcCoreControllerAddUserController ControllerAddUserController;

#endif // _AddUserController_H_
