//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\view\AddUserView.java
//

#include "AddUserView.h"

@interface RtdcCoreViewAddUserView : NSObject
@end

@implementation RtdcCoreViewAddUserView

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getUsernameAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setUsernameAsStringWithNSString:", "setUsernameAsString", "V", 0x401, NULL },
    { "setErrorForUsernameWithNSString:", "setErrorForUsername", "V", 0x401, NULL },
    { "getSurnameAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setSurnameAsStringWithNSString:", "setSurnameAsString", "V", 0x401, NULL },
    { "setErrorForSurnameWithNSString:", "setErrorForSurname", "V", 0x401, NULL },
    { "getFirstnameAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setFirstnameAsStringWithNSString:", "setFirstnameAsString", "V", 0x401, NULL },
    { "setErrorForFirstnameWithNSString:", "setErrorForFirstname", "V", 0x401, NULL },
    { "getEmailAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setEmailAsStringWithNSString:", "setEmailAsString", "V", 0x401, NULL },
    { "getRoleAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setRoleAsStringWithNSString:", "setRoleAsString", "V", 0x401, NULL },
    { "getPasswordAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setPasswordAsStringWithNSString:", "setPasswordAsString", "V", 0x401, NULL },
    { "setErrorForPasswordWithNSString:", "setErrorForPassword", "V", 0x401, NULL },
    { "getPermissionAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "setPermissionAsStringWithNSString:", "setPermissionAsString", "V", 0x401, NULL },
    { "setPermissionForSurnameWithNSString:", "setPermissionForSurname", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreViewAddUserView = { "AddUserView", "rtdc.core.view", NULL, 0x201, 19, methods, 0, NULL, 0, NULL};
  return &_RtdcCoreViewAddUserView;
}

@end

