//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/service/AsyncCallback.java
//

#include "AsyncCallback.h"

@interface ServiceAsyncCallback : NSObject
@end

@implementation ServiceAsyncCallback

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onSuccessWithId:", "onSuccess", "V", 0x401, NULL },
    { "onErrorWithNSString:", "onError", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ServiceAsyncCallback = { "AsyncCallback", "rtdc.core.service", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ServiceAsyncCallback;
}

@end

