//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/event/AuthenticationEvent.java
//

#ifndef _AuthenticationEvent_H_
#define _AuthenticationEvent_H_

#include "Event.h"
#include "EventHandler.h"
#include "J2ObjC_header.h"
#include "ObjectProperty.h"
#include "java/lang/Enum.h"

@class EventEventType;
@class IOSObjectArray;
@class JsonJSONObject;
@class ModelUser;
@protocol ModelObjectProperty;

@interface EventAuthenticationEvent : EventEvent

+ (EventEventType *)TYPE;

#pragma mark Public

- (instancetype)initWithJsonJSONObject:(JsonJSONObject *)object;

- (instancetype)initWithModelUser:(ModelUser *)user
                     withNSString:(NSString *)authenticationToken;

- (NSString *)getAuthenticationToken;

- (IOSObjectArray *)getProperties;

- (NSString *)getType;

- (ModelUser *)getUser;

- (id)getValueWithModelObjectProperty:(id<ModelObjectProperty>)property;

#pragma mark Package-Private

- (void)fire;

@end

J2OBJC_STATIC_INIT(EventAuthenticationEvent)

FOUNDATION_EXPORT EventEventType *EventAuthenticationEvent_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(EventAuthenticationEvent, TYPE_, EventEventType *)

FOUNDATION_EXPORT void EventAuthenticationEvent_initWithModelUser_withNSString_(EventAuthenticationEvent *self, ModelUser *user, NSString *authenticationToken);

FOUNDATION_EXPORT EventAuthenticationEvent *new_EventAuthenticationEvent_initWithModelUser_withNSString_(ModelUser *user, NSString *authenticationToken) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void EventAuthenticationEvent_initWithJsonJSONObject_(EventAuthenticationEvent *self, JsonJSONObject *object);

FOUNDATION_EXPORT EventAuthenticationEvent *new_EventAuthenticationEvent_initWithJsonJSONObject_(JsonJSONObject *object) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(EventAuthenticationEvent)

@compatibility_alias RtdcCoreEventAuthenticationEvent EventAuthenticationEvent;

typedef NS_ENUM(NSUInteger, EventAuthenticationEvent_Properties) {
  EventAuthenticationEvent_Properties_user = 0,
  EventAuthenticationEvent_Properties_authenticationToken = 1,
};

@interface EventAuthenticationEvent_PropertiesEnum : JavaLangEnum < NSCopying, ModelObjectProperty >

+ (EventAuthenticationEvent_PropertiesEnum *)user;

+ (EventAuthenticationEvent_PropertiesEnum *)authenticationToken;

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *EventAuthenticationEvent_PropertiesEnum_values();

+ (EventAuthenticationEvent_PropertiesEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT EventAuthenticationEvent_PropertiesEnum *EventAuthenticationEvent_PropertiesEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EventAuthenticationEvent_PropertiesEnum)

FOUNDATION_EXPORT EventAuthenticationEvent_PropertiesEnum *EventAuthenticationEvent_PropertiesEnum_values_[];

#define EventAuthenticationEvent_PropertiesEnum_user EventAuthenticationEvent_PropertiesEnum_values_[EventAuthenticationEvent_Properties_user]
J2OBJC_ENUM_CONSTANT_GETTER(EventAuthenticationEvent_PropertiesEnum, user)

#define EventAuthenticationEvent_PropertiesEnum_authenticationToken EventAuthenticationEvent_PropertiesEnum_values_[EventAuthenticationEvent_Properties_authenticationToken]
J2OBJC_ENUM_CONSTANT_GETTER(EventAuthenticationEvent_PropertiesEnum, authenticationToken)

J2OBJC_TYPE_LITERAL_HEADER(EventAuthenticationEvent_PropertiesEnum)

@protocol EventAuthenticationEvent_Handler < EventEventHandler, NSObject, JavaObject >

- (void)onAuthenticateWithEventAuthenticationEvent:(EventAuthenticationEvent *)event;

@end

J2OBJC_EMPTY_STATIC_INIT(EventAuthenticationEvent_Handler)

J2OBJC_TYPE_LITERAL_HEADER(EventAuthenticationEvent_Handler)

#endif // _AuthenticationEvent_H_
