//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/event/AuthenticationEvent.java
//

#include "AuthenticationEvent.h"
#include "Event.h"
#include "EventType.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JSONObject.h"
#include "ObjectProperty.h"
#include "User.h"
#include "com/google/common/collect/ImmutableSet.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

@interface RtdcCoreEventAuthenticationEvent () {
 @public
  ModelUser *user_;
  NSString *authenticationToken_;
}

@end

J2OBJC_FIELD_SETTER(RtdcCoreEventAuthenticationEvent, user_, ModelUser *)
J2OBJC_FIELD_SETTER(RtdcCoreEventAuthenticationEvent, authenticationToken_, NSString *)

__attribute__((unused)) static void RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(RtdcCoreEventAuthenticationEvent_PropertiesEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static RtdcCoreEventAuthenticationEvent_PropertiesEnum *new_RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@interface RtdcCoreEventAuthenticationEvent_Handler : NSObject

@end

J2OBJC_INITIALIZED_DEFN(RtdcCoreEventAuthenticationEvent)

RtdcCoreEventEventType *RtdcCoreEventAuthenticationEvent_TYPE_;

@implementation RtdcCoreEventAuthenticationEvent

- (instancetype)initWithModelUser:(ModelUser *)user
                     withNSString:(NSString *)authenticationToken {
  RtdcCoreEventAuthenticationEvent_initWithModelUser_withNSString_(self, user, authenticationToken);
  return self;
}

- (instancetype)initWithJSONJSONObject:(JSONJSONObject *)object {
  RtdcCoreEventAuthenticationEvent_initWithJSONJSONObject_(self, object);
  return self;
}

- (ModelUser *)getUser {
  return user_;
}

- (NSString *)getAuthenticationToken {
  return authenticationToken_;
}

- (void)fire {
  for (id<RtdcCoreEventAuthenticationEvent_Handler> __strong handler in nil_chk([self getHandlersWithRtdcCoreEventEventType:RtdcCoreEventAuthenticationEvent_TYPE_])) [((id<RtdcCoreEventAuthenticationEvent_Handler>) nil_chk(handler)) onAuthenticateWithRtdcCoreEventAuthenticationEvent:self];
}

- (IOSObjectArray *)getProperties {
  return RtdcCoreEventAuthenticationEvent_PropertiesEnum_values();
}

- (NSString *)getType {
  return [((RtdcCoreEventEventType *) nil_chk(RtdcCoreEventAuthenticationEvent_TYPE_)) getName];
}

- (id)getValueWithModelObjectProperty:(id<ModelObjectProperty>)property {
  switch ([(RtdcCoreEventAuthenticationEvent_PropertiesEnum *) check_class_cast(property, [RtdcCoreEventAuthenticationEvent_PropertiesEnum class]) ordinal]) {
    case RtdcCoreEventAuthenticationEvent_Properties_user:
    return user_;
    case RtdcCoreEventAuthenticationEvent_Properties_authenticationToken:
    return authenticationToken_;
  }
  return nil;
}

- (void)dealloc {
  RELEASE_(user_);
  RELEASE_(authenticationToken_);
  [super dealloc];
}

+ (void)initialize {
  if (self == [RtdcCoreEventAuthenticationEvent class]) {
    JreStrongAssignAndConsume(&RtdcCoreEventAuthenticationEvent_TYPE_, new_RtdcCoreEventEventType_initWithNSString_(@"authenticationEvent"));
    J2OBJC_SET_INITIALIZED(RtdcCoreEventAuthenticationEvent)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithModelUser:withNSString:", "AuthenticationEvent", NULL, 0x1, NULL, NULL },
    { "initWithJSONJSONObject:", "AuthenticationEvent", NULL, 0x1, NULL, NULL },
    { "getUser", NULL, "Lrtdc.core.model.User;", 0x1, NULL, NULL },
    { "getAuthenticationToken", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "fire", NULL, "V", 0x0, NULL, NULL },
    { "getProperties", NULL, "[Lrtdc.core.model.ObjectProperty;", 0x1, NULL, NULL },
    { "getType", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getValueWithModelObjectProperty:", "getValue", "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TYPE_", NULL, 0x19, "Lrtdc.core.event.EventType;", &RtdcCoreEventAuthenticationEvent_TYPE_, "Lrtdc/core/event/EventType<Lrtdc/core/event/AuthenticationEvent$Handler;>;", .constantValue.asLong = 0 },
    { "user_", NULL, 0x12, "Lrtdc.core.model.User;", NULL, NULL, .constantValue.asLong = 0 },
    { "authenticationToken_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lrtdc.core.event.AuthenticationEvent$Handler;"};
  static const char *inner_classes[] = {"Lrtdc.core.event.AuthenticationEvent$Properties;", "Lrtdc.core.event.AuthenticationEvent$Handler;"};
  static const J2ObjcClassInfo _RtdcCoreEventAuthenticationEvent = { 2, "AuthenticationEvent", "rtdc.core.event", NULL, 0x1, 8, methods, 3, fields, 1, superclass_type_args, 2, inner_classes, NULL, "Lrtdc/core/event/Event<Lrtdc/core/event/AuthenticationEvent$Handler;>;" };
  return &_RtdcCoreEventAuthenticationEvent;
}

@end

void RtdcCoreEventAuthenticationEvent_initWithModelUser_withNSString_(RtdcCoreEventAuthenticationEvent *self, ModelUser *user, NSString *authenticationToken) {
  RtdcCoreEventEvent_init(self);
  JreStrongAssign(&self->user_, user);
  JreStrongAssign(&self->authenticationToken_, authenticationToken);
}

RtdcCoreEventAuthenticationEvent *new_RtdcCoreEventAuthenticationEvent_initWithModelUser_withNSString_(ModelUser *user, NSString *authenticationToken) {
  RtdcCoreEventAuthenticationEvent *self = [RtdcCoreEventAuthenticationEvent alloc];
  RtdcCoreEventAuthenticationEvent_initWithModelUser_withNSString_(self, user, authenticationToken);
  return self;
}

void RtdcCoreEventAuthenticationEvent_initWithJSONJSONObject_(RtdcCoreEventAuthenticationEvent *self, JSONJSONObject *object) {
  RtdcCoreEventEvent_init(self);
  JreStrongAssignAndConsume(&self->user_, new_ModelUser_initWithJSONJSONObject_([((JSONJSONObject *) nil_chk(object)) getJSONObjectWithNSString:[((RtdcCoreEventAuthenticationEvent_PropertiesEnum *) nil_chk(JreLoadStatic(RtdcCoreEventAuthenticationEvent_PropertiesEnum, user))) name]]));
  JreStrongAssign(&self->authenticationToken_, [object optStringWithNSString:[((RtdcCoreEventAuthenticationEvent_PropertiesEnum *) nil_chk(JreLoadStatic(RtdcCoreEventAuthenticationEvent_PropertiesEnum, authenticationToken))) name]]);
}

RtdcCoreEventAuthenticationEvent *new_RtdcCoreEventAuthenticationEvent_initWithJSONJSONObject_(JSONJSONObject *object) {
  RtdcCoreEventAuthenticationEvent *self = [RtdcCoreEventAuthenticationEvent alloc];
  RtdcCoreEventAuthenticationEvent_initWithJSONJSONObject_(self, object);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RtdcCoreEventAuthenticationEvent)

J2OBJC_INITIALIZED_DEFN(RtdcCoreEventAuthenticationEvent_PropertiesEnum)

RtdcCoreEventAuthenticationEvent_PropertiesEnum *RtdcCoreEventAuthenticationEvent_PropertiesEnum_values_[2];

@implementation RtdcCoreEventAuthenticationEvent_PropertiesEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *RtdcCoreEventAuthenticationEvent_PropertiesEnum_values() {
  RtdcCoreEventAuthenticationEvent_PropertiesEnum_initialize();
  return [IOSObjectArray arrayWithObjects:RtdcCoreEventAuthenticationEvent_PropertiesEnum_values_ count:2 type:RtdcCoreEventAuthenticationEvent_PropertiesEnum_class_()];
}

+ (IOSObjectArray *)values {
  return RtdcCoreEventAuthenticationEvent_PropertiesEnum_values();
}

+ (RtdcCoreEventAuthenticationEvent_PropertiesEnum *)valueOfWithNSString:(NSString *)name {
  return RtdcCoreEventAuthenticationEvent_PropertiesEnum_valueOfWithNSString_(name);
}

RtdcCoreEventAuthenticationEvent_PropertiesEnum *RtdcCoreEventAuthenticationEvent_PropertiesEnum_valueOfWithNSString_(NSString *name) {
  RtdcCoreEventAuthenticationEvent_PropertiesEnum_initialize();
  for (int i = 0; i < 2; i++) {
    RtdcCoreEventAuthenticationEvent_PropertiesEnum *e = RtdcCoreEventAuthenticationEvent_PropertiesEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [RtdcCoreEventAuthenticationEvent_PropertiesEnum class]) {
    RtdcCoreEventAuthenticationEvent_PropertiesEnum_user = new_RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(@"user", 0);
    RtdcCoreEventAuthenticationEvent_PropertiesEnum_authenticationToken = new_RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(@"authenticationToken", 1);
    J2OBJC_SET_INITIALIZED(RtdcCoreEventAuthenticationEvent_PropertiesEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "user", "user", 0x4019, "Lrtdc.core.event.AuthenticationEvent$Properties;", &RtdcCoreEventAuthenticationEvent_PropertiesEnum_user, NULL, .constantValue.asLong = 0 },
    { "authenticationToken", "authenticationToken", 0x4019, "Lrtdc.core.event.AuthenticationEvent$Properties;", &RtdcCoreEventAuthenticationEvent_PropertiesEnum_authenticationToken, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lrtdc.core.event.AuthenticationEvent$Properties;"};
  static const J2ObjcClassInfo _RtdcCoreEventAuthenticationEvent_PropertiesEnum = { 2, "Properties", "rtdc.core.event", "AuthenticationEvent", 0x4019, 0, NULL, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lrtdc/core/event/AuthenticationEvent$Properties;>;Lrtdc/core/model/ObjectProperty<Lrtdc/core/event/AuthenticationEvent;>;" };
  return &_RtdcCoreEventAuthenticationEvent_PropertiesEnum;
}

@end

void RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(RtdcCoreEventAuthenticationEvent_PropertiesEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

RtdcCoreEventAuthenticationEvent_PropertiesEnum *new_RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  RtdcCoreEventAuthenticationEvent_PropertiesEnum *self = [RtdcCoreEventAuthenticationEvent_PropertiesEnum alloc];
  RtdcCoreEventAuthenticationEvent_PropertiesEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RtdcCoreEventAuthenticationEvent_PropertiesEnum)

@implementation RtdcCoreEventAuthenticationEvent_Handler

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onAuthenticateWithRtdcCoreEventAuthenticationEvent:", "onAuthenticate", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreEventAuthenticationEvent_Handler = { 2, "Handler", "rtdc.core.event", "AuthenticationEvent", 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RtdcCoreEventAuthenticationEvent_Handler;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RtdcCoreEventAuthenticationEvent_Handler)
