//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/Bootstrapper.java
//

#include "Bootstrapper.h"
#include "Factory.h"
#include "IOSClass.h"

@implementation RtdcCoreBootstrapper

id<ImplFactory> RtdcCoreBootstrapper_FACTORY_;
NSString * RtdcCoreBootstrapper_AUTHENTICATION_TOKEN_;

+ (void)initialize__WithImplFactory:(id<ImplFactory>)factory {
  RtdcCoreBootstrapper_initialize__WithImplFactory_(factory);
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initialize__WithImplFactory:", "initialize", "V", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "FACTORY_", NULL, 0x9, "Lrtdc.core.impl.Factory;", &RtdcCoreBootstrapper_FACTORY_,  },
    { "AUTHENTICATION_TOKEN_", NULL, 0x9, "Ljava.lang.String;", &RtdcCoreBootstrapper_AUTHENTICATION_TOKEN_,  },
  };
  static const J2ObjcClassInfo _RtdcCoreBootstrapper = { "Bootstrapper", "rtdc.core", NULL, 0x1, 2, methods, 2, fields, 0, NULL};
  return &_RtdcCoreBootstrapper;
}

@end

void RtdcCoreBootstrapper_initialize__WithImplFactory_(id<ImplFactory> factory) {
  RtdcCoreBootstrapper_init();
  JreStrongAssign(&RtdcCoreBootstrapper_FACTORY_, nil, factory);
}
