//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/controller/BootstrapperController.java
//

#ifndef _ControllerBootstrapperController_H_
#define _ControllerBootstrapperController_H_

@protocol RtdcCoreViewBootstrapperView;

#import "JreEmulation.h"

@interface ControllerBootstrapperController : NSObject {
 @public
  id<RtdcCoreViewBootstrapperView> view_;
}

- (instancetype)initWithRtdcCoreViewBootstrapperView:(id<RtdcCoreViewBootstrapperView>)view;

- (void)init__ OBJC_METHOD_FAMILY_NONE;

- (void)dealloc;

- (void)copyAllFieldsTo:(ControllerBootstrapperController *)other;

@end

__attribute__((always_inline)) inline void ControllerBootstrapperController_init() {}

J2OBJC_FIELD_SETTER(ControllerBootstrapperController, view_, id<RtdcCoreViewBootstrapperView>)

typedef ControllerBootstrapperController RtdcCoreControllerBootstrapperController;

#endif // _ControllerBootstrapperController_H_
