//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/Bootstrapper.java
//

#ifndef _Bootstrapper_H_
#define _Bootstrapper_H_

#include "J2ObjC_header.h"

@protocol ImplFactory;

@interface RtdcCoreBootstrapper : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initialize__WithImplFactory:(id<ImplFactory>)factory OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_STATIC_INIT(RtdcCoreBootstrapper)

FOUNDATION_EXPORT id<ImplFactory> RtdcCoreBootstrapper_FACTORY_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreBootstrapper, FACTORY_, id<ImplFactory>)
J2OBJC_STATIC_FIELD_SETTER(RtdcCoreBootstrapper, FACTORY_, id<ImplFactory>)

FOUNDATION_EXPORT NSString *RtdcCoreBootstrapper_AUTHENTICATION_TOKEN_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreBootstrapper, AUTHENTICATION_TOKEN_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(RtdcCoreBootstrapper, AUTHENTICATION_TOKEN_, NSString *)

FOUNDATION_EXPORT void RtdcCoreBootstrapper_initialize__WithImplFactory_(id<ImplFactory> factory);

FOUNDATION_EXPORT void RtdcCoreBootstrapper_init(RtdcCoreBootstrapper *self);

FOUNDATION_EXPORT RtdcCoreBootstrapper *new_RtdcCoreBootstrapper_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RtdcCoreBootstrapper)

#endif // _Bootstrapper_H_
