//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\view\BootstrapperView.java
//

#include "BootstrapperView.h"

@interface RtdcCoreViewBootstrapperView : NSObject
@end

@implementation RtdcCoreViewBootstrapperView

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "hasAuthenticationToken", NULL, "Z", 0x401, NULL },
    { "getAuthenticationToken", NULL, "Ljava.lang.String;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreViewBootstrapperView = { "BootstrapperView", "rtdc.core.view", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_RtdcCoreViewBootstrapperView;
}

@end

