//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/view/CapacityOverviewView.java
//

#ifndef _CapacityOverviewView_H_
#define _CapacityOverviewView_H_

#include "J2ObjC_header.h"
#include "View.h"

@protocol JavaUtilList;

@protocol ViewCapacityOverviewView < ViewView, NSObject, JavaObject >

- (void)setUnitsWithJavaUtilList:(id<JavaUtilList>)units;

@end

J2OBJC_EMPTY_STATIC_INIT(ViewCapacityOverviewView)

J2OBJC_TYPE_LITERAL_HEADER(ViewCapacityOverviewView)

#define RtdcCoreViewCapacityOverviewView ViewCapacityOverviewView

#endif // _CapacityOverviewView_H_
