//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/view/Dialog.java
//

#ifndef _Dialog_H_
#define _Dialog_H_

#include "J2ObjC_header.h"
#include "View.h"

@protocol ViewDialog < ViewView, NSObject, JavaObject >

- (void)closeDialog;

@end

J2OBJC_EMPTY_STATIC_INIT(ViewDialog)

J2OBJC_TYPE_LITERAL_HEADER(ViewDialog)

#define RtdcCoreViewDialog ViewDialog

#endif // _Dialog_H_
