//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/event/EventHandler.java
//

#ifndef _EventHandler_H_
#define _EventHandler_H_

#include "J2ObjC_header.h"

@protocol EventEventHandler < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(EventEventHandler)

J2OBJC_TYPE_LITERAL_HEADER(EventEventHandler)

#define RtdcCoreEventEventHandler EventEventHandler

#endif // _EventHandler_H_
