//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/event/FetchUsersEvent.java
//

#ifndef _FetchUsersEvent_H_
#define _FetchUsersEvent_H_

#include "Event.h"
#include "EventHandler.h"
#include "J2ObjC_header.h"
#include "ObjectProperty.h"
#include "java/lang/Enum.h"

@class ComGoogleCommonCollectImmutableSet;
@class IOSObjectArray;
@class JSONJSONObject;
@class RtdcCoreEventEventType;
@protocol JavaLangIterable;
@protocol ModelObjectProperty;

@interface RtdcCoreEventFetchUsersEvent : RtdcCoreEventEvent

#pragma mark Public

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)units;

- (instancetype)initWithJSONJSONObject:(JSONJSONObject *)object;

- (void)fire;

- (IOSObjectArray *)getProperties;

- (NSString *)getType;

- (ComGoogleCommonCollectImmutableSet *)getUsers;

- (id)getValueWithModelObjectProperty:(id<ModelObjectProperty>)property;

@end

J2OBJC_STATIC_INIT(RtdcCoreEventFetchUsersEvent)

FOUNDATION_EXPORT RtdcCoreEventEventType *RtdcCoreEventFetchUsersEvent_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreEventFetchUsersEvent, TYPE_, RtdcCoreEventEventType *)

FOUNDATION_EXPORT void RtdcCoreEventFetchUsersEvent_initWithJavaLangIterable_(RtdcCoreEventFetchUsersEvent *self, id<JavaLangIterable> units);

FOUNDATION_EXPORT RtdcCoreEventFetchUsersEvent *new_RtdcCoreEventFetchUsersEvent_initWithJavaLangIterable_(id<JavaLangIterable> units) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void RtdcCoreEventFetchUsersEvent_initWithJSONJSONObject_(RtdcCoreEventFetchUsersEvent *self, JSONJSONObject *object);

FOUNDATION_EXPORT RtdcCoreEventFetchUsersEvent *new_RtdcCoreEventFetchUsersEvent_initWithJSONJSONObject_(JSONJSONObject *object) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RtdcCoreEventFetchUsersEvent)

@protocol RtdcCoreEventFetchUsersEvent_Handler < RtdcCoreEventEventHandler, NSObject, JavaObject >

- (void)onUsersFetchedWithRtdcCoreEventFetchUsersEvent:(RtdcCoreEventFetchUsersEvent *)event;

@end

J2OBJC_EMPTY_STATIC_INIT(RtdcCoreEventFetchUsersEvent_Handler)

J2OBJC_TYPE_LITERAL_HEADER(RtdcCoreEventFetchUsersEvent_Handler)

typedef NS_ENUM(NSUInteger, RtdcCoreEventFetchUsersEvent_Properties) {
  RtdcCoreEventFetchUsersEvent_Properties_users = 0,
};

@interface RtdcCoreEventFetchUsersEvent_PropertiesEnum : JavaLangEnum < NSCopying, ModelObjectProperty >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *RtdcCoreEventFetchUsersEvent_PropertiesEnum_values();

+ (RtdcCoreEventFetchUsersEvent_PropertiesEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT RtdcCoreEventFetchUsersEvent_PropertiesEnum *RtdcCoreEventFetchUsersEvent_PropertiesEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(RtdcCoreEventFetchUsersEvent_PropertiesEnum)

FOUNDATION_EXPORT RtdcCoreEventFetchUsersEvent_PropertiesEnum *RtdcCoreEventFetchUsersEvent_PropertiesEnum_values_[];

#define RtdcCoreEventFetchUsersEvent_PropertiesEnum_users RtdcCoreEventFetchUsersEvent_PropertiesEnum_values_[RtdcCoreEventFetchUsersEvent_Properties_users]
J2OBJC_ENUM_CONSTANT_GETTER(RtdcCoreEventFetchUsersEvent_PropertiesEnum, users)

J2OBJC_TYPE_LITERAL_HEADER(RtdcCoreEventFetchUsersEvent_PropertiesEnum)

#endif // _FetchUsersEvent_H_
