//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/impl/HttpResponse.java
//

#include "HttpResponse.h"

@interface ImplHttpResponse : NSObject
@end

@implementation ImplHttpResponse

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getStatusCode", NULL, "I", 0x401, NULL },
    { "getContent", NULL, "Ljava.lang.String;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ImplHttpResponse = { "HttpResponse", "rtdc.core.impl", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ImplHttpResponse;
}

@end

