//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/impl/HttpRequest.java
//

#ifndef _ImplHttpRequest_H_
#define _ImplHttpRequest_H_

@protocol ServiceAsyncCallback;

#import "JreEmulation.h"
#include "java/lang/Enum.h"

@protocol ImplHttpRequest < NSObject, JavaObject >

- (void)addParameterWithNSString:(NSString *)parameter
                    withNSString:(NSString *)data;

- (void)setHeaderWithNSString:(NSString *)name
                 withNSString:(NSString *)value;

- (void)executeWithServiceAsyncCallback:(id<ServiceAsyncCallback>)response;

@end

__attribute__((always_inline)) inline void ImplHttpRequest_init() {}

#define RtdcCoreImplHttpRequest ImplHttpRequest

typedef NS_ENUM(NSUInteger, ImplHttpRequest_RequestMethod) {
  ImplHttpRequest_RequestMethod_GET = 0,
  ImplHttpRequest_RequestMethod_PUT = 1,
  ImplHttpRequest_RequestMethod_DELETE = 2,
  ImplHttpRequest_RequestMethod_POST = 3,
};

@interface ImplHttpRequest_RequestMethodEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ImplHttpRequest_RequestMethodEnum_values();

+ (ImplHttpRequest_RequestMethodEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ImplHttpRequest_RequestMethodEnum *ImplHttpRequest_RequestMethodEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ImplHttpRequest_RequestMethodEnum_initialized;
J2OBJC_STATIC_INIT(ImplHttpRequest_RequestMethodEnum)

FOUNDATION_EXPORT ImplHttpRequest_RequestMethodEnum *ImplHttpRequest_RequestMethodEnum_values_[];

#define ImplHttpRequest_RequestMethodEnum_GET ImplHttpRequest_RequestMethodEnum_values_[ImplHttpRequest_RequestMethod_GET]
J2OBJC_STATIC_FIELD_GETTER(ImplHttpRequest_RequestMethodEnum, GET, ImplHttpRequest_RequestMethodEnum *)

#define ImplHttpRequest_RequestMethodEnum_PUT ImplHttpRequest_RequestMethodEnum_values_[ImplHttpRequest_RequestMethod_PUT]
J2OBJC_STATIC_FIELD_GETTER(ImplHttpRequest_RequestMethodEnum, PUT, ImplHttpRequest_RequestMethodEnum *)

#define ImplHttpRequest_RequestMethodEnum_DELETE ImplHttpRequest_RequestMethodEnum_values_[ImplHttpRequest_RequestMethod_DELETE]
J2OBJC_STATIC_FIELD_GETTER(ImplHttpRequest_RequestMethodEnum, DELETE, ImplHttpRequest_RequestMethodEnum *)

#define ImplHttpRequest_RequestMethodEnum_POST ImplHttpRequest_RequestMethodEnum_values_[ImplHttpRequest_RequestMethod_POST]
J2OBJC_STATIC_FIELD_GETTER(ImplHttpRequest_RequestMethodEnum, POST, ImplHttpRequest_RequestMethodEnum *)

#endif // _ImplHttpRequest_H_
