//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/service/HttpHeadersName.java
//

#ifndef _HttpHeadersName_H_
#define _HttpHeadersName_H_

#include "J2ObjC_header.h"

@interface ServiceHttpHeadersName : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ServiceHttpHeadersName)

FOUNDATION_EXPORT NSString *ServiceHttpHeadersName_AUTH_TOKEN_;
J2OBJC_STATIC_FIELD_GETTER(ServiceHttpHeadersName, AUTH_TOKEN_, NSString *)

FOUNDATION_EXPORT void ServiceHttpHeadersName_init(ServiceHttpHeadersName *self);

FOUNDATION_EXPORT ServiceHttpHeadersName *new_ServiceHttpHeadersName_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ServiceHttpHeadersName)

@compatibility_alias RtdcCoreServiceHttpHeadersName ServiceHttpHeadersName;

#endif // _HttpHeadersName_H_
