//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/impl/HttpResponse.java
//

#ifndef _ImplHttpResponse_H_
#define _ImplHttpResponse_H_

#import "JreEmulation.h"

@protocol ImplHttpResponse < NSObject, JavaObject >

- (jint)getStatusCode;

- (NSString *)getContent;

@end

__attribute__((always_inline)) inline void ImplHttpResponse_init() {}

#define RtdcCoreImplHttpResponse ImplHttpResponse

#endif // _ImplHttpResponse_H_
