//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\json\JSONString.java
//

#ifndef _RtdcCoreJsonJSONString_H_
#define _RtdcCoreJsonJSONString_H_

#import "JreEmulation.h"

@protocol RtdcCoreJsonJSONString < NSObject, JavaObject >

- (NSString *)toJSONString;

@end

__attribute__((always_inline)) inline void RtdcCoreJsonJSONString_init() {}

#endif // _RtdcCoreJsonJSONString_H_
