//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/model/JsonTransmissionWrapper.java
//

#ifndef _ModelJsonTransmissionWrapper_H_
#define _ModelJsonTransmissionWrapper_H_

@class JSONJSONArray;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "JSONObject.h"

@interface ModelJsonTransmissionWrapper : JSONJSONObject {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)json;

- (instancetype)initWithJSONJSONObject:(JSONJSONObject *)element;

- (instancetype)initWithJSONJSONArray:(JSONJSONArray *)element;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)exception;

- (JSONJSONObject *)getData;

- (JSONJSONArray *)getDataAsJSONArray;

- (void)setDataWithJSONJSONObject:(JSONJSONObject *)data;

- (void)setDataWithJSONJSONArray:(JSONJSONArray *)data;

- (void)setNull;

- (NSString *)getStatus;

- (void)setStatusWithNSString:(NSString *)status;

- (NSString *)getDescription;

- (void)setDescriptionWithNSString:(NSString *)description_;

@end

__attribute__((always_inline)) inline void ModelJsonTransmissionWrapper_init() {}

typedef ModelJsonTransmissionWrapper RtdcCoreModelJsonTransmissionWrapper;

#endif // _ModelJsonTransmissionWrapper_H_
