//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\json\JSONException.java
//

#ifndef _RtdcCoreJsonJSONException_H_
#define _RtdcCoreJsonJSONException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

@interface RtdcCoreJsonJSONException : JavaLangRuntimeException {
 @public
  JavaLangThrowable *cause_JSONException_;
}

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)t;

- (JavaLangThrowable *)getCause;

- (void)dealloc;

- (void)copyAllFieldsTo:(RtdcCoreJsonJSONException *)other;

@end

__attribute__((always_inline)) inline void RtdcCoreJsonJSONException_init() {}

J2OBJC_FIELD_SETTER(RtdcCoreJsonJSONException, cause_JSONException_, JavaLangThrowable *)

#endif // _RtdcCoreJsonJSONException_H_
