//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/json/JSONStringer.java
//

#include "JSONStringer.h"
#include "StringWriter.h"
#include "java/io/Writer.h"

@implementation JSONJSONStringer

- (instancetype)init {
  return [super initWithJavaIoWriter:[[[JSONStringWriter alloc] init] autorelease]];
}

- (NSString *)description {
  return self->mode_ == 'd' ? [((JavaIoWriter *) nil_chk(self->writer_)) description] : nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JSONStringer", NULL, 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
  };
  static const J2ObjcClassInfo _JSONJSONStringer = { "JSONStringer", "rtdc.core.json", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_JSONJSONStringer;
}

@end
