//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\json\JSONWriter.java
//

#ifndef _RtdcCoreJsonJSONWriter_H_
#define _RtdcCoreJsonJSONWriter_H_

@class IOSCharArray;
@class JavaIoWriter;

#import "JreEmulation.h"

#define RtdcCoreJsonJSONWriter_maxdepth 20

@interface RtdcCoreJsonJSONWriter : NSObject {
 @public
  jboolean comma_;
  jchar mode_;
  IOSCharArray *stack_;
  jint top_;
  JavaIoWriter *writer_;
}

- (instancetype)initWithJavaIoWriter:(JavaIoWriter *)w;

- (RtdcCoreJsonJSONWriter *)appendWithNSString:(NSString *)s;

- (RtdcCoreJsonJSONWriter *)array;

- (RtdcCoreJsonJSONWriter *)endWithChar:(jchar)m
                               withChar:(jchar)c;

- (RtdcCoreJsonJSONWriter *)endArray;

- (RtdcCoreJsonJSONWriter *)endObject;

- (RtdcCoreJsonJSONWriter *)keyWithNSString:(NSString *)s;

- (RtdcCoreJsonJSONWriter *)object;

- (void)popWithChar:(jchar)c;

- (void)pushWithChar:(jchar)c;

- (RtdcCoreJsonJSONWriter *)valueWithBoolean:(jboolean)b;

- (RtdcCoreJsonJSONWriter *)valueWithLong:(jlong)l;

- (RtdcCoreJsonJSONWriter *)valueWithId:(id)o;

- (void)dealloc;

- (void)copyAllFieldsTo:(RtdcCoreJsonJSONWriter *)other;

@end

__attribute__((always_inline)) inline void RtdcCoreJsonJSONWriter_init() {}

J2OBJC_FIELD_SETTER(RtdcCoreJsonJSONWriter, stack_, IOSCharArray *)
J2OBJC_FIELD_SETTER(RtdcCoreJsonJSONWriter, writer_, JavaIoWriter *)

J2OBJC_STATIC_FIELD_GETTER(RtdcCoreJsonJSONWriter, maxdepth, jint)

#endif // _RtdcCoreJsonJSONWriter_H_
