//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/json/JSONException.java
//

#ifndef _JSONException_H_
#define _JSONException_H_

#include "J2ObjC_header.h"
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface JSONJSONException : JavaLangRuntimeException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)t;

- (JavaLangThrowable *)getCause;

@end

J2OBJC_EMPTY_STATIC_INIT(JSONJSONException)

FOUNDATION_EXPORT void JSONJSONException_initWithNSString_(JSONJSONException *self, NSString *message);

FOUNDATION_EXPORT JSONJSONException *new_JSONJSONException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JSONJSONException_initWithJavaLangThrowable_(JSONJSONException *self, JavaLangThrowable *t);

FOUNDATION_EXPORT JSONJSONException *new_JSONJSONException_initWithJavaLangThrowable_(JavaLangThrowable *t) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JSONJSONException)

@compatibility_alias RtdcCoreJsonJSONException JSONJSONException;

#endif // _JSONException_H_
