//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/json/JSONString.java
//

#ifndef _JSONString_H_
#define _JSONString_H_

#include "J2ObjC_header.h"

@protocol JSONJSONString < NSObject, JavaObject >

- (NSString *)toJSONString;

@end

J2OBJC_EMPTY_STATIC_INIT(JSONJSONString)

J2OBJC_TYPE_LITERAL_HEADER(JSONJSONString)

#define RtdcCoreJsonJSONString JSONJSONString

#endif // _JSONString_H_
