//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\json\JSONString.java
//

#include "JSONString.h"

@interface RtdcCoreJsonJSONString : NSObject
@end

@implementation RtdcCoreJsonJSONString

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "toJSONString", NULL, "Ljava.lang.String;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreJsonJSONString = { "JSONString", "rtdc.core.json", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_RtdcCoreJsonJSONString;
}

@end

