//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/event/MessageSavedEvent.java
//

#include "Event.h"
#include "EventType.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JSONObject.h"
#include "MessageSavedEvent.h"
#include "ObjectProperty.h"
#include "com/google/common/collect/ImmutableSet.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/util/Date.h"

@interface EventMessageSavedEvent () {
 @public
  JavaUtilDate *timeSent_;
  jint messageId_;
}

@end

J2OBJC_FIELD_SETTER(EventMessageSavedEvent, timeSent_, JavaUtilDate *)

@interface EventMessageSavedEvent_Handler : NSObject

@end

__attribute__((unused)) static void EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(EventMessageSavedEvent_PropertiesEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static EventMessageSavedEvent_PropertiesEnum *new_EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_INITIALIZED_DEFN(EventMessageSavedEvent)

EventEventType *EventMessageSavedEvent_TYPE_;

@implementation EventMessageSavedEvent

+ (EventEventType *)TYPE {
  return EventMessageSavedEvent_TYPE_;
}

- (instancetype)initWithInt:(jint)messageId
           withJavaUtilDate:(JavaUtilDate *)timeSent {
  EventMessageSavedEvent_initWithInt_withJavaUtilDate_(self, messageId, timeSent);
  return self;
}

- (instancetype)initWithJsonJSONObject:(JsonJSONObject *)object {
  EventMessageSavedEvent_initWithJsonJSONObject_(self, object);
  return self;
}

- (jint)getMessageId {
  return messageId_;
}

- (JavaUtilDate *)getTimeSent {
  return timeSent_;
}

- (void)fire {
  for (id<EventMessageSavedEvent_Handler> __strong handler in nil_chk([self getHandlersWithEventEventType:EventMessageSavedEvent_TYPE_])) [((id<EventMessageSavedEvent_Handler>) nil_chk(handler)) onMessageSavedWithEventMessageSavedEvent:self];
}

- (IOSObjectArray *)getProperties {
  return EventMessageSavedEvent_PropertiesEnum_values();
}

- (NSString *)getType {
  return [((EventEventType *) nil_chk(EventMessageSavedEvent_TYPE_)) getName];
}

- (id)getValueWithModelObjectProperty:(id<ModelObjectProperty>)property {
  switch ([(EventMessageSavedEvent_PropertiesEnum *) check_class_cast(property, [EventMessageSavedEvent_PropertiesEnum class]) ordinal]) {
    case EventMessageSavedEvent_Properties_messageId:
    return JavaLangInteger_valueOfWithInt_(messageId_);
    case EventMessageSavedEvent_Properties_timeSent:
    return timeSent_;
  }
  return nil;
}

+ (void)initialize {
  if (self == [EventMessageSavedEvent class]) {
    EventMessageSavedEvent_TYPE_ = new_EventEventType_initWithNSString_(@"messageSavedEvent");
    J2OBJC_SET_INITIALIZED(EventMessageSavedEvent)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:withJavaUtilDate:", "MessageSavedEvent", NULL, 0x1, NULL, NULL },
    { "initWithJsonJSONObject:", "MessageSavedEvent", NULL, 0x1, NULL, NULL },
    { "getMessageId", NULL, "I", 0x1, NULL, NULL },
    { "getTimeSent", NULL, "Ljava.util.Date;", 0x1, NULL, NULL },
    { "fire", NULL, "V", 0x1, NULL, NULL },
    { "getProperties", NULL, "[Lrtdc.core.model.ObjectProperty;", 0x1, NULL, NULL },
    { "getType", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getValueWithModelObjectProperty:", "getValue", "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TYPE_", NULL, 0x19, "Lrtdc.core.event.EventType;", &EventMessageSavedEvent_TYPE_, "Lrtdc/core/event/EventType<Lrtdc/core/event/MessageSavedEvent$Handler;>;", .constantValue.asLong = 0 },
    { "timeSent_", NULL, 0x12, "Ljava.util.Date;", NULL, NULL, .constantValue.asLong = 0 },
    { "messageId_", NULL, 0x12, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lrtdc.core.event.ActionCompleteEvent$Handler;"};
  static const char *inner_classes[] = {"Lrtdc.core.event.MessageSavedEvent$Handler;", "Lrtdc.core.event.MessageSavedEvent$Properties;"};
  static const J2ObjcClassInfo _EventMessageSavedEvent = { 2, "MessageSavedEvent", "rtdc.core.event", NULL, 0x1, 8, methods, 3, fields, 1, superclass_type_args, 2, inner_classes, NULL, "Lrtdc/core/event/Event<Lrtdc/core/event/ActionCompleteEvent$Handler;>;" };
  return &_EventMessageSavedEvent;
}

@end

void EventMessageSavedEvent_initWithInt_withJavaUtilDate_(EventMessageSavedEvent *self, jint messageId, JavaUtilDate *timeSent) {
  (void) EventEvent_init(self);
  self->messageId_ = messageId;
  self->timeSent_ = timeSent;
}

EventMessageSavedEvent *new_EventMessageSavedEvent_initWithInt_withJavaUtilDate_(jint messageId, JavaUtilDate *timeSent) {
  EventMessageSavedEvent *self = [EventMessageSavedEvent alloc];
  EventMessageSavedEvent_initWithInt_withJavaUtilDate_(self, messageId, timeSent);
  return self;
}

void EventMessageSavedEvent_initWithJsonJSONObject_(EventMessageSavedEvent *self, JsonJSONObject *object) {
  (void) EventEvent_init(self);
  self->messageId_ = [((JsonJSONObject *) nil_chk(object)) getIntWithNSString:[((EventMessageSavedEvent_PropertiesEnum *) nil_chk(JreLoadStatic(EventMessageSavedEvent_PropertiesEnum, messageId))) name]];
  if ([[object getWithNSString:[((EventMessageSavedEvent_PropertiesEnum *) nil_chk(JreLoadStatic(EventMessageSavedEvent_PropertiesEnum, timeSent))) name]] isKindOfClass:[JavaUtilDate class]]) self->timeSent_ = (JavaUtilDate *) check_class_cast([object getWithNSString:[JreLoadStatic(EventMessageSavedEvent_PropertiesEnum, timeSent) name]], [JavaUtilDate class]);
  else self->timeSent_ = new_JavaUtilDate_initWithLong_([((JavaLangLong *) nil_chk((JavaLangLong *) check_class_cast([object getWithNSString:[JreLoadStatic(EventMessageSavedEvent_PropertiesEnum, timeSent) name]], [JavaLangLong class]))) longLongValue]);
}

EventMessageSavedEvent *new_EventMessageSavedEvent_initWithJsonJSONObject_(JsonJSONObject *object) {
  EventMessageSavedEvent *self = [EventMessageSavedEvent alloc];
  EventMessageSavedEvent_initWithJsonJSONObject_(self, object);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EventMessageSavedEvent)

@implementation EventMessageSavedEvent_Handler

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onMessageSavedWithEventMessageSavedEvent:", "onMessageSaved", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _EventMessageSavedEvent_Handler = { 2, "Handler", "rtdc.core.event", "MessageSavedEvent", 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_EventMessageSavedEvent_Handler;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EventMessageSavedEvent_Handler)

J2OBJC_INITIALIZED_DEFN(EventMessageSavedEvent_PropertiesEnum)

EventMessageSavedEvent_PropertiesEnum *EventMessageSavedEvent_PropertiesEnum_values_[2];

@implementation EventMessageSavedEvent_PropertiesEnum

+ (EventMessageSavedEvent_PropertiesEnum *)messageId {
  return EventMessageSavedEvent_PropertiesEnum_messageId;
}

+ (EventMessageSavedEvent_PropertiesEnum *)timeSent {
  return EventMessageSavedEvent_PropertiesEnum_timeSent;
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *EventMessageSavedEvent_PropertiesEnum_values() {
  EventMessageSavedEvent_PropertiesEnum_initialize();
  return [IOSObjectArray arrayWithObjects:EventMessageSavedEvent_PropertiesEnum_values_ count:2 type:EventMessageSavedEvent_PropertiesEnum_class_()];
}

+ (IOSObjectArray *)values {
  return EventMessageSavedEvent_PropertiesEnum_values();
}

+ (EventMessageSavedEvent_PropertiesEnum *)valueOfWithNSString:(NSString *)name {
  return EventMessageSavedEvent_PropertiesEnum_valueOfWithNSString_(name);
}

EventMessageSavedEvent_PropertiesEnum *EventMessageSavedEvent_PropertiesEnum_valueOfWithNSString_(NSString *name) {
  EventMessageSavedEvent_PropertiesEnum_initialize();
  for (int i = 0; i < 2; i++) {
    EventMessageSavedEvent_PropertiesEnum *e = EventMessageSavedEvent_PropertiesEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [EventMessageSavedEvent_PropertiesEnum class]) {
    EventMessageSavedEvent_PropertiesEnum_messageId = new_EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(@"messageId", 0);
    EventMessageSavedEvent_PropertiesEnum_timeSent = new_EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(@"timeSent", 1);
    J2OBJC_SET_INITIALIZED(EventMessageSavedEvent_PropertiesEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "messageId", "messageId", 0x4019, "Lrtdc.core.event.MessageSavedEvent$Properties;", &EventMessageSavedEvent_PropertiesEnum_messageId, NULL, .constantValue.asLong = 0 },
    { "timeSent", "timeSent", 0x4019, "Lrtdc.core.event.MessageSavedEvent$Properties;", &EventMessageSavedEvent_PropertiesEnum_timeSent, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lrtdc.core.event.MessageSavedEvent$Properties;"};
  static const J2ObjcClassInfo _EventMessageSavedEvent_PropertiesEnum = { 2, "Properties", "rtdc.core.event", "MessageSavedEvent", 0x4019, 0, NULL, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lrtdc/core/event/MessageSavedEvent$Properties;>;Lrtdc/core/model/ObjectProperty<Lrtdc/core/event/ActionCompleteEvent;>;" };
  return &_EventMessageSavedEvent_PropertiesEnum;
}

@end

void EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(EventMessageSavedEvent_PropertiesEnum *self, NSString *__name, jint __ordinal) {
  (void) JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

EventMessageSavedEvent_PropertiesEnum *new_EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  EventMessageSavedEvent_PropertiesEnum *self = [EventMessageSavedEvent_PropertiesEnum alloc];
  EventMessageSavedEvent_PropertiesEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EventMessageSavedEvent_PropertiesEnum)
