//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/Session.java
//

#ifndef _Session_H_
#define _Session_H_

#include "J2ObjC_header.h"

@class ModelUser;

@interface RtdcCoreSession : NSObject

#pragma mark Public

- (instancetype)initWithModelUser:(ModelUser *)user;

+ (RtdcCoreSession *)getCurrentSession;

- (ModelUser *)getUser;

+ (void)setCurrentSessionWithRtdcCoreSession:(RtdcCoreSession *)session;

@end

J2OBJC_EMPTY_STATIC_INIT(RtdcCoreSession)

FOUNDATION_EXPORT void RtdcCoreSession_initWithModelUser_(RtdcCoreSession *self, ModelUser *user);

FOUNDATION_EXPORT RtdcCoreSession *new_RtdcCoreSession_initWithModelUser_(ModelUser *user) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void RtdcCoreSession_setCurrentSessionWithRtdcCoreSession_(RtdcCoreSession *session);

FOUNDATION_EXPORT RtdcCoreSession *RtdcCoreSession_getCurrentSession();

J2OBJC_TYPE_LITERAL_HEADER(RtdcCoreSession)

#endif // _Session_H_
