//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\exception\SessionExpiredException.java
//

#include "SessionExpiredException.h"

@implementation RtdcCoreExceptionSessionExpiredException

- (instancetype)initWithNSString:(NSString *)message {
  return [super initWithNSString:message];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "SessionExpiredException", NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreExceptionSessionExpiredException = { "SessionExpiredException", "rtdc.core.exception", NULL, 0x1, 1, methods, 0, NULL, 0, NULL};
  return &_RtdcCoreExceptionSessionExpiredException;
}

@end
