//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/util/Stringifier.java
//

#include "J2ObjC_source.h"
#include "Stringifier.h"

@interface UtilStringifier : NSObject

@end

@implementation UtilStringifier

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "toStringWithId:", "toString", "Ljava.lang.String;", 0x401, NULL, "(TT;)Ljava/lang/String;" },
  };
  static const J2ObjcClassInfo _UtilStringifier = { 2, "Stringifier", "rtdc.core.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_UtilStringifier;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(UtilStringifier)
