//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/view/UnitListView.java
//

#include "J2ObjC_source.h"
#include "UnitListView.h"
#include "java/util/List.h"

@interface ViewUnitListView : NSObject

@end

@implementation ViewUnitListView

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setUnitsWithJavaUtilList:", "setUnits", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ViewUnitListView = { 2, "UnitListView", "rtdc.core.view", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ViewUnitListView;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ViewUnitListView)
