//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/controller/UnitListController.java
//

#include "IOSClass.h"
#include "Service.h"
#include "Unit.h"
#include "UnitListController.h"
#include "UnitListView.h"
#include "java/util/List.h"

@implementation ControllerUnitListController

- (instancetype)initWithRtdcCoreViewUnitListView:(id<RtdcCoreViewUnitListView>)view {
  if (self = [super init]) {
    ControllerUnitListController_set_view_(self, view);
    ServiceService_getUnitsWithServiceAsyncCallback_([[[ControllerUnitListController_$1 alloc] initWithControllerUnitListController:self] autorelease]);
  }
  return self;
}

- (void)onClickUserWithModelUnit:(ModelUnit *)unit {
}

- (void)onClickNewUser {
}

- (void)dealloc {
  ControllerUnitListController_set_view_(self, nil);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ControllerUnitListController *)other {
  [super copyAllFieldsTo:other];
  ControllerUnitListController_set_view_(other, view_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithRtdcCoreViewUnitListView:", "UnitListController", NULL, 0x1, NULL },
    { "onClickUserWithModelUnit:", "onClickUser", "V", 0x1, NULL },
    { "onClickNewUser", NULL, "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "view_", NULL, 0x2, "Lrtdc.core.view.UnitListView;", NULL,  },
  };
  static const J2ObjcClassInfo _ControllerUnitListController = { "UnitListController", "rtdc.core.controller", NULL, 0x1, 3, methods, 1, fields, 0, NULL};
  return &_ControllerUnitListController;
}

@end

@implementation ControllerUnitListController_$1

- (void)onSuccessWithId:(id<JavaUtilList>)units {
  [((id<RtdcCoreViewUnitListView>) nil_chk(this$0_->view_)) setUnitsWithJavaUtilList:units];
}

- (void)onErrorWithNSString:(NSString *)message {
  [((id<RtdcCoreViewUnitListView>) nil_chk(this$0_->view_)) displayErrorWithNSString:@"Error" withNSString:message];
}

- (instancetype)initWithControllerUnitListController:(ControllerUnitListController *)outer$ {
  ControllerUnitListController_$1_set_this$0_(self, outer$);
  return [super init];
}

- (void)dealloc {
  ControllerUnitListController_$1_set_this$0_(self, nil);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ControllerUnitListController_$1 *)other {
  [super copyAllFieldsTo:other];
  ControllerUnitListController_$1_set_this$0_(other, this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onSuccessWithJavaUtilList:", "onSuccess", "V", 0x1, NULL },
    { "onErrorWithNSString:", "onError", "V", 0x1, NULL },
    { "initWithControllerUnitListController:", "init", NULL, 0x0, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lrtdc.core.controller.UnitListController;", NULL,  },
  };
  static const J2ObjcClassInfo _ControllerUnitListController_$1 = { "$1", "rtdc.core.controller", "UnitListController", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ControllerUnitListController_$1;
}

@end
