//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\exception\UsernamePasswordMismatchException.java
//

#ifndef _RtdcCoreExceptionUsernamePasswordMismatchException_H_
#define _RtdcCoreExceptionUsernamePasswordMismatchException_H_

#import "JreEmulation.h"
#include "ApiException.h"

@interface RtdcCoreExceptionUsernamePasswordMismatchException : RtdcCoreExceptionApiException {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void RtdcCoreExceptionUsernamePasswordMismatchException_init() {}

#endif // _RtdcCoreExceptionUsernamePasswordMismatchException_H_
