//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\exception\UsernamePasswordMismatchException.java
//

#include "UsernamePasswordMismatchException.h"

@implementation RtdcCoreExceptionUsernamePasswordMismatchException

- (instancetype)initWithNSString:(NSString *)message {
  return [super initWithNSString:message];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "UsernamePasswordMismatchException", NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _RtdcCoreExceptionUsernamePasswordMismatchException = { "UsernamePasswordMismatchException", "rtdc.core.exception", NULL, 0x1, 1, methods, 0, NULL, 0, NULL};
  return &_RtdcCoreExceptionUsernamePasswordMismatchException;
}

@end
