//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/controller/UserListController.java
//

#ifndef _ControllerUserListController_H_
#define _ControllerUserListController_H_

@class ModelUser;
@protocol JavaUtilList;
@protocol RtdcCoreViewUserListView;

#import "JreEmulation.h"
#include "AsyncCallback.h"

@interface ControllerUserListController : NSObject {
 @public
  id<RtdcCoreViewUserListView> view_;
}

- (instancetype)initWithRtdcCoreViewUserListView:(id<RtdcCoreViewUserListView>)view;

- (void)onClickUserWithModelUser:(ModelUser *)user;

- (void)onClickNewUser;

- (void)dealloc;

- (void)copyAllFieldsTo:(ControllerUserListController *)other;

@end

__attribute__((always_inline)) inline void ControllerUserListController_init() {}

J2OBJC_FIELD_SETTER(ControllerUserListController, view_, id<RtdcCoreViewUserListView>)

typedef ControllerUserListController RtdcCoreControllerUserListController;

@interface ControllerUserListController_$1 : NSObject < ServiceAsyncCallback > {
 @public
  ControllerUserListController *this$0_;
}

- (void)onSuccessWithId:(id<JavaUtilList>)users;

- (void)onErrorWithNSString:(NSString *)message;

- (instancetype)initWithControllerUserListController:(ControllerUserListController *)outer$;

- (void)dealloc;

- (void)copyAllFieldsTo:(ControllerUserListController_$1 *)other;

@end

__attribute__((always_inline)) inline void ControllerUserListController_$1_init() {}

J2OBJC_FIELD_SETTER(ControllerUserListController_$1, this$0_, ControllerUserListController *)

#endif // _ControllerUserListController_H_
