//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/view/UserListView.java
//

#ifndef _UserListView_H_
#define _UserListView_H_

#include "J2ObjC_header.h"
#include "View.h"

@protocol JavaUtilList;

@protocol ViewUserListView < ViewView, NSObject, JavaObject >

- (void)setUsersWithJavaUtilList:(id<JavaUtilList>)users;

@end

J2OBJC_EMPTY_STATIC_INIT(ViewUserListView)

J2OBJC_TYPE_LITERAL_HEADER(ViewUserListView)

#define RtdcCoreViewUserListView ViewUserListView

#endif // _UserListView_H_
