//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/exception/UsernamePasswordMismatchException.java
//

#ifndef _UsernamePasswordMismatchException_H_
#define _UsernamePasswordMismatchException_H_

#include "ApiException.h"
#include "J2ObjC_header.h"

@interface ExceptionUsernamePasswordMismatchException : ExceptionApiException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ExceptionUsernamePasswordMismatchException)

FOUNDATION_EXPORT void ExceptionUsernamePasswordMismatchException_initWithNSString_(ExceptionUsernamePasswordMismatchException *self, NSString *message);

FOUNDATION_EXPORT ExceptionUsernamePasswordMismatchException *new_ExceptionUsernamePasswordMismatchException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ExceptionUsernamePasswordMismatchException)

@compatibility_alias RtdcCoreExceptionUsernamePasswordMismatchException ExceptionUsernamePasswordMismatchException;

#endif // _UsernamePasswordMismatchException_H_
