//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/view/UserListView.java
//

#include "J2ObjC_source.h"
#include "UserListView.h"
#include "java/util/List.h"

@interface ViewUserListView : NSObject

@end

@implementation ViewUserListView

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setUsersWithJavaUtilList:", "setUsers", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ViewUserListView = { 2, "UserListView", "rtdc.core.view", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ViewUserListView;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ViewUserListView)
