//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Z:\RTDC\core\src\main\java\rtdc\core\model\User.java
//

#ifndef _RtdcCoreModelUser_H_
#define _RtdcCoreModelUser_H_

@class RtdcCoreModelUnit;

#import "JreEmulation.h"
#include "JSONObject.h"
#include "java/io/Serializable.h"

@interface RtdcCoreModelUser : RtdcCoreJsonJSONObject < JavaIoSerializable > {
 @public
  NSString *authenticationToken_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)json;

- (jint)getId;

- (void)setIdWithInt:(jint)id_;

- (NSString *)getUsername;

- (void)setUsernameWithNSString:(NSString *)username;

- (NSString *)getSurname;

- (void)setSurnameWithNSString:(NSString *)surname;

- (NSString *)getFirstName;

- (void)setFirstNameWithNSString:(NSString *)firstName;

- (NSString *)getEmail;

- (void)setEmailWithNSString:(NSString *)email;

- (jlong)getPhone;

- (void)setPhoneWithLong:(jlong)phone;

- (NSString *)getPermission;

- (void)setPermissionWithNSString:(NSString *)permission;

- (NSString *)getRole;

- (void)setRoleWithNSString:(NSString *)role;

- (RtdcCoreModelUnit *)getUnit;

- (void)setUnitWithRtdcCoreModelUnit:(RtdcCoreModelUnit *)unit;

- (NSString *)getAuthenticationToken;

- (void)setAuthenticationTokenWithNSString:(NSString *)authenticationToken;

- (void)dealloc;

- (void)copyAllFieldsTo:(RtdcCoreModelUser *)other;

@end

__attribute__((always_inline)) inline void RtdcCoreModelUser_init() {}

J2OBJC_FIELD_SETTER(RtdcCoreModelUser, authenticationToken_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_ID_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, ID_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_USERNAME_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, USERNAME_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_SURNAME_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, SURNAME_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_EMAIL_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, EMAIL_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_PHONE_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, PHONE_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_FIRSTNAME_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, FIRSTNAME_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_PERMISSION_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, PERMISSION_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_ROLE_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, ROLE_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_UNIT_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, UNIT_, NSString *)

FOUNDATION_EXPORT NSString *RtdcCoreModelUser_AUTH_TOKEN_;
J2OBJC_STATIC_FIELD_GETTER(RtdcCoreModelUser, AUTH_TOKEN_, NSString *)

#endif // _RtdcCoreModelUser_H_
