//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/java/rtdc/core/exception/ValidationException.java
//

#include "J2ObjC_source.h"
#include "ValidationException.h"
#include "java/lang/RuntimeException.h"

@implementation ExceptionValidationException

- (instancetype)initWithNSString:(NSString *)message {
  ExceptionValidationException_initWithNSString_(self, message);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "ValidationException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _ExceptionValidationException = { 2, "ValidationException", "rtdc.core.exception", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ExceptionValidationException;
}

@end

void ExceptionValidationException_initWithNSString_(ExceptionValidationException *self, NSString *message) {
  JavaLangRuntimeException_initWithNSString_(self, message);
}

ExceptionValidationException *new_ExceptionValidationException_initWithNSString_(NSString *message) {
  ExceptionValidationException *self = [ExceptionValidationException alloc];
  ExceptionValidationException_initWithNSString_(self, message);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ExceptionValidationException)
