//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nicolasmenard/IdeaProjects/RTDC/core/src/main/resources/rtdc/core/super/java/lang/ref/WeakReference.java
//

#include "J2ObjC_source.h"
#include "WeakReference.h"

@interface JavaLangRefWeakReference () {
 @public
  id obj_;
}

@end

J2OBJC_FIELD_SETTER(JavaLangRefWeakReference, obj_, id)

@implementation JavaLangRefWeakReference

- (instancetype)initWithId:(id)param {
  JavaLangRefWeakReference_initWithId_(self, param);
  return self;
}

- (id)get {
  return obj_;
}

- (void)dealloc {
  RELEASE_(obj_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithId:", "WeakReference", NULL, 0x1, NULL, "(TT;)V" },
    { "get", NULL, "TT;", 0x1, NULL, "()TT;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "obj_", NULL, 0x2, "TT;", NULL, "TT;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _JavaLangRefWeakReference = { 2, "WeakReference", "java.lang.ref", NULL, 0x1, 2, methods, 1, fields, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_JavaLangRefWeakReference;
}

@end

void JavaLangRefWeakReference_initWithId_(JavaLangRefWeakReference *self, id param) {
  NSObject_init(self);
  JreStrongAssign(&self->obj_, param);
}

JavaLangRefWeakReference *new_JavaLangRefWeakReference_initWithId_(id param) {
  JavaLangRefWeakReference *self = [JavaLangRefWeakReference alloc];
  JavaLangRefWeakReference_initWithId_(self, param);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(JavaLangRefWeakReference)
