//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/io/InputSupplier.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonIoInputSupplier_RESTRICT
#define ComGoogleCommonIoInputSupplier_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoInputSupplier_RESTRICT
#if !defined (_ComGoogleCommonIoInputSupplier_) && (ComGoogleCommonIoInputSupplier_INCLUDE_ALL || ComGoogleCommonIoInputSupplier_INCLUDE)
#define _ComGoogleCommonIoInputSupplier_


@protocol ComGoogleCommonIoInputSupplier < NSObject, JavaObject >

- (id)getInput;

@end

__attribute__((always_inline)) inline void ComGoogleCommonIoInputSupplier_init() {}
#endif
