//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/io/LittleEndianDataInputStream.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonIoLittleEndianDataInputStream_RESTRICT
#define ComGoogleCommonIoLittleEndianDataInputStream_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoLittleEndianDataInputStream_RESTRICT
#if !defined (_ComGoogleCommonIoLittleEndianDataInputStream_) && (ComGoogleCommonIoLittleEndianDataInputStream_INCLUDE_ALL || ComGoogleCommonIoLittleEndianDataInputStream_INCLUDE)
#define _ComGoogleCommonIoLittleEndianDataInputStream_

@class IOSByteArray;
@class JavaIoInputStream;

#define JavaIoFilterInputStream_RESTRICT 1
#define JavaIoFilterInputStream_INCLUDE 1
#include "java/io/FilterInputStream.h"

#define JavaIoDataInput_RESTRICT 1
#define JavaIoDataInput_INCLUDE 1
#include "java/io/DataInput.h"


@interface ComGoogleCommonIoLittleEndianDataInputStream : JavaIoFilterInputStream < JavaIoDataInput > {
}

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (NSString *)readLine;

- (void)readFullyWithByteArray:(IOSByteArray *)b;

- (void)readFullyWithByteArray:(IOSByteArray *)b
                       withInt:(jint)off
                       withInt:(jint)len;

- (jint)skipBytesWithInt:(jint)n;

- (jint)readUnsignedByte;

- (jint)readUnsignedShort;

- (jint)readInt;

- (jlong)readLong;

- (jfloat)readFloat;

- (jdouble)readDouble;

- (NSString *)readUTF;

- (jshort)readShort;

- (jchar)readChar;

- (jbyte)readByte;

- (jboolean)readBoolean;

@end

__attribute__((always_inline)) inline void ComGoogleCommonIoLittleEndianDataInputStream_init() {}
#endif
