//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/guava/sources/com/google/common/io/OutputSupplier.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonIoOutputSupplier_RESTRICT
#define ComGoogleCommonIoOutputSupplier_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoOutputSupplier_RESTRICT
#if !defined (_ComGoogleCommonIoOutputSupplier_) && (ComGoogleCommonIoOutputSupplier_INCLUDE_ALL || ComGoogleCommonIoOutputSupplier_INCLUDE)
#define _ComGoogleCommonIoOutputSupplier_


@protocol ComGoogleCommonIoOutputSupplier < NSObject, JavaObject >

- (id)getOutput;

@end

__attribute__((always_inline)) inline void ComGoogleCommonIoOutputSupplier_init() {}
#endif
