//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kstanger/j2objc-0.9.5/j2objc/junit/build_result/java/junit/textui/ResultPrinter.java
//

#ifndef _JunitTextuiResultPrinter_H_
#define _JunitTextuiResultPrinter_H_

@class JavaIoPrintStream;
@class JavaLangThrowable;
@class JunitFrameworkAssertionFailedError;
@class JunitFrameworkTestFailure;
@class JunitFrameworkTestResult;
@protocol JavaUtilEnumeration;
@protocol JunitFrameworkTest;

#import "JreEmulation.h"
#include "junit/framework/TestListener.h"

@interface JunitTextuiResultPrinter : NSObject < JunitFrameworkTestListener > {
 @public
  JavaIoPrintStream *fWriter_;
  jint fColumn_;
}

- (instancetype)initWithJavaIoPrintStream:(JavaIoPrintStream *)writer;

- (void)printWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result
                                 withLong:(jlong)runTime;

- (void)printWaitPrompt;

- (void)printHeaderWithLong:(jlong)runTime;

- (void)printErrorsWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;

- (void)printFailuresWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;

- (void)printDefectsWithJavaUtilEnumeration:(id<JavaUtilEnumeration>)booBoos
                                    withInt:(jint)count
                               withNSString:(NSString *)type;

- (void)printDefectWithJunitFrameworkTestFailure:(JunitFrameworkTestFailure *)booBoo
                                         withInt:(jint)count;

- (void)printDefectHeaderWithJunitFrameworkTestFailure:(JunitFrameworkTestFailure *)booBoo
                                               withInt:(jint)count;

- (void)printDefectTraceWithJunitFrameworkTestFailure:(JunitFrameworkTestFailure *)booBoo;

- (void)printFooterWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;

- (NSString *)elapsedTimeAsStringWithLong:(jlong)runTime;

- (JavaIoPrintStream *)getWriter;

- (void)addErrorWithJunitFrameworkTest:(id<JunitFrameworkTest>)test
                 withJavaLangThrowable:(JavaLangThrowable *)t;

- (void)addFailureWithJunitFrameworkTest:(id<JunitFrameworkTest>)test
  withJunitFrameworkAssertionFailedError:(JunitFrameworkAssertionFailedError *)t;

- (void)endTestWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;

- (void)startTestWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;

- (void)dealloc;

- (void)copyAllFieldsTo:(JunitTextuiResultPrinter *)other;

@end

__attribute__((always_inline)) inline void JunitTextuiResultPrinter_init() {}

J2OBJC_FIELD_SETTER(JunitTextuiResultPrinter, fWriter_, JavaIoPrintStream *)

#endif // _JunitTextuiResultPrinter_H_
