//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/cert/CRLException.java
//

#ifndef _JavaSecurityCertCRLException_H_
#define _JavaSecurityCertCRLException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/security/GeneralSecurityException.h"

#define JavaSecurityCertCRLException_serialVersionUID -6694728944094197147LL

@interface JavaSecurityCertCRLException : JavaSecurityGeneralSecurityException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

__attribute__((always_inline)) inline void JavaSecurityCertCRLException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityCertCRLException, serialVersionUID, jlong)

#endif // _JavaSecurityCertCRLException_H_
