//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/charset/CodingErrorAction.java
//

#ifndef _JavaNioCharsetCodingErrorAction_H_
#define _JavaNioCharsetCodingErrorAction_H_

#import "JreEmulation.h"

@interface JavaNioCharsetCodingErrorAction : NSObject {
}

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL JavaNioCharsetCodingErrorAction_initialized;
J2OBJC_STATIC_INIT(JavaNioCharsetCodingErrorAction)

FOUNDATION_EXPORT JavaNioCharsetCodingErrorAction *JavaNioCharsetCodingErrorAction_IGNORE_;
J2OBJC_STATIC_FIELD_GETTER(JavaNioCharsetCodingErrorAction, IGNORE_, JavaNioCharsetCodingErrorAction *)

FOUNDATION_EXPORT JavaNioCharsetCodingErrorAction *JavaNioCharsetCodingErrorAction_REPLACE_;
J2OBJC_STATIC_FIELD_GETTER(JavaNioCharsetCodingErrorAction, REPLACE_, JavaNioCharsetCodingErrorAction *)

FOUNDATION_EXPORT JavaNioCharsetCodingErrorAction *JavaNioCharsetCodingErrorAction_REPORT_;
J2OBJC_STATIC_FIELD_GETTER(JavaNioCharsetCodingErrorAction, REPORT_, JavaNioCharsetCodingErrorAction *)

#endif // _JavaNioCharsetCodingErrorAction_H_
