//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/charset/UnmappableCharacterException.java
//

#ifndef _JavaNioCharsetUnmappableCharacterException_H_
#define _JavaNioCharsetUnmappableCharacterException_H_

#import "JreEmulation.h"
#include "java/nio/charset/CharacterCodingException.h"

#define JavaNioCharsetUnmappableCharacterException_serialVersionUID -7026962371537706123LL

@interface JavaNioCharsetUnmappableCharacterException : JavaNioCharsetCharacterCodingException {
}

- (instancetype)initWithInt:(jint)length;

- (jint)getInputLength;

- (NSString *)getMessage;

@end

__attribute__((always_inline)) inline void JavaNioCharsetUnmappableCharacterException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaNioCharsetUnmappableCharacterException, serialVersionUID, jlong)

#endif // _JavaNioCharsetUnmappableCharacterException_H_
