//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/text/util/Rfc822Token.java
//

#ifndef _AndroidTextUtilRfc822Token_H_
#define _AndroidTextUtilRfc822Token_H_

#import "JreEmulation.h"

@interface AndroidTextUtilRfc822Token : NSObject {
}

- (instancetype)initWithNSString:(NSString *)name
                    withNSString:(NSString *)address
                    withNSString:(NSString *)comment;

- (NSString *)getName;

- (NSString *)getAddress;

- (NSString *)getComment;

- (void)setNameWithNSString:(NSString *)name;

- (void)setAddressWithNSString:(NSString *)address;

- (void)setCommentWithNSString:(NSString *)comment;

- (NSString *)description;

+ (NSString *)quoteNameIfNecessaryWithNSString:(NSString *)name;

+ (NSString *)quoteNameWithNSString:(NSString *)name;

+ (NSString *)quoteCommentWithNSString:(NSString *)comment;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)o;

@end

__attribute__((always_inline)) inline void AndroidTextUtilRfc822Token_init() {}
FOUNDATION_EXPORT NSString *AndroidTextUtilRfc822Token_quoteNameIfNecessaryWithNSString_(NSString *name);
FOUNDATION_EXPORT NSString *AndroidTextUtilRfc822Token_quoteNameWithNSString_(NSString *name);
FOUNDATION_EXPORT NSString *AndroidTextUtilRfc822Token_quoteCommentWithNSString_(NSString *comment);

#endif // _AndroidTextUtilRfc822Token_H_
