//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/Dictionary.java
//

#ifndef _JavaUtilDictionary_H_
#define _JavaUtilDictionary_H_

@protocol JavaUtilEnumeration;

#import "JreEmulation.h"

@interface JavaUtilDictionary : NSObject {
}

- (instancetype)init;

- (id<JavaUtilEnumeration>)elements;

- (id)getWithId:(id)key;

- (jboolean)isEmpty;

- (id<JavaUtilEnumeration>)keys;

- (id)putWithId:(id)key
         withId:(id)value;

- (id)removeWithId:(id)key;

- (jint)size;

@end

__attribute__((always_inline)) inline void JavaUtilDictionary_init() {}

#endif // _JavaUtilDictionary_H_
