//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/IllegalFormatCodePointException.java
//

#ifndef _JavaUtilIllegalFormatCodePointException_H_
#define _JavaUtilIllegalFormatCodePointException_H_

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "java/util/IllegalFormatException.h"

#define JavaUtilIllegalFormatCodePointException_serialVersionUID 19080630LL

@interface JavaUtilIllegalFormatCodePointException : JavaUtilIllegalFormatException < JavaIoSerializable > {
}

- (instancetype)initWithInt:(jint)c;

- (jint)getCodePoint;

- (NSString *)getMessage;

@end

__attribute__((always_inline)) inline void JavaUtilIllegalFormatCodePointException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaUtilIllegalFormatCodePointException, serialVersionUID, jlong)

#endif // _JavaUtilIllegalFormatCodePointException_H_
