//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/IllegalFormatWidthException.java
//

#ifndef _JavaUtilIllegalFormatWidthException_H_
#define _JavaUtilIllegalFormatWidthException_H_

#import "JreEmulation.h"
#include "java/util/IllegalFormatException.h"

#define JavaUtilIllegalFormatWidthException_serialVersionUID 16660902LL

@interface JavaUtilIllegalFormatWidthException : JavaUtilIllegalFormatException {
}

- (instancetype)initWithInt:(jint)w;

- (jint)getWidth;

- (NSString *)getMessage;

@end

__attribute__((always_inline)) inline void JavaUtilIllegalFormatWidthException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaUtilIllegalFormatWidthException, serialVersionUID, jlong)

#endif // _JavaUtilIllegalFormatWidthException_H_
